//! Selection-specific Rust models with independent presence and nullability.
use crate::render::{rust_field_name, type_name};
use anyhow::{Context, Result, ensure};
use poolster_core::native::{GraphqlOperations, ModelField, ModelKind, ModelType};
use std::{
    collections::{BTreeMap, BTreeSet},
    fmt::Write,
};
pub(super) struct Models<'a> {
    contract: &'a GraphqlOperations,
    mappings: BTreeMap<String, super::GraphqlScalarMapping>,
    names: BTreeSet<String>,
    input_names: BTreeMap<String, String>,
    pub source: String,
    pub files: BTreeMap<String, String>,
}
impl<'a> Models<'a> {
    #[cfg(test)]
    pub fn new(contract: &'a GraphqlOperations) -> Self {
        Self::with_mappings(contract, &BTreeMap::new())
    }
    #[cfg(test)]
    pub fn with_mappings(
        contract: &'a GraphqlOperations,
        mappings: &BTreeMap<String, super::GraphqlScalarMapping>,
    ) -> Self {
        Self::with_reserved(contract, mappings, &[])
    }
    pub fn with_reserved(
        contract: &'a GraphqlOperations,
        mappings: &BTreeMap<String, super::GraphqlScalarMapping>,
        reserved: &[String],
    ) -> Self {
        let mut names: BTreeSet<_> = [
            "String",
            "Vec",
            "Option",
            "Box",
            "Self",
            "Presence",
            "Optional",
            "GraphqlResponse",
            "GraphqlHttpTransport",
            "GraphqlSubscription",
            "GraphqlScalarCodecs",
            "GraphqlIncrementalStream",
            "GraphqlIncrementalEvent",
            "GraphqlIncrementalSnapshot",
            "GraphqlTransportError",
            "GraphqlError",
            "GraphqlErrorLocation",
            "Result",
            "Serialize",
            "Deserialize",
        ]
        .into_iter()
        .map(str::to_owned)
        .collect();
        names.extend(reserved.iter().cloned());
        let input_names = contract
            .input_objects
            .keys()
            .map(|name| (name.clone(), unique(&mut names, &type_name(name))))
            .collect();
        Self {
            contract,
            mappings: mappings.clone(),
            names,
            input_names,
            files: BTreeMap::new(),
            source: String::from(
                "// Generated by Poolster.\nuse serde::{Deserialize, Serialize};\nuse crate::graphql_runtime::{Presence, Optional};\n",
            ),
        }
    }
    pub fn input_objects(&mut self) -> Result<()> {
        for (original, fields) in &self.contract.input_objects {
            let name = self.input_names[original].clone();
            self.object(&name, fields, true, Some(original))?;
        }
        Ok(())
    }
    pub fn variables(&mut self, name: &str, fields: &[ModelField]) -> Result<String> {
        let name = self.allocate(name);
        self.object(&name, fields, true, None)?;
        Ok(name)
    }
    pub fn result(&mut self, name: &str, ty: &ModelType) -> Result<String> {
        ensure!(
            !ty.nullable && matches!(ty.kind, ModelKind::Object(_)),
            "GraphQL result root must be a nonnullable selected object"
        );
        self.ty(ty, name, false, None)
    }
    fn allocate(&mut self, name: &str) -> String {
        unique(&mut self.names, &type_name(name))
    }
    fn object(
        &mut self,
        name: &str,
        fields: &[ModelField],
        input: bool,
        current: Option<&str>,
    ) -> Result<()> {
        let body = self.fields(fields, name, input, current)?;
        let default = if input && fields.iter().all(|field| field.optional) {
            ", Default"
        } else {
            ""
        };
        self.declare(name, format!("#[derive(Clone, Debug, Serialize, Deserialize{default})]\n#[serde(deny_unknown_fields)]\npub struct {name} {{\n{body}}}\n"));
        Ok(())
    }
    fn fields(
        &mut self,
        fields: &[ModelField],
        path: &str,
        input: bool,
        current: Option<&str>,
    ) -> Result<String> {
        let mut source = String::new();
        let mut names = BTreeSet::new();
        let mut wire_names = BTreeSet::new();
        for field in fields {
            ensure!(
                wire_names.insert(&field.name),
                "duplicate GraphQL field {}",
                field.name
            );
            let name = unique(&mut names, &rust_field_name(&field.name));
            let mut bare = field.ty.clone();
            bare.nullable = false;
            let value = self.ty(
                &bare,
                &format!("{path}{}", type_name(&field.name)),
                input,
                current,
            )?;
            let ty = if field.optional {
                let wrapper = if field.ty.nullable {
                    "Presence"
                } else {
                    "Optional"
                };
                writeln!(
                    source,
                    "    #[serde(default, skip_serializing_if = \"{wrapper}::is_absent\")]"
                )?;
                format!("{wrapper}<{value}>")
            } else if field.ty.nullable {
                writeln!(
                    source,
                    "    #[serde(deserialize_with = \"crate::graphql_runtime::required_nullable\")]"
                )?;
                format!("Option<{value}>")
            } else {
                value
            };
            writeln!(
                source,
                "    #[serde(rename = {})]\n    pub {name}: {ty},",
                serde_json::to_string(&field.name)?
            )?;
        }
        Ok(source)
    }
    fn ty(
        &mut self,
        ty: &ModelType,
        path: &str,
        input: bool,
        current: Option<&str>,
    ) -> Result<String> {
        let value = match &ty.kind {
            ModelKind::Scalar(name) => {
                if let Some(mapping) = self.mappings.get(name) {
                    if input {
                        mapping.input.clone()
                    } else {
                        mapping.output.clone()
                    }
                } else {
                    match name.as_str() {
                        "String" | "ID" => "String",
                        "Int" => "i32",
                        "Float" => "f64",
                        "Boolean" => "bool",
                        _ => "serde_json::Value",
                    }
                    .into()
                }
            }
            ModelKind::Named(name) => {
                let resolved = self
                    .input_names
                    .get(name)
                    .with_context(|| format!("GraphQL references missing input type {name}"))?
                    .clone();
                if current.is_some_and(|from| self.reaches(name, from, &mut BTreeSet::new())) {
                    format!("Box<{resolved}>")
                } else {
                    resolved
                }
            }
            ModelKind::List(item) => format!(
                "Vec<{}>",
                self.ty(item, &format!("{path}Item"), input, current)?
            ),
            ModelKind::Object(fields) => {
                let name = self.allocate(path);
                self.object(&name, fields, input, current)?;
                name
            }
            ModelKind::Literal(value) => self.enumeration(path, std::slice::from_ref(value))?,
            ModelKind::Enum(values) => self.enumeration(path, values)?,
            ModelKind::Union(variants) => {
                ensure!(
                    !variants.is_empty(),
                    "GraphQL abstract selection has no concrete variants"
                );
                let name = self.allocate(path);
                let mut body = String::new();
                let mut variant_names = BTreeSet::from(["Self".into()]);
                let tags: Option<Vec<_>> = variants
                    .iter()
                    .map(|variant| match &variant.kind {
                        ModelKind::Object(fields) => fields
                            .iter()
                            .find(|f| f.name == "__typename")
                            .and_then(|f| {
                                if let ModelKind::Literal(tag) = &f.ty.kind {
                                    Some(tag.clone())
                                } else {
                                    None
                                }
                            }),
                        _ => None,
                    })
                    .collect();
                if let Some(tags) = tags {
                    let mut wire_tags = BTreeSet::new();
                    for (variant, tag) in variants.iter().zip(tags) {
                        ensure!(
                            wire_tags.insert(tag.clone()),
                            "duplicate GraphQL abstract typename {tag}"
                        );
                        let variant_name = unique(&mut variant_names, &type_name(&tag));
                        let ModelKind::Object(fields) = &variant.kind else {
                            unreachable!()
                        };
                        let fields: Vec<_> = fields
                            .iter()
                            .filter(|f| f.name != "__typename")
                            .cloned()
                            .collect();
                        let content =
                            self.fields(&fields, &format!("{name}{variant_name}"), input, current)?;
                        writeln!(
                            body,
                            "    #[serde(rename = {})]\n    {variant_name} {{\n{content}    }},",
                            serde_json::to_string(&tag)?
                        )?;
                    }
                    self.declare(&name, format!("#[derive(Clone, Debug, Serialize, Deserialize)]\n#[serde(tag = \"__typename\", deny_unknown_fields)]\npub enum {name} {{\n{body}}}\n"));
                } else {
                    for (index, variant) in variants.iter().enumerate() {
                        if let ModelKind::Object(fields) = &variant.kind {
                            for previous in &variants[..index] {
                                if let ModelKind::Object(other) = &previous.kind {
                                    let keys: BTreeSet<_> =
                                        fields.iter().map(|f| &f.name).collect();
                                    let other_keys: BTreeSet<_> =
                                        other.iter().map(|f| &f.name).collect();
                                    ensure!(
                                        keys != other_keys || fields == other,
                                        "ambiguous GraphQL abstract selection: variants use the same response fields with different types; select __typename"
                                    );
                                }
                            }
                        }
                    }
                    for (index, variant) in variants.iter().enumerate() {
                        let variant_type =
                            self.ty(variant, &format!("{name}Variant{index}"), input, current)?;
                        writeln!(body, "    Variant{index}({variant_type}),")?;
                    }
                    self.declare(&name, format!("#[derive(Clone, Debug, Serialize, Deserialize)]\n#[serde(untagged)]\npub enum {name} {{\n{body}}}\n"));
                }
                name
            }
        };
        Ok(if ty.nullable {
            format!("Option<{value}>")
        } else {
            value
        })
    }
    fn enumeration(&mut self, path: &str, values: &[String]) -> Result<String> {
        ensure!(!values.is_empty(), "GraphQL contract has an empty enum");
        let name = self.allocate(path);
        let mut names = BTreeSet::from(["Self".into()]);
        let mut wires = BTreeSet::new();
        let mut body = String::new();
        for value in values {
            ensure!(wires.insert(value), "duplicate GraphQL enum value {value}");
            let variant = unique(&mut names, &type_name(value));
            writeln!(
                body,
                "    #[serde(rename = {})]\n    {variant},",
                serde_json::to_string(value)?
            )?;
        }
        self.declare(&name, format!("#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]\npub enum {name} {{\n{body}}}\n"));
        Ok(name)
    }
    fn declare(&mut self, name: &str, declaration: String) {
        self.source.push_str(&declaration);
        self.source.push('\n');
        self.files.insert(name.to_owned(), declaration + "\n");
    }
    fn reaches(&self, from: &str, target: &str, seen: &mut BTreeSet<String>) -> bool {
        if from == target {
            return true;
        }
        if !seen.insert(from.into()) {
            return false;
        }
        fn edges(ty: &ModelType, out: &mut Vec<String>) {
            match &ty.kind {
                ModelKind::Named(name) => out.push(name.clone()),
                ModelKind::List(item) => edges(item, out),
                ModelKind::Object(fields) => {
                    for field in fields {
                        edges(&field.ty, out)
                    }
                }
                _ => {}
            }
        }
        self.contract.input_objects.get(from).is_some_and(|fields| {
            fields.iter().any(|field| {
                let mut names = Vec::new();
                edges(&field.ty, &mut names);
                names.iter().any(|name| self.reaches(name, target, seen))
            })
        })
    }
}
fn unique(names: &mut BTreeSet<String>, base: &str) -> String {
    let mut candidate = base.to_owned();
    let mut suffix = 2;
    while !names.insert(candidate.clone()) {
        candidate = format!("{base}{suffix}");
        suffix += 1;
    }
    candidate
}

#[cfg(test)]
#[path = "model_tests.rs"]
mod tests;
