[package]
name = "poolster-plugin-dotnet"
version.workspace = true
edition = "2024"
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Deprecated compatibility facade for Poolster's C# SDK generator"
publish = ["crates-io"]

[dependencies]
poolster-core = { version = "0.5.0-alpha.1", path = "../../core" }
poolster-plugin-csharp = { version = "0.5.0-alpha.1", path = "../csharp" }
