[workspace]
resolver = "3"
members = [
    "crates/kaji-core",
    "crates/kaji",
    "crates/plugins/go",
    "crates/plugins/python",
    "crates/plugins/php",
    "crates/plugins/java",
    "crates/plugins/dotnet",
    "crates/plugins/elixir",
]
default-members = ["crates/kaji"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/rlvtapp/Kaji"
homepage = "https://github.com/rlvtapp/Kaji"
rust-version = "1.85"
