[workspace]
resolver = "3"
members = [
    "crates/inputs/bundle",
    "crates/inputs/openapi",
    "crates/inputs/graphql",
    "crates/inputs/asyncapi",
    "crates/inputs/arazzo",
    "crates/inputs/protobuf",
    "crates/inputs/capnproto",
    "crates/core",
    "crates/facade",
    "crates/cli",
    "crates/node",
    "crates/plugins/rust",
    "crates/plugins/typescript",
    "crates/plugins/typescript-cli",
    "crates/plugins/rust-cli",
    "crates/plugins/go",
    "crates/plugins/python",
    "crates/plugins/php",
    "crates/plugins/symfony",
    "crates/plugins/terraform",
    "crates/plugins/postman",
    "crates/plugins/java",
    "crates/plugins/csharp",
    "crates/plugins/dotnet",
    "crates/plugins/elixir",
    "crates/plugins/ruby",
    "crates/plugins/swift",
]
default-members = ["crates/facade"]

[workspace.package]
version = "0.5.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/rlvtapp/poolster"
homepage = "https://github.com/rlvtapp/poolster"
rust-version = "1.85"
