//! Selection-specific source and artifact emission.
use super::*;

pub(super) fn generate(generator: &Graphql, cx: &mut PluginContext<'_, TypeScript>) -> Result<()> {
    let mut oversized = Vec::new();
    let contract = cx.inputs.get::<GraphqlOperations>()?;
    scalars::validate_mappings(&generator.scalars, contract)?;
    if contract.operations.is_empty() {
        bail!("GraphQL generation requires operation documents");
    }
    let mut out = String::from(
        "/** Generated by Poolster. */\nimport type { GraphqlTransport, SubscriptionTransport, GraphqlResult, RequestOptions } from './graphql-runtime.js';\n",
    );
    let mut model_exports = String::new();
    let mut operation_exports = String::new();
    let mut file_names = std::collections::BTreeSet::new();
    let mut names = [
        "GraphqlTransport",
        "SubscriptionTransport",
        "GraphqlResult",
        "RequestOptions",
        "GraphqlError",
        "GraphqlHttpError",
        "GraphqlProtocolError",
        "createGraphqlHttpTransport",
        "Array",
        "Promise",
        "AsyncIterable",
        "createClient",
        "GraphqlClientOptions",
        "GraphqlBoundClient",
        "GraphqlScalarCodecs",
        "ScalarCodecMap",
        "ScalarCodec",
        "ScalarShape",
        "ScalarInputShapes",
        "GraphqlSseOptions",
        "createGraphqlSseTransport",
        "parseGraphqlResult",
        "withGraphqlScalarCodecs",
        "encodeGraphqlVariables",
        "decodeGraphqlResult",
        "decodeGraphqlStream",
        "scalarInputShapes",
        "variablesShape",
        "resultShape",
        "HeadersInit",
    ]
    .into_iter()
    .map(str::to_owned)
    .collect::<std::collections::BTreeSet<_>>();
    for fields in contract.input_objects.values() {
        for field in fields {
            validate_type(&field.ty, contract)?;
        }
    }
    for op in &contract.operations {
        validate_type(&op.result, contract)?;
        for field in &op.variables {
            validate_type(&field.ty, contract)?;
        }
    }
    for (name, fields) in &contract.input_objects {
        identifier(name)?;
        let file_name = poolster_core::files::source_file_stem(name);
        anyhow::ensure!(
            file_names.insert(file_name.to_ascii_lowercase()),
            "GraphQL source filename collision: {name}"
        );
        let mut model_source = String::from("/** Generated by Poolster. */\n");
        let mut dependencies = std::collections::BTreeSet::new();
        for field in fields {
            named_dependencies(&field.ty, &mut dependencies);
        }
        for other in &dependencies {
            if other != name {
                writeln!(
                    model_source,
                    "import type {{ {other} }} from './{}.js';",
                    poolster_core::files::source_file_stem(other)
                )?;
            }
        }
        writeln!(
            model_source,
            "export type {name} = {};",
            render_fields(fields, &generator.scalars, true)
        )?;
        if !names.insert(name.clone()) {
            bail!("GraphQL TypeScript symbol collision: {name}");
        }
        emit_source(
            &mut cx.files,
            GeneratedFile::new(format!("graphql/models/{file_name}.ts"), model_source)?,
            &mut oversized,
        )?;
        writeln!(
            model_exports,
            "export type {{ {name} }} from './graphql/models/{file_name}.js';"
        )?;
        cx.workspace.declare("graphql", name, generator.kind())?;
    }
    let mut operations = BTreeMap::new();
    let mut ordered_operations: Vec<_> = contract.operations.iter().collect();
    ordered_operations.sort_by_key(|op| &op.name);
    for op in ordered_operations {
        identifier(&op.name)?;
        let mut symbols = Vec::new();
        for name in [
            format!("{}Variables", op.name),
            format!("{}Result", op.name),
            op.name.clone(),
        ] {
            if !names.insert(name.clone()) {
                bail!("GraphQL TypeScript symbol collision: {name}");
            }
            symbols.push(cx.workspace.declare("graphql", &name, generator.kind())?);
        }
        let raw_name = crate::symbols::camel(&op.name);
        let raw_function = if raw_name == op.name {
            symbols[2].clone()
        } else {
            if !names.insert(raw_name.clone()) {
                bail!("GraphQL TypeScript symbol collision: {raw_name}");
            }
            cx.workspace
                .declare("graphql", &raw_name, generator.kind())?
        };
        operations.insert(
            op.name.clone(),
            GraphqlOperationSymbols {
                variables: symbols[0].clone(),
                result: symbols[1].clone(),
                function: symbols[2].clone(),
                raw_function,
                kind: op.kind,
            },
        );
        let mut model_source = String::from("/** Generated by Poolster. */\n");
        let file_name = poolster_core::files::source_file_stem(&op.name);
        anyhow::ensure!(
            file_names.insert(file_name.to_ascii_lowercase()),
            "GraphQL source filename collision: {}",
            op.name
        );
        let mut dependencies = std::collections::BTreeSet::new();
        for field in &op.variables {
            named_dependencies(&field.ty, &mut dependencies);
        }
        for input in &dependencies {
            writeln!(
                model_source,
                "import type {{ {input} }} from './{}.js';",
                poolster_core::files::source_file_stem(input)
            )?;
        }
        let variables = format!("{}Variables", op.name);
        let result = format!("{}Result", op.name);
        writeln!(
            model_source,
            "export type {variables} = {};",
            render_fields(&op.variables, &generator.scalars, true)
        )?;
        writeln!(
            model_source,
            "export type {result} = {};",
            render_type(&op.result, &generator.scalars, false)
        )?;
        emit_source(
            &mut cx.files,
            GeneratedFile::new(format!("graphql/models/{file_name}.ts"), model_source)?,
            &mut oversized,
        )?;
        writeln!(
            model_exports,
            "export type {{ {variables}, {result} }} from './graphql/models/{file_name}.js';"
        )?;
        let mut operation_source = format!(
            "/** Generated by Poolster. */\nimport type {{ GraphqlTransport, SubscriptionTransport, GraphqlResult, RequestOptions }} from '../../graphql-runtime.js';\nimport type {{ {variables}, {result} }} from '../models/{file_name}.js';\n"
        );
        operation_source.push_str("import { encodeGraphqlVariables, decodeGraphqlResult, decodeGraphqlStream } from '../../graphql-scalar-runtime.js';\nimport type { ScalarShape } from '../../graphql-scalar-runtime.js';\nimport { scalarInputShapes } from '../../graphql-codecs.js';\n");
        operation_source.push_str(&codecs::operation_shapes(op)?);
        let doc = serde_json::to_string(&op.document)?;
        let name = serde_json::to_string(&op.name)?;
        if op.kind == GraphqlOperationKind::Subscription {
            if !generator.subscriptions {
                bail!(
                    "GraphQL subscription {} requires separately enabled injected subscription transport capability",
                    op.name
                );
            }
            writeln!(
                operation_source,
                "export function {}(transport: SubscriptionTransport, variables: {variables}, options?: RequestOptions): AsyncIterable<GraphqlResult<{result}>> {{\n  const codecs = options?.scalarCodecs ?? transport.scalarCodecs;\n  return decodeGraphqlStream(\n    transport.subscribe<{result}>(\n      {doc},\n      {name},\n      encodeGraphqlVariables(variables, variablesShape, scalarInputShapes, codecs),\n      options,\n    ),\n    resultShape, scalarInputShapes, codecs,\n  );\n}}",
                op.name
            )?;
        } else {
            writeln!(
                operation_source,
                "export function {}(transport: GraphqlTransport, variables: {variables}, options?: RequestOptions): Promise<GraphqlResult<{result}>> {{\n  const codecs = options?.scalarCodecs ?? transport.scalarCodecs;\n  return transport.execute<{result}>(\n    {doc},\n    {name},\n    encodeGraphqlVariables(variables, variablesShape, scalarInputShapes, codecs),\n    options,\n  ).then(result => decodeGraphqlResult(result, resultShape, scalarInputShapes, codecs));\n}}",
                op.name
            )?;
        }
        let alias = crate::symbols::camel(&op.name);
        if alias != op.name {
            writeln!(operation_source, "export const {alias} = {};", op.name)?;
        }
        emit_source(
            &mut cx.files,
            GeneratedFile::new(
                format!("graphql/operations/{file_name}.ts"),
                operation_source,
            )?,
            &mut oversized,
        )?;
        writeln!(
            operation_exports,
            "export * from './graphql/operations/{file_name}.js';"
        )?;
    }
    let mut client_files = BTreeMap::new();
    let methods = facade::render_files(
        &mut out,
        generator.style,
        contract,
        &generator.groups,
        &mut client_files,
    )?;
    for (path, content) in client_files {
        emit_source(
            &mut cx.files,
            GeneratedFile::new(path, content)?,
            &mut oversized,
        )?;
    }
    let factory = if generator.style != GraphqlStyle::Raw {
        cx.workspace
            .declare("graphql", "GraphqlClientOptions", generator.kind())?;
        cx.workspace
            .declare("graphql", "GraphqlBoundClient", generator.kind())?;
        Some(
            cx.workspace
                .declare("graphql", "createClient", generator.kind())?,
        )
    } else {
        None
    };
    let mut entry = String::from(
        "/** Public GraphQL entry point. Generated by Poolster. */\nexport * from './graphql-models.js';\nexport * from './graphql-operations.js';\n",
    );
    if generator.style != GraphqlStyle::Raw {
        entry.push_str("export * from './graphql-client.js';\n");
        emit_source(
            &mut cx.files,
            GeneratedFile::new("graphql-client.ts", out)?,
            &mut oversized,
        )?;
    }
    for (category, exports) in [("models", model_exports), ("operations", operation_exports)] {
        let lines: Vec<_> = exports.lines().collect();
        let mut barrel = String::from("/** Generated exports. */\n");
        for (index, chunk) in lines.chunks(64).enumerate() {
            let source = chunk
                .join("\n")
                .replace(&format!("'./graphql/{category}/"), "'../")
                + "\n";
            emit_source(
                &mut cx.files,
                GeneratedFile::new(
                    format!("graphql/{category}/_exports/part_{index}.ts"),
                    source,
                )?,
                &mut oversized,
            )?;
            writeln!(
                barrel,
                "export * from './graphql/{category}/_exports/part_{index}.js';"
            )?;
        }
        emit_source(
            &mut cx.files,
            GeneratedFile::new(format!("graphql-{category}.ts"), barrel)?,
            &mut oversized,
        )?;
    }
    emit_source(
        &mut cx.files,
        GeneratedFile::new("graphql.ts", entry)?,
        &mut oversized,
    )?;
    emit_source(
        &mut cx.files,
        GeneratedFile::new(
            "graphql-runtime.ts",
            include_str!("runtime/runtime.ts.tmpl"),
        )?,
        &mut oversized,
    )?;
    for file in codecs::files(contract, &generator.scalars)? {
        emit_source(&mut cx.files, file, &mut oversized)?;
    }
    cx.workspace.export("graphql-codecs")?;
    cx.workspace.export("graphql-scalar-runtime")?;
    cx.workspace.export("graphql-sse")?;
    cx.workspace.export("graphql")?;
    cx.workspace.export("graphql-runtime")?;
    cx.workspace.package_file(GeneratedFile::new("package.json", serde_json::to_string_pretty(&serde_json::json!({"name": cx.settings.package_name.as_deref().unwrap_or("poolster-graphql-client"), "version":cx.common.package_version.as_deref().unwrap_or("0.0.0"), "type":"module", "main":"./dist/index.js", "types":"./dist/index.d.ts", "exports":{".":{"types":"./dist/index.d.ts","import":"./dist/index.js"}}, "scripts":{"build":"tsc -p tsconfig.json"}, "devDependencies":{"typescript":"5.9.3"}}))?)?)?;
    cx.workspace.package_file(GeneratedFile::new("tsconfig.json", "{\"compilerOptions\":{\"target\":\"ES2022\",\"module\":\"NodeNext\",\"moduleResolution\":\"NodeNext\",\"strict\":true,\"declaration\":true,\"outDir\":\"dist\",\"lib\":[\"ES2022\",\"DOM\"]},\"include\":[\"**/*.ts\"],\"exclude\":[\"dist\"]}\n")?)?;
    if !oversized.is_empty() {
        cx.files.emit(GeneratedFile::new(
            ".poolster/source-layout-diagnostics.json",
            serde_json::to_string_pretty(&oversized)?,
        )?)?;
    }
    cx.publish(GraphqlClient {
        operations,
        runtime_module: "graphql-runtime".into(),
        style: generator.style,
        factory,
        methods,
        definition: contract.clone(),
        scalars: generator.scalars.clone(),
    })
}
