[package]
name = "poolster-plugin-java"
version.workspace = true
edition = "2024"
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Native Java SDK generator for Poolster"
publish = false

[dependencies]
anyhow = "1.0.102"
poolster-core = { path = "../../core" }
serde_json = "1.0.138"

[dev-dependencies]
tempfile = "3.27.0"
