//! Native GraphQL clients preserve fixed operation selections and wire presence.
use crate::{Ruby, pascal_case, ruby_file_name, ruby_string, snake_case};
use anyhow::{Result, ensure};
use poolster_core::{
    GeneratedFile,
    engine::{Contract, Handle, Meta, Plugin, PluginContext, Provision, Requirement},
    native::{
        GraphqlIncrementalOperations, GraphqlOperationKind, GraphqlOperations, ModelKind, ModelType,
    },
};
use std::{
    collections::{BTreeMap, BTreeSet},
    fmt::Write,
};
#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub enum GraphqlStyle {
    Raw,
    Flat,
    #[default]
    Idiomatic,
}
pub struct GraphqlClient {
    pub methods: BTreeMap<String, String>,
}
impl Contract for GraphqlClient {
    const NAME: &'static str = "poolster.ruby.graphql-client.v1";
}
pub struct Graphql {
    meta: Meta,
    input: Option<Handle<GraphqlOperations>>,
    incremental_input: Option<Handle<GraphqlIncrementalOperations>>,
    subscriptions: bool,
    incremental: bool,
    style: GraphqlStyle,
    groups: BTreeMap<String, BTreeMap<String, String>>,
}
pub fn graphql(input: Option<Handle<GraphqlOperations>>) -> Graphql {
    Graphql {
        meta: Meta::new(),
        input,
        incremental_input: None,
        subscriptions: false,
        incremental: false,
        style: GraphqlStyle::default(),
        groups: BTreeMap::new(),
    }
}
pub fn graphql_incremental(input: Option<Handle<GraphqlIncrementalOperations>>) -> Graphql {
    let mut plugin = graphql(None);
    plugin.incremental_input = input;
    plugin.incremental = true;
    plugin
}
impl Graphql {
    pub fn subscriptions(mut self) -> Self {
        self.subscriptions = true;
        self
    }
    pub fn incremental_input(mut self, input: Handle<GraphqlIncrementalOperations>) -> Self {
        self.incremental_input = Some(input);
        self.incremental = true;
        self
    }
    pub fn raw(mut self) -> Self {
        self.style = GraphqlStyle::Raw;
        self
    }
    pub fn flat(mut self) -> Self {
        self.style = GraphqlStyle::Flat;
        self
    }
    pub fn idiomatic(mut self) -> Self {
        self.style = GraphqlStyle::Idiomatic;
        self
    }
    pub fn namespaced(self) -> Self {
        self.idiomatic()
    }
    pub fn groups(mut self, groups: BTreeMap<String, BTreeMap<String, String>>) -> Self {
        self.groups = groups;
        self
    }
    pub fn group(
        mut self,
        group: impl Into<String>,
        method: impl Into<String>,
        operation: impl Into<String>,
    ) -> Self {
        self.groups
            .entry(group.into())
            .or_default()
            .insert(method.into(), operation.into());
        self
    }
    pub fn handle(&self) -> Handle<GraphqlClient> {
        self.meta.handle()
    }
}
impl Plugin<Ruby> for Graphql {
    fn kind(&self) -> &'static str {
        "ruby-graphql"
    }
    fn meta(&self) -> &Meta {
        &self.meta
    }
    fn supports_native_input(&self) -> bool {
        true
    }
    fn requires(&self) -> Vec<Requirement> {
        if self.incremental {
            vec![Requirement::on(self.incremental_input)]
        } else {
            vec![Requirement::on(self.input)]
        }
    }
    fn provides(&self) -> Vec<Provision> {
        vec![Provision::of::<GraphqlClient>()]
    }
    fn generate(&self, cx: &mut PluginContext<'_, Ruby>) -> Result<()> {
        let name = cx
            .settings
            .package_name
            .as_deref()
            .unwrap_or("graphql_client");
        let version = cx.common.package_version.as_deref().unwrap_or("0.0.0");
        let contract = if self.incremental {
            &cx.inputs.get::<GraphqlIncrementalOperations>()?.definition
        } else {
            cx.inputs.get::<GraphqlOperations>()?
        };
        let (tree, methods) = render_advanced(
            contract,
            name,
            self.style,
            &self.groups,
            self.subscriptions,
            self.incremental,
        )?;
        let file = ruby_file_name(name);
        cx.files.append(tree)?;
        cx.files.emit(GeneratedFile::new(format!("{file}.gemspec"),format!("Gem::Specification.new do |s|\n s.name={}\n s.version={}\n s.summary='Selection-specific GraphQL client generated by Poolster'\n s.authors=['Poolster']\n s.required_ruby_version='>= 3.1'\n s.files=Dir['lib/**/*.rb','sig/**/*.rbs']\n s.require_paths=['lib']\nend\n",ruby_string(name),ruby_string(version)))?)?;
        cx.files.emit(GeneratedFile::new("README.md", "# GraphQL Ruby client\n\nFixed operation clients with raw, flat or grouped APIs. GraphqlResponse preserves partial data and errors. Models retain optional presence separately from null; RBS signatures describe selected types. Net::HTTP transport supports headers/timeouts. Opt-in distinct-connection graphql-sse subscriptions, multipart deferSpec=20220824 incremental frames and scalar_codecs callbacks are available. Intermediate frames retain raw incomplete data and final typed envelopes. No reconnect, multiplexing or alternate incremental dialect. Custom scalar host types remain untyped.\n")?)?;
        cx.publish(GraphqlClient { methods })
    }
}
fn method(value: &str) -> Result<String> {
    let name = snake_case(value);
    ensure!(
        !name.is_empty()
            && name
                .chars()
                .next()
                .is_some_and(|c| c.is_ascii_lowercase() || c == '_')
            && name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_'),
        "invalid Ruby GraphQL method {value}"
    );
    ensure!(
        ![
            "class",
            "def",
            "end",
            "module",
            "initialize",
            "transport",
            "subscribe",
            "incremental",
            "response",
            "query",
            "mutation",
            "send",
            "object_id",
            "respond_to",
            "to_h",
            "hash",
            "inspect",
            "freeze",
            "frozen",
            "clone",
            "dup",
            "method",
            "methods",
            "public_send",
            "tap",
            "then",
            "display",
            "nil",
            "true",
            "false",
            "new",
            "begin",
            "rescue",
            "ensure",
            "return",
            "raise",
            "yield",
            "super",
            "self",
            "while",
            "until",
            "if",
            "unless",
            "case",
            "when",
            "else",
            "elsif",
            "for",
            "in",
            "break",
            "next",
            "redo",
            "retry",
            "do",
            "alias",
            "and",
            "or",
            "not",
            "undef",
            "defined"
        ]
        .contains(&name.as_str()),
        "reserved Ruby GraphQL method {name}"
    );
    Ok(name)
}
mod models;
use models::Models;
#[cfg(test)]
fn render(
    contract: &GraphqlOperations,
    name: &str,
    style: GraphqlStyle,
    groups: &BTreeMap<String, BTreeMap<String, String>>,
) -> Result<(poolster_core::GeneratedTree, BTreeMap<String, String>)> {
    render_advanced(contract, name, style, groups, false, false)
}
mod render;
use render::render_advanced;

#[cfg(test)]
mod tests;

mod source_layout;
