//! GraphQL package assembly from owned operation contracts.
use super::*;

pub(super) fn render_advanced(
    contract: &GraphqlOperations,
    name: &str,
    style: GraphqlStyle,
    groups: &BTreeMap<String, BTreeMap<String, String>>,
    subscriptions: bool,
    incremental: bool,
) -> Result<(poolster_core::GeneratedTree, BTreeMap<String, String>)> {
    ensure!(
        !contract.operations.is_empty(),
        "Ruby GraphQL requires operation documents"
    );
    ensure!(
        !name.is_empty()
            && name
                .chars()
                .all(|c| c.is_ascii_alphanumeric() || "_-".contains(c)),
        "invalid Ruby GraphQL gem name"
    );
    ensure!(
        style == GraphqlStyle::Idiomatic || groups.is_empty(),
        "custom GraphQL groups require idiomatic style"
    );
    let module = pascal_case(name);
    ensure!(
        module
            .chars()
            .next()
            .is_some_and(|c| c.is_ascii_uppercase()),
        "invalid Ruby GraphQL module name"
    );
    ensure!(
        ![
            "Object",
            "Kernel",
            "Class",
            "Module",
            "String",
            "Array",
            "Hash",
            "Integer",
            "Float",
            "Numeric",
            "TrueClass",
            "FalseClass",
            "NilClass",
            "Exception",
            "StandardError",
            "Struct"
        ]
        .contains(&module.as_str()),
        "reserved Ruby GraphQL module name {module}"
    );
    let mut source = format!(
        "# Generated by Poolster. DO NOT EDIT.\nrequire 'json'\nrequire 'net/http'\nrequire 'uri'\nmodule {module}\n"
    );
    source.push_str(include_str!("runtime/runtime.rb.tmpl"));
    source.push_str(include_str!("runtime/streaming.rb.tmpl"));
    let runtime = format!("{source}end\n");
    let mut files = BTreeMap::<String, (String, String)>::new();
    let mut signatures = format!(
        "module {module}\n  class Model\n    def present?: (String | Symbol) -> bool\n    def to_h: () -> Hash[String, untyped]\n  end\n"
    );
    signatures.push_str("  class Transport\n    def initialize: (String, ?headers: Hash[String, String], ?timeout: Numeric, ?scalar_codecs: Hash[String | Symbol, untyped], ?max_frame_bytes: Integer) -> void\n  end\n  class GraphqlResponse[T]\n    def data: () -> T?\n    def errors: () -> Array[Hash[String, untyped]]\n    def extensions: () -> untyped\n    def data_present: () -> bool\n    def status: () -> Symbol\n    def require_data: () -> T\n  end\n");
    signatures.push_str("  class IncrementalFrame\n    def frame: () -> Hash[String, untyped]\n    def data: () -> untyped\n    def final: () -> GraphqlResponse[untyped]?\n  end\n");
    let runtime_signature = format!("{signatures}end\n");
    let mut methods = BTreeMap::new();
    let mut models = Models {
        files: BTreeMap::new(),
        names: [
            "Client",
            "Model",
            "Transport",
            "GraphqlResponse",
            "IncrementalFrame",
            "StreamParser",
            "GraphqlErrors",
            "HttpError",
            "Object",
            "Kernel",
            "Class",
            "Module",
            "String",
            "Array",
            "Hash",
            "Integer",
            "Float",
            "Numeric",
            "Symbol",
            "TrueClass",
            "FalseClass",
            "NilClass",
            "Exception",
            "StandardError",
            "Struct",
            "JSON",
            "URI",
            "Net",
        ]
        .into_iter()
        .map(str::to_string)
        .collect(),
        inputs: contract
            .input_objects
            .keys()
            .map(|name| (name.clone(), pascal_case(name)))
            .collect(),
    };
    for (name, fields) in &contract.input_objects {
        models.model(
            &pascal_case(name),
            &ModelType {
                nullable: false,
                kind: ModelKind::Object(fields.clone()),
            },
            true,
        )?;
    }
    for op in &contract.operations {
        ensure!(
            op.kind != GraphqlOperationKind::Subscription || subscriptions,
            "Ruby GraphQL subscriptions require a separately supported transport"
        );
        let method = method(&op.name)?;
        ensure!(
            !methods.values().any(|v| v == &method),
            "Ruby GraphQL method collision {method}"
        );
        methods.insert(op.name.clone(), method.clone());
        let class = pascal_case(&op.name);
        let variables = ModelType {
            nullable: false,
            kind: ModelKind::Object(op.variables.clone()),
        };
        models.model(&format!("{class}Variables"), &variables, true)?;
        models.model(&format!("{class}Result"), &op.result, false)?;
        let call = if incremental {
            "incremental"
        } else if op.kind == GraphqlOperationKind::Subscription {
            "subscribe"
        } else {
            "execute"
        };
        let returns = if incremental {
            "Enumerator[IncrementalFrame, untyped]".to_string()
        } else if op.kind == GraphqlOperationKind::Subscription {
            format!("Enumerator[GraphqlResponse[{class}Result], untyped]")
        } else {
            format!("GraphqlResponse[{class}Result]")
        };
        let mut operation = String::new();
        writeln!(
            operation,
            "  def self.{method}(transport, variables = {{}})\n    variables = {class}Variables.new(variables) unless variables.is_a?({class}Variables)\n    options = transport.is_a?(Transport) ? {{variables_type: {class}Variables::TYPE}} : {{}}\n    transport.{call}({}, {}, variables.to_h, {class}Result, **options)\n  end",
            ruby_string(&op.document),
            ruby_string(&op.name)
        )?;
        let mut signature = format!(
            "  def self.{method}: (Transport, ?(Hash[String | Symbol, untyped] | {class}Variables)) -> {returns}\n"
        );
        if style != GraphqlStyle::Raw {
            writeln!(
                operation,
                "  class Client\n    def {method}(variables = {{}})\n      {module}.{method}(@transport, variables)\n    end\n  end"
            )?;
            writeln!(
                signature,
                "  class Client\n    def {method}: (?(Hash[String | Symbol, untyped] | {class}Variables)) -> {returns}\n  end"
            )?;
        }
        files.insert(format!("operations/{method}"), (operation, signature));
    }
    source = format!("module {module}\n");
    source.push_str("  class Client\n    attr_reader :transport\n    def initialize(endpoint, headers: {}, timeout: 30, scalar_codecs: {}, max_frame_bytes: 1048576)\n      @transport = Transport.new(endpoint, headers: headers, timeout: timeout, scalar_codecs: scalar_codecs, max_frame_bytes: max_frame_bytes)\n    end\n");
    let mut selected = groups.clone();
    if selected.is_empty() && style == GraphqlStyle::Idiomatic {
        for op in &contract.operations {
            let group = match op.kind {
                GraphqlOperationKind::Query => "query",
                GraphqlOperationKind::Mutation => "mutation",
                GraphqlOperationKind::Subscription => "subscription",
            };
            selected
                .entry(group.into())
                .or_default()
                .insert(methods[&op.name].clone(), op.name.clone());
        }
    }
    if style == GraphqlStyle::Idiomatic {
        let mut names = BTreeSet::new();
        for (index, (group, items)) in selected.iter().enumerate() {
            let group = snake_case(group);
            ensure!(
                names.insert(group.clone())
                    && !methods.values().any(|m| m == &group)
                    && ![
                        "initialize",
                        "transport",
                        "subscribe",
                        "incremental",
                        "response",
                        "class",
                        "send",
                        "def",
                        "end",
                        "module",
                        "if",
                        "else",
                        "true",
                        "false",
                        "nil",
                        "self",
                        "new",
                        "begin",
                        "rescue",
                        "ensure",
                        "return",
                        "yield",
                        "super",
                        "while",
                        "until",
                        "case",
                        "when",
                        "for",
                        "in",
                        "break",
                        "next",
                        "redo",
                        "retry",
                        "do",
                        "alias",
                        "and",
                        "or",
                        "not",
                        "undef",
                        "hash",
                        "inspect",
                        "freeze",
                        "frozen",
                        "clone",
                        "dup",
                        "method",
                        "methods",
                        "public_send",
                        "to_h"
                    ]
                    .contains(&group.as_str())
                    && group
                        .chars()
                        .next()
                        .is_some_and(|c| c.is_ascii_lowercase() || c == '_')
                    && group.chars().all(|c| c.is_ascii_alphanumeric() || c == '_'),
                "Ruby GraphQL group collision {group}"
            );
            let mut group_source = String::new();
            writeln!(
                group_source,
                "    def {group}\n      Group{index}.new(@transport)\n    end\n    class Group{index}\n      def initialize(transport)\n        @transport = transport\n      end"
            )?;
            let mut local = BTreeSet::new();
            let mut group_signature = String::new();
            writeln!(
                group_signature,
                "    def {group}: () -> Group{index}\n    class Group{index}"
            )?;
            for (alias, operation) in items {
                let alias = method(alias)?;
                ensure!(
                    local.insert(alias.clone()),
                    "Ruby GraphQL group method collision {alias}"
                );
                let target = methods
                    .get(operation)
                    .ok_or_else(|| anyhow::anyhow!("unknown GraphQL operation {operation}"))?;
                let class = pascal_case(operation);
                let op = contract
                    .operations
                    .iter()
                    .find(|op| op.name == *operation)
                    .unwrap();
                let returns = if incremental {
                    "Enumerator[IncrementalFrame, untyped]".to_string()
                } else if op.kind == GraphqlOperationKind::Subscription {
                    format!("Enumerator[GraphqlResponse[{class}Result], untyped]")
                } else {
                    format!("GraphqlResponse[{class}Result]")
                };
                files.insert(format!("groups/{group}_{alias}"),(format!("  class Client\n    class Group{index}\n      def {alias}(variables = {{}})\n        {module}.{target}(@transport, variables)\n      end\n    end\n  end\n"),format!("  class Client\n    class Group{index}\n      def {alias}: (?(Hash[String | Symbol, untyped] | {class}Variables)) -> {returns}\n    end\n  end\n")));
            }
            group_source.push_str("    end\n");
            group_signature.push_str("    end\n");
            files.insert(
                format!("groups/{group}_base"),
                (
                    format!("  class Client\n{group_source}  end\n"),
                    format!("  class Client\n{group_signature}  end\n"),
                ),
            );
        }
    }
    source.push_str("  end\nend\n");
    let file = ruby_file_name(name);
    let mut tree = poolster_core::GeneratedTree::default();
    tree.insert(GeneratedFile::new(
        format!("lib/{file}/runtime.rb"),
        runtime,
    )?)?;
    tree.insert(GeneratedFile::new(
        format!("sig/{file}/runtime.rbs"),
        runtime_signature,
    )?)?;
    tree.insert(GeneratedFile::new(format!("lib/{file}/client.rb"), source)?)?;
    tree.insert(GeneratedFile::new(format!("sig/{file}/client.rbs"),format!("module {module}\n  class Client\n    def initialize: (String, ?headers: Hash[String,String], ?timeout: Numeric, ?scalar_codecs: Hash[String | Symbol, untyped], ?max_frame_bytes: Integer) -> void\n    def transport: () -> Transport\n  end\nend\n"))?)?;
    for (name, (source, signature)) in models.files {
        files.insert(format!("models/{}", snake_case(&name)), (source, signature));
    }
    for (path, (source, signature)) in files {
        tree.insert(GeneratedFile::new(
            format!("lib/{file}/{path}.rb"),
            format!("module {module}\n{source}end\n"),
        )?)?;
        tree.insert(GeneratedFile::new(
            format!("sig/{file}/{path}.rbs"),
            format!("module {module}\n{signature}end\n"),
        )?)?;
    }
    tree.insert(GeneratedFile::new(format!("lib/{file}.rb"),format!("# Generated by Poolster.\nrequire_relative '{file}/runtime'\nrequire_relative '{file}/client'\n%w[models operations groups].each do |dir|\n  Dir[File.join(__dir__, '{file}', dir, '*.rb')].sort.each {{ |path| require path }}\nend\n"))?)?;
    tree.insert(GeneratedFile::new(
        format!("sig/{file}.rbs"),
        "# GraphQL signatures live in the matching directory.\n",
    )?)?;
    source_layout::diagnostics(&mut tree)?;
    Ok((tree, methods))
}
