//! Native Rust provider contracts. Modules retain the maintained SDK ABI.
use crate::{Rust, render};
use anyhow::Result;
use kaji_core::{
    GeneratedFile, SdkClientStyle,
    engine::{
        Contract, FinalizeContext, Handle, Meta, Plugin, PluginContext, Provision, Requirement,
    },
};
use std::collections::BTreeMap;

pub const DEFAULT_TRANSPORT: &str = r#"// Generated by Kaji. Do not edit.
use std::{future::Future, pin::Pin};
pub type TransportFuture<'a> = Pin<Box<dyn Future<Output = Result<reqwest::Response, reqwest::Error>> + Send + 'a>>;
/// Executors may inspect or transform fully encoded requests. Cancellation
/// propagates when the returned future is dropped. Responses retain reqwest ABI.
pub trait Transport: Send + Sync { fn execute(&self, request: reqwest::Request) -> TransportFuture<'_>; }
/// A request middleware owns its request and may modify it before calling next,
/// transform the response/error afterwards, or return without calling next.
/// Runs once per transport attempt, inside the generated client's retry policy.
/// HTTP status/decode errors are classified by the client after this layer.
pub trait Middleware: Send + Sync {
    fn handle<'a>(&'a self, request: reqwest::Request, next: &'a dyn Transport) -> TransportFuture<'a>;
}
/// Composable executor: outer middleware runs first on requests and last on responses.
pub struct MiddlewareTransport<M, T> { middleware: M, inner: T }
impl<M, T> MiddlewareTransport<M, T> {
    pub fn new(middleware: M, inner: T) -> Self { Self { middleware, inner } }
}
impl<M: Middleware, T: Transport> Transport for MiddlewareTransport<M, T> {
    fn execute(&self, request: reqwest::Request) -> TransportFuture<'_> {
        self.middleware.handle(request, &self.inner)
    }
}
impl<T: Transport + ?Sized> Transport for std::sync::Arc<T> {
    fn execute(&self, request: reqwest::Request) -> TransportFuture<'_> { (**self).execute(request) }
}
#[derive(Default)]
pub struct DefaultTransport { client: reqwest::Client }
impl Transport for DefaultTransport {
    fn execute(&self, request: reqwest::Request) -> TransportFuture<'_> { Box::pin(self.client.execute(request)) }
}
"#;
#[derive(Clone)]
pub struct Models {
    pub symbols: BTreeMap<String, String>,
}
impl Contract for Models {
    const NAME: &'static str = "rust.models";
}
/// Community providers emit their module and publish its trait and constructor.
/// The trait must accept reqwest::Request and return TransportFuture.
#[derive(Clone)]
pub struct Transport {
    pub module: String,
    pub constructor: String,
}
impl Contract for Transport {
    const NAME: &'static str = "rust.transport";
}
#[derive(Clone)]
pub struct Operations {
    pub methods: BTreeMap<String, String>,
    pub prefix: Option<String>,
}
impl Contract for Operations {
    const NAME: &'static str = "rust.operations";
}
#[derive(Clone)]
pub struct Client {
    pub symbol: String,
}
impl Contract for Client {
    const NAME: &'static str = "rust.client";
}
#[derive(Default)]
pub struct Workspace {
    pub(crate) models: bool,
    pub(crate) tests: bool,
    pub(crate) operations: bool,
    pub(crate) resources: bool,
    pub(crate) transport: Option<Transport>,
}
impl Workspace {
    pub fn finalize(cx: &mut FinalizeContext<'_, Rust>) -> Result<()> {
        if !cx.workspace.models && !cx.workspace.operations {
            return Ok(());
        }
        let mut exports = String::from(
            "// Generated by Kaji. Do not edit.\npub mod models;\n#[allow(unused_imports)]\npub use models::*;\n",
        );
        if cx.workspace.operations {
            let transport = cx.workspace.transport.as_ref().unwrap();
            let module = transport
                .module
                .strip_prefix("crate::")
                .unwrap_or(&transport.module);
            anyhow::ensure!(
                !module.contains("::")
                    && !module.is_empty()
                    && module
                        .chars()
                        .all(|ch| ch.is_ascii_alphanumeric() || ch == '_'),
                "Rust transport module must be a root module identifier"
            );
            exports.push_str(&format!(
                "pub mod {module};\npub mod client;\npub use client::*;\n"
            ));
            let runtime = render::render_client_runtime(cx.api, cx.workspace.resources)
                .replace(
                    "crate::transport::Transport",
                    &format!("{}::Transport", transport.module),
                )
                .replace(
                    "crate::transport::DefaultTransport::default()",
                    &transport.constructor,
                );
            cx.files
                .emit(GeneratedFile::new("src/client/mod.rs", runtime)?)?;
        }
        if cx.workspace.tests {
            exports.push_str("#[cfg(test)] mod roundtrip_tests;\n");
        }
        cx.files.emit(GeneratedFile::new("src/lib.rs", exports)?)?;
        let name = cx
            .settings
            .package_name
            .clone()
            .unwrap_or_else(|| format!("{}-sdk", render::kebab_case(&cx.api.name)));
        cx.files.emit(GeneratedFile::new(
            "Cargo.toml",
            render::render_cargo_toml(&name, &cx.api.version),
        )?)
    }
}
#[derive(Clone, Copy)]
enum Part {
    Models,
    Transport,
    Operations,
    Client,
}
pub struct Provider {
    meta: Meta,
    part: Part,
    models: Option<Handle<Models>>,
    transport: Option<Handle<Transport>>,
    operations: Option<Handle<Operations>>,
    prefix: Option<String>,
    namespaced: bool,
}
fn provider(part: Part) -> Provider {
    Provider {
        meta: Meta::new(),
        part,
        models: None,
        transport: None,
        operations: None,
        prefix: None,
        namespaced: true,
    }
}
pub fn models() -> Provider {
    provider(Part::Models)
}
pub fn transport() -> Provider {
    provider(Part::Transport)
}
pub fn operations() -> Provider {
    provider(Part::Operations)
}
pub fn client() -> Provider {
    provider(Part::Client)
}
impl Provider {
    pub fn using_models(mut self, value: Handle<Models>) -> Self {
        self.models = Some(value);
        self
    }
    pub fn using_transport(mut self, value: Handle<Transport>) -> Self {
        self.transport = Some(value);
        self
    }
    pub fn using_operations(mut self, value: Handle<Operations>) -> Self {
        self.operations = Some(value);
        self
    }
    pub fn models_handle(&self) -> Handle<Models> {
        self.meta.handle()
    }
    pub fn transport_handle(&self) -> Handle<Transport> {
        self.meta.handle()
    }
    pub fn operations_handle(&self) -> Handle<Operations> {
        self.meta.handle()
    }
    pub fn client_handle(&self) -> Handle<Client> {
        self.meta.handle()
    }
    pub fn operation_prefix(mut self, value: impl Into<String>) -> Self {
        self.prefix = Some(value.into());
        self
    }
    pub fn flat(mut self) -> Self {
        self.namespaced = false;
        self
    }
}
impl Plugin<Rust> for Provider {
    fn kind(&self) -> &'static str {
        match self.part {
            Part::Models => "rust-models",
            Part::Transport => "rust-transport",
            Part::Operations => "rust-operations",
            Part::Client => "rust-client",
        }
    }
    fn meta(&self) -> &Meta {
        &self.meta
    }
    fn provides(&self) -> Vec<Provision> {
        vec![match self.part {
            Part::Models => Provision::of::<Models>(),
            Part::Transport => Provision::of::<Transport>(),
            Part::Operations => Provision::of::<Operations>(),
            Part::Client => Provision::of::<Client>(),
        }]
    }
    fn requires(&self) -> Vec<Requirement> {
        match self.part {
            Part::Operations => vec![
                Requirement::on(self.models),
                Requirement::on(self.transport),
            ],
            Part::Client => vec![Requirement::on(self.operations)],
            _ => vec![],
        }
    }
    fn generate(&self, cx: &mut PluginContext<'_, Rust>) -> Result<()> {
        let mut options = render::RenderOptions {
            crate_name: cx.settings.package_name.clone(),
            client_style: SdkClientStyle::Flat,
            operation_prefix: self.prefix.clone(),
        };
        match self.part {
            Part::Models => {
                for file in render::RustModels.generate(cx.api, &options)? {
                    cx.files.emit(file)?;
                }
                cx.workspace.models = true;
                cx.publish(model_contract(cx.api))?;
            }
            Part::Transport => {
                cx.files
                    .emit(GeneratedFile::new("src/transport.rs", DEFAULT_TRANSPORT)?)?;
                cx.publish(default_transport())?;
            }
            Part::Operations => {
                let _ = cx.inputs.get::<Models>()?;
                let transport = cx.inputs.get::<Transport>()?.clone();
                for file in render::render_operation_files(cx.api, &options)? {
                    cx.files.emit(file)?;
                }
                cx.workspace.operations = true;
                cx.workspace.transport = Some(transport);
                cx.publish(operation_contract(cx.api, self.prefix.clone()))?;
            }
            Part::Client => {
                options.operation_prefix = cx.inputs.get::<Operations>()?.prefix.clone();
                if self.namespaced {
                    options.client_style = SdkClientStyle::Namespaced;
                    for file in render::render_resource_files(cx.api, &options)? {
                        cx.files.emit(file)?;
                    }
                    cx.workspace.resources = true;
                }
                cx.publish(Client {
                    symbol: "crate::Client".into(),
                })?;
            }
        }
        Ok(())
    }
}
pub(crate) fn model_contract(api: &kaji_core::Api) -> Models {
    Models {
        symbols: api
            .schemas
            .iter()
            .map(|schema| {
                (
                    schema.name.clone(),
                    format!("crate::models::{}", render::type_name(&schema.name)),
                )
            })
            .collect(),
    }
}
pub(crate) fn operation_contract(api: &kaji_core::Api, prefix: Option<String>) -> Operations {
    Operations {
        methods: api
            .operations
            .iter()
            .map(|operation| {
                (
                    operation.id.clone(),
                    format!(
                        "{}{}",
                        prefix
                            .as_ref()
                            .map(|prefix| format!("{}_", render::rust_field_name(prefix)))
                            .unwrap_or_default(),
                        render::rust_field_name(&operation.id)
                    ),
                )
            })
            .collect(),
        prefix,
    }
}
pub(crate) fn default_transport() -> Transport {
    Transport {
        module: "crate::transport".into(),
        constructor: "crate::transport::DefaultTransport::default()".into(),
    }
}

/// Emits executable decode/encode checks from shared schema-derived JSON fixtures.
pub struct RoundtripTests {
    meta: Meta,
    models: Option<Handle<Models>>,
    options: kaji_core::samples::SampleOptions,
}
pub fn roundtrip_tests() -> RoundtripTests {
    RoundtripTests {
        meta: Meta::new(),
        models: None,
        options: Default::default(),
    }
}
impl RoundtripTests {
    pub fn using_models(mut self, value: Handle<Models>) -> Self {
        self.models = Some(value);
        self
    }
    pub fn options(mut self, value: kaji_core::samples::SampleOptions) -> Self {
        self.options = value;
        self
    }
}
impl Plugin<Rust> for RoundtripTests {
    fn kind(&self) -> &'static str {
        "rust-roundtrip-tests"
    }
    fn meta(&self) -> &Meta {
        &self.meta
    }
    fn requires(&self) -> Vec<Requirement> {
        vec![Requirement::on(self.models)]
    }
    fn generate(&self, cx: &mut PluginContext<'_, Rust>) -> Result<()> {
        let models = cx.inputs.get::<Models>()?;
        let mut source = String::from("// Generated by Kaji. Do not edit.\n");
        let mut diagnostics = BTreeMap::new();
        for (index, schema) in cx.api.schemas.iter().enumerate() {
            let symbol = models
                .symbols
                .get(&schema.name)
                .ok_or_else(|| anyhow::anyhow!("missing model symbol {}", schema.name))?;
            let report = kaji_core::samples::schema_samples(cx.api, &schema.value, self.options);
            diagnostics.insert(schema.name.clone(), report.diagnostics);
            for (sample_index, sample) in report.samples.iter().enumerate() {
                let json = serde_json::to_string(&sample.value)?;
                source.push_str(&format!("#[test]\nfn schema_{index}_sample_{sample_index}() {{\n let input: serde_json::Value = serde_json::from_str({json:?}).unwrap();\n let model: {symbol} = serde_json::from_value(input.clone()).unwrap();\n let output = serde_json::to_value(model).unwrap();\n assert_eq!(input, output, {:?});\n}}\n",format!("{} {}",schema.name,sample.name)));
            }
        }
        // Unit test module uses the published crate:: model symbols directly.
        source.insert_str(0, "#[cfg(test)]\nmod kaji_generated_roundtrips {\n");
        source.push_str("}\n");
        cx.files
            .emit(GeneratedFile::new("src/roundtrip_tests.rs", source)?)?;
        cx.workspace.tests = true;
        cx.files.emit(GeneratedFile::new(
            ".kaji/roundtrip-diagnostics.json",
            serde_json::to_string_pretty(&diagnostics)? + "\n",
        )?)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use kaji_core::{
        Api, HttpMethod, Operation, OperationResponse, Schema, SchemaKind, SchemaValue,
        engine::Packages,
    };
    struct CustomTransport {
        meta: Meta,
    }
    impl Plugin<Rust> for CustomTransport {
        fn kind(&self) -> &'static str {
            "custom-rust-http"
        }
        fn meta(&self) -> &Meta {
            &self.meta
        }
        fn provides(&self) -> Vec<Provision> {
            vec![Provision::of::<Transport>()]
        }
        fn generate(&self, cx: &mut PluginContext<'_, Rust>) -> Result<()> {
            cx.files.emit(GeneratedFile::new("src/custom_http.rs",r#"use std::{future::Future,pin::Pin};
pub type TransportFuture<'a>=Pin<Box<dyn Future<Output=Result<reqwest::Response,reqwest::Error>>+Send+'a>>;
pub trait Transport:Send+Sync {fn execute(&self,request:reqwest::Request)->TransportFuture<'_>;}
#[derive(Default)] pub struct CustomHTTP;
impl Transport for CustomHTTP {fn execute(&self,request:reqwest::Request)->TransportFuture<'_>{Box::pin(async move {assert_eq!(request.url().path(),"/label");panic!("custom transport invoked")})}}
"#)?)?;
            cx.publish(Transport {
                module: "crate::custom_http".into(),
                constructor: "crate::custom_http::CustomHTTP".into(),
            })
        }
    }
    #[test]
    fn provider_contracts_generate_replaceable_transport_and_tests() {
        let mut integer = SchemaValue::new(SchemaKind::Integer);
        integer.format = Some("int64".into());
        let api = Api {
            name: "demo".into(),
            version: "1.0.0".into(),
            schemas: vec![
                Schema::new(
                    "Details",
                    SchemaValue::new(SchemaKind::Object {
                        fields: vec![kaji_core::Field {
                            name: "note".into(),
                            value: {
                                let mut value = SchemaValue::new(SchemaKind::String);
                                value.nullable = true;
                                value
                            },
                            required: false,
                            annotations: Default::default(),
                        }],
                        additional_properties: kaji_core::AdditionalProperties::Any,
                    }),
                ),
                Schema::new("Counter", integer),
                Schema::new("Label", SchemaValue::new(SchemaKind::String)),
            ],
            operations: vec![Operation {
                id: "getLabel".into(),
                method: HttpMethod::Get,
                path: "/label".into(),
                responses: vec![OperationResponse::json(
                    "200",
                    SchemaValue::new(SchemaKind::String),
                )],
                ..Default::default()
            }],
            ..Default::default()
        };
        let model = models();
        let mh = model.models_handle();
        let transport = CustomTransport { meta: Meta::new() };
        let th = transport.meta.handle::<Transport>();
        let operation = operations().using_models(mh).using_transport(th);
        let oh = operation.operations_handle();
        let tree = Packages::new()
            .package(
                crate::package("sdk")
                    .with(client().using_operations(oh))
                    .with(operation)
                    .with(transport)
                    .with(model)
                    .with(roundtrip_tests().using_models(mh)),
            )
            .generate(&api, None)
            .unwrap();
        assert!(
            tree.get("sdk/src/client/mod.rs")
                .unwrap()
                .contains("Arc<dyn crate::custom_http::Transport>")
        );
        let root = tempfile::tempdir().unwrap();
        tree.write_to(root.path()).unwrap();
        std::fs::create_dir(root.path().join("sdk/tests")).unwrap();
        std::fs::write(root.path().join("sdk/tests/custom.rs"),r#"#[test]
#[should_panic(expected="custom transport invoked")]
fn custom_executor_runs(){use std::future::Future;let client=demo_sdk::Client::new("https://unused.example");let mut future=Box::pin(client.get_label());let _=future.as_mut().poll(&mut std::task::Context::from_waker(std::task::Waker::noop()));}
"#).unwrap();
        let output = std::process::Command::new("cargo")
            .args(["test", "--offline", "--quiet"])
            .env("RUSTFLAGS", "-Dwarnings")
            .current_dir(root.path().join("sdk"))
            .env(
                "CARGO_TARGET_DIR",
                std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                    .join("../../../target/generated-rust-providers"),
            )
            .output()
            .unwrap();
        assert!(
            output.status.success(),
            "{}{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
    }
    #[test]
    fn generated_middleware_composes_and_short_circuits() {
        let api = Api {
            name: "middleware".into(),
            version: "1.0.0".into(),
            operations: vec![Operation {
                id: "getLabel".into(),
                method: HttpMethod::Get,
                path: "/label".into(),
                responses: vec![OperationResponse::json(
                    "200",
                    SchemaValue::new(SchemaKind::String),
                )],
                ..Default::default()
            }],
            ..Default::default()
        };
        let tree = Packages::new()
            .package(crate::package("sdk").with(crate::sdk()).middleware(kaji_core::customization::BundledMiddleware {
                path: "src/author_policy.rs".into(), symbol: "author_policy".into(), async_symbol: None,
                contents: r#"use crate::transport::{Middleware, Transport, TransportFuture};
pub fn author_policy() -> impl Middleware { Policy }
struct Policy;
impl Middleware for Policy {
    fn handle<'a>(&'a self, _: reqwest::Request, _: &'a dyn Transport) -> TransportFuture<'a> {
        Box::pin(async { Ok(http::Response::builder().status(200).header("content-type", "application/json").body(reqwest::Body::from("\"cached\"")).unwrap().into()) })
    }
}"#.into(),
            }))
            .generate(&api, None)
            .unwrap();
        let root = tempfile::tempdir().unwrap();
        tree.write_to(root.path()).unwrap();
        let sdk = root.path().join("sdk");
        let manifest = sdk.join("Cargo.toml");
        let mut cargo = std::fs::read_to_string(&manifest).unwrap();
        cargo.push_str("\n[dependencies.http]\nversion = \"1\"\n");
        std::fs::write(manifest, cargo).unwrap();
        std::fs::create_dir(sdk.join("tests")).unwrap();
        std::fs::write(sdk.join("tests/middleware.rs"), r#"
use middleware_sdk::transport::{Middleware, MiddlewareTransport, Transport, TransportFuture};
use std::{future::Future, sync::{Arc, Mutex, atomic::{AtomicUsize, Ordering}}, task::{Context, Poll, Waker}};
fn ready<F: Future>(future: F) -> F::Output {
    let mut future = Box::pin(future);
    match future.as_mut().poll(&mut Context::from_waker(Waker::noop())) {
        Poll::Ready(value) => value, Poll::Pending => panic!("test transport must be immediately ready"),
    }
}
fn response() -> reqwest::Response {
    http::Response::builder().status(200).header("content-type", "application/json")
        .body(reqwest::Body::from("\"cached\"")).unwrap().into()
}
struct Terminal { calls: Arc<AtomicUsize>, fail: bool }
impl Transport for Terminal {
    fn execute(&self, request: reqwest::Request) -> TransportFuture<'_> {
        self.calls.fetch_add(1, Ordering::SeqCst);
        assert_eq!(request.headers()["x-outer"], "yes");
        assert_eq!(request.headers()["x-inner"], "yes");
        Box::pin(async move {
            if self.fail { Err(reqwest::Client::new().get("invalid url").build().unwrap_err()) }
            else { Ok(response()) }
        })
    }
}
struct Layer { name: &'static str, events: Arc<Mutex<Vec<String>>>, recover: bool }
impl Middleware for Layer {
    fn handle<'a>(&'a self, mut request: reqwest::Request, next: &'a dyn Transport) -> TransportFuture<'a> {
        Box::pin(async move {
            self.events.lock().unwrap().push(format!("{}:request", self.name));
            request.headers_mut().insert(format!("x-{}", self.name).parse::<reqwest::header::HeaderName>().unwrap(), "yes".parse().unwrap());
            let result = next.execute(request).await;
            self.events.lock().unwrap().push(format!("{}:{}", self.name, if result.is_ok() {"response"} else {"error"}));
            let mut response = match result { Ok(r) => r, Err(_) if self.recover => response(), Err(e) => return Err(e) };
            response.headers_mut().insert("x-middleware", self.name.parse().unwrap());
            Ok(response)
        })
    }
}
struct Cache;
impl Middleware for Cache {
    fn handle<'a>(&'a self, _: reqwest::Request, _: &'a dyn Transport) -> TransportFuture<'a> {
        Box::pin(async { Ok(response()) })
    }
}
fn chain(fail: bool, recover: bool) -> (impl Transport, Arc<AtomicUsize>, Arc<Mutex<Vec<String>>>) {
    let calls = Arc::new(AtomicUsize::new(0)); let events = Arc::new(Mutex::new(vec![]));
    let inner = MiddlewareTransport::new(Layer {name:"inner",events:events.clone(),recover}, Terminal {calls:calls.clone(),fail});
    let transport = MiddlewareTransport::new(Layer {name:"outer",events:events.clone(),recover:false}, inner);
    (transport, calls, events)
}
#[test]
fn request_response_order_and_mutation() {
    let (transport, calls, events) = chain(false, false);
    let response = ready(transport.execute(reqwest::Request::new(reqwest::Method::GET, "https://unused.example/label".parse().unwrap()))).unwrap();
    assert_eq!(response.headers()["x-middleware"], "outer"); assert_eq!(calls.load(Ordering::SeqCst), 1);
    assert_eq!(*events.lock().unwrap(), ["outer:request", "inner:request", "inner:response", "outer:response"]);
}
#[test]
fn errors_propagate_or_recover() {
    let (transport, _, events) = chain(true, false);
    assert!(ready(transport.execute(reqwest::Request::new(reqwest::Method::GET, "https://unused.example".parse().unwrap()))).is_err());
    assert_eq!(*events.lock().unwrap(), ["outer:request", "inner:request", "inner:error", "outer:error"]);
    let (transport, _, events) = chain(true, true);
    assert!(ready(transport.execute(reqwest::Request::new(reqwest::Method::GET, "https://unused.example".parse().unwrap()))).is_ok());
    assert_eq!(*events.lock().unwrap(), ["outer:request", "inner:request", "inner:error", "outer:response"]);
}
#[test]
fn author_policy_is_enabled_without_consumer_registration() {
    let client = middleware_sdk::Client::new("https://unused.example");
    assert_eq!(ready(client.get_label()).unwrap(), "cached");
}
#[test]
fn short_circuit_is_used_by_generated_operation() {
    let calls = Arc::new(AtomicUsize::new(0));
    let terminal = Terminal {calls:calls.clone(),fail:false};
    let transport: Arc<dyn Transport> = Arc::new(MiddlewareTransport::new(Cache, terminal));
    let client = middleware_sdk::Client::new("https://unused.example").with_transport(transport);
    assert_eq!(ready(client.get_label()).unwrap(), "cached"); assert_eq!(calls.load(Ordering::SeqCst), 0);
}
"#).unwrap();
        let output = std::process::Command::new("cargo")
            .args(["test", "--offline", "--quiet"])
            .env("RUSTFLAGS", "-Dwarnings")
            .current_dir(sdk)
            .env(
                "CARGO_TARGET_DIR",
                std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                    .join("../../../target/generated-rust-providers"),
            )
            .output()
            .unwrap();
        assert!(
            output.status.success(),
            "{}{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
    }
}
