//! Native schema roundtrip test provider.
use super::*;

/// Emits executable decode/encode checks from shared schema-derived JSON fixtures.
pub struct RoundtripTests {
    pub(super) http_input: poolster_core::engine::HttpInput,
    meta: Meta,
    models: Option<Handle<Models>>,
    options: poolster_core::samples::SampleOptions,
}
pub fn roundtrip_tests() -> RoundtripTests {
    RoundtripTests {
        http_input: Default::default(),
        meta: Meta::new(),
        models: None,
        options: Default::default(),
    }
}
impl RoundtripTests {
    pub fn using_models(mut self, value: Handle<Models>) -> Self {
        self.models = Some(value);
        self
    }
    pub fn options(mut self, value: poolster_core::samples::SampleOptions) -> Self {
        self.options = value;
        self
    }
}
impl Plugin<Rust> for RoundtripTests {
    fn supports_native_input(&self) -> bool {
        self.http_input.is_explicit()
    }
    fn kind(&self) -> &'static str {
        "rust-roundtrip-tests"
    }
    fn meta(&self) -> &Meta {
        &self.meta
    }
    fn requires(&self) -> Vec<Requirement> {
        let mut requirements = self.http_input.requirements();
        requirements.extend(vec![Requirement::on(self.models)]);
        requirements
    }
    fn generate(&self, cx: &mut PluginContext<'_, Rust>) -> Result<()> {
        self.http_input.with_context(cx, |cx| {
        let models = cx.inputs.get::<Models>()?;
        let mut source = String::from("// Generated by Poolster. Do not edit.\n");
        let mut diagnostics = BTreeMap::new();
        for (index, schema) in cx.api.schemas.iter().enumerate() {
            let symbol = models
                .symbols
                .get(&schema.name)
                .ok_or_else(|| anyhow::anyhow!("missing model symbol {}", schema.name))?;
            let report =
                poolster_core::samples::schema_samples(cx.api, &schema.value, self.options);
            diagnostics.insert(schema.name.clone(), report.diagnostics);
            for (sample_index, sample) in report.samples.iter().enumerate() {
                let json = serde_json::to_string(&sample.value)?;
                source.push_str(&format!("#[test]\nfn schema_{index}_sample_{sample_index}() {{\n let input: serde_json::Value = serde_json::from_str({json:?}).unwrap();\n let model: {symbol} = serde_json::from_value(input.clone()).unwrap();\n let output = serde_json::to_value(model).unwrap();\n assert_eq!(input, output, {:?});\n}}\n",format!("{} {}",schema.name,sample.name)));
            }
        }
        // Unit test module uses the published crate:: model symbols directly.
        source.insert_str(0, "#[cfg(test)]\nmod poolster_generated_roundtrips {\n");
        source.push_str("}\n");
        cx.files
            .emit(GeneratedFile::new("src/roundtrip_tests.rs", source)?)?;
        cx.workspace.tests = true;
        cx.files.emit(GeneratedFile::new(
            ".poolster/roundtrip-diagnostics.json",
            serde_json::to_string_pretty(&diagnostics)? + "\n",
        )?)
     })
    }
}
