//! HTTP package rendering.
use super::*;

pub(crate) fn render_readme(api: &Api, crate_name: &str, config: &RenderOptions) -> String {
    let crate_import = crate_name.replace('-', "_");
    let call = api
        .operations
        .iter()
        .find(|operation| {
            operation.id.starts_with("list")
                && operation.request_body.is_none()
                && !operation.path.contains('{')
                && operation.parameters.iter().all(|parameter| !parameter.required)
        })
        .or_else(|| {
            api.operations
                .iter()
                .find(|operation| {
                    operation.request_body.is_none()
                        && !operation.path.contains('{')
                        && operation.parameters.iter().all(|parameter| !parameter.required)
                })
        })
        .map(|operation| {
            let resource = resource_name(operation);
            let accessor = resource_accessor_name(
                &resource,
                &api.operations
                    .iter()
                    .map(|operation| direct_method_name(operation, config))
                    .collect::<Vec<_>>(),
            );
            let method = resource_method_name(&rust_field_name(&operation.id), &resource);
            let input = if operation_has_parameters(operation) {
                format!("{}::default()", operation_request_name(operation))
            } else {
                String::new()
            };
            let method_path = if resource_client_enabled(config) {
                format!("{accessor}().{method}")
            } else {
                direct_method_name(operation, config)
            };
            format!("let response = client.{method_path}({input}).await?;\nprintln!(\"{{response:?}}\");")
        })
        .unwrap_or_else(|| "// Call a generated operation from your async context.".into());
    let surface = if resource_client_enabled(config) {
        "resource-first"
    } else {
        "direct-method"
    };
    let mut output = format!(
        "# {} Rust SDK\n\nGenerated by Poolster with the **{surface}** client surface.\n\n```sh\ncargo add {crate_name}\n```\n\nUse it from an async context:\n\n```rust\nuse {crate_import}::*;\n\nlet client = Client::new(\"https://api.example.com\");\n{call}\n```\n\nSee [STYLE_GUIDE.md](STYLE_GUIDE.md) for the public surface.\n",
        api.name
    );
    if api
        .operations
        .iter()
        .any(|operation| rust_pagination(operation).is_some())
    {
        output.push_str("\n## Pagination\n\nDeclared helpers return lazy `<operation>_pages(input)` streams of full response pages. They call the original operation and preserve its transport/authentication. Optional page/offset starts default to 1/0; explicit starts remain unchanged. Empty/short results or declared final pages terminate iteration. Counter overflow stops continuation, and a 10,000-page guard reports a pagination error. Supported declarations are scalar parameter cursors, page numbers and legacy offset/limit; body controls and URL continuation remain unsupported. Inspect `.poolster/pagination-diagnostics.json` when a declared helper is absent.\n");
    }
    output.push_str(&r#"
## Customer middleware

```rust
use std::sync::Arc;
use MODULE::{Client, transport::{DefaultTransport, Middleware, MiddlewareTransport, Transport, TransportFuture}};
struct CustomerHeader;
impl Middleware for CustomerHeader {
    fn handle<'a>(&'a self, mut request: reqwest::Request, next: &'a dyn Transport) -> TransportFuture<'a> {
        Box::pin(async move {
            request.headers_mut().insert("x-customer", "example".parse().unwrap());
            let mut response = next.execute(request).await?;
            response.headers_mut().insert("x-observed", "yes".parse().unwrap());
            Ok(response)
        })
    }
}
let transport = MiddlewareTransport::new(CustomerHeader, DefaultTransport::default());
let client = Client::new("https://api.example.com").with_transport(Arc::new(transport));
```

Nest wrappers: outer layers see requests first and responses last. A layer may recover a transport error or return a synthetic response without calling `next`. Middleware runs once per transport attempt inside SDK retries; avoid independently replaying unsafe requests. HTTP status/decode errors are classified afterwards. The request/response/error ABI remains reqwest; custom generator transport modules must provide their own middleware types. Observational `ClientHooks` run separately. SSE responses pass through this boundary when opened, not per decoded event.
"#.replace("MODULE", &crate_import));
    output
}

pub(crate) fn render_cargo_toml_for_api(crate_name: &str, api: &Api) -> String {
    let mut manifest = render_cargo_toml(crate_name, &api.version);
    if api.operations.iter().any(|operation| {
        poolster_core::idempotency::resolved(operation).is_some_and(|policy| policy.auto_generate)
    }) {
        manifest.push_str("uuid = { version = \"1\", features = [\"v4\"] }\n");
    }
    manifest
}

pub(crate) fn render_cargo_toml(crate_name: &str, version: &str) -> String {
    let version = cargo_package_version(version);
    format!(
        "[package]\nname = {:?}\nversion = {:?}\nedition = \"2024\"\ndescription = \"Generated API client\"\n\n[dependencies]\nfutures-util = \"0.3\"\nhttpdate = \"1\"\nreqwest = {{ version = \"0.12\", features = [\"json\"] }}\nserde = {{ version = \"1\", features = [\"derive\"] }}\nserde_json = \"1\"\ntokio = {{ version = \"1\", features = [\"time\", \"sync\"] }}\n",
        crate_name, version
    )
}

/// OpenAPI's `info.version` is free-form; Cargo package versions are SemVer.
/// Preserve date-based release versions where possible and use a stable safe
/// fallback for opaque API release labels.
pub(crate) fn cargo_package_version(version: &str) -> String {
    let parts = version.split('-').collect::<Vec<_>>();
    if parts.len() == 3 && parts.iter().all(|part| part.parse::<u64>().is_ok()) {
        return parts
            .iter()
            .map(|part| match part.trim_start_matches('0') {
                "" => "0",
                normalized => normalized,
            })
            .collect::<Vec<_>>()
            .join(".");
    }
    let parts = version.split('.').collect::<Vec<_>>();
    if parts.len() == 3 && parts.iter().all(|part| part.parse::<u64>().is_ok()) {
        return version.into();
    }
    "0.1.0".into()
}
