//! Native GraphQL clients preserve fixed operation selections and wire presence.
use crate::{Ruby, pascal_case, ruby_file_name, ruby_string, snake_case};
use anyhow::{Result, ensure};
use poolster_core::{
    GeneratedFile,
    engine::{Contract, Handle, Meta, Plugin, PluginContext, Provision, Requirement},
    native::{
        GraphqlIncrementalOperations, GraphqlOperationKind, GraphqlOperations, ModelKind, ModelType,
    },
};
use std::{
    collections::{BTreeMap, BTreeSet},
    fmt::Write,
};
#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub enum GraphqlStyle {
    Raw,
    Flat,
    #[default]
    Idiomatic,
}
pub struct GraphqlClient {
    pub methods: BTreeMap<String, String>,
}
impl Contract for GraphqlClient {
    const NAME: &'static str = "poolster.ruby.graphql-client.v1";
}
pub struct Graphql {
    meta: Meta,
    input: Option<Handle<GraphqlOperations>>,
    incremental_input: Option<Handle<GraphqlIncrementalOperations>>,
    subscriptions: bool,
    incremental: bool,
    style: GraphqlStyle,
    groups: BTreeMap<String, BTreeMap<String, String>>,
}
pub fn graphql(input: Option<Handle<GraphqlOperations>>) -> Graphql {
    Graphql {
        meta: Meta::new(),
        input,
        incremental_input: None,
        subscriptions: false,
        incremental: false,
        style: GraphqlStyle::default(),
        groups: BTreeMap::new(),
    }
}
pub fn graphql_incremental(input: Option<Handle<GraphqlIncrementalOperations>>) -> Graphql {
    let mut plugin = graphql(None);
    plugin.incremental_input = input;
    plugin.incremental = true;
    plugin
}
impl Graphql {
    pub fn subscriptions(mut self) -> Self {
        self.subscriptions = true;
        self
    }
    pub fn incremental_input(mut self, input: Handle<GraphqlIncrementalOperations>) -> Self {
        self.incremental_input = Some(input);
        self.incremental = true;
        self
    }
    pub fn raw(mut self) -> Self {
        self.style = GraphqlStyle::Raw;
        self
    }
    pub fn flat(mut self) -> Self {
        self.style = GraphqlStyle::Flat;
        self
    }
    pub fn idiomatic(mut self) -> Self {
        self.style = GraphqlStyle::Idiomatic;
        self
    }
    pub fn namespaced(self) -> Self {
        self.idiomatic()
    }
    pub fn groups(mut self, groups: BTreeMap<String, BTreeMap<String, String>>) -> Self {
        self.groups = groups;
        self
    }
    pub fn group(
        mut self,
        group: impl Into<String>,
        method: impl Into<String>,
        operation: impl Into<String>,
    ) -> Self {
        self.groups
            .entry(group.into())
            .or_default()
            .insert(method.into(), operation.into());
        self
    }
    pub fn handle(&self) -> Handle<GraphqlClient> {
        self.meta.handle()
    }
}
impl Plugin<Ruby> for Graphql {
    fn kind(&self) -> &'static str {
        "ruby-graphql"
    }
    fn meta(&self) -> &Meta {
        &self.meta
    }
    fn supports_native_input(&self) -> bool {
        true
    }
    fn requires(&self) -> Vec<Requirement> {
        if self.incremental {
            vec![Requirement::on(self.incremental_input)]
        } else {
            vec![Requirement::on(self.input)]
        }
    }
    fn provides(&self) -> Vec<Provision> {
        vec![Provision::of::<GraphqlClient>()]
    }
    fn generate(&self, cx: &mut PluginContext<'_, Ruby>) -> Result<()> {
        let name = cx
            .settings
            .package_name
            .as_deref()
            .unwrap_or("graphql_client");
        let version = cx.common.package_version.as_deref().unwrap_or("0.0.0");
        let contract = if self.incremental {
            &cx.inputs.get::<GraphqlIncrementalOperations>()?.definition
        } else {
            cx.inputs.get::<GraphqlOperations>()?
        };
        let (tree, methods) = render_advanced(
            contract,
            name,
            self.style,
            &self.groups,
            self.subscriptions,
            self.incremental,
        )?;
        let file = ruby_file_name(name);
        cx.files.append(tree)?;
        cx.files.emit(GeneratedFile::new(format!("{file}.gemspec"),format!("Gem::Specification.new do |s|\n s.name={}\n s.version={}\n s.summary='Selection-specific GraphQL client generated by Poolster'\n s.authors=['Poolster']\n s.required_ruby_version='>= 3.1'\n s.files=Dir['lib/**/*.rb','sig/**/*.rbs']\n s.require_paths=['lib']\nend\n",ruby_string(name),ruby_string(version)))?)?;
        cx.files.emit(GeneratedFile::new("README.md", "# GraphQL Ruby client\n\nFixed operation clients with raw, flat or grouped APIs. GraphqlResponse preserves partial data and errors. Models retain optional presence separately from null; RBS signatures describe selected types. Net::HTTP transport supports headers/timeouts. Opt-in distinct-connection graphql-sse subscriptions, multipart deferSpec=20220824 incremental frames and scalar_codecs callbacks are available. Intermediate frames retain raw incomplete data and final typed envelopes. No reconnect, multiplexing or alternate incremental dialect. Custom scalar host types remain untyped.\n")?)?;
        cx.publish(GraphqlClient { methods })
    }
}
fn method(value: &str) -> Result<String> {
    let name = snake_case(value);
    ensure!(
        !name.is_empty()
            && name
                .chars()
                .next()
                .is_some_and(|c| c.is_ascii_lowercase() || c == '_')
            && name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_'),
        "invalid Ruby GraphQL method {value}"
    );
    ensure!(
        ![
            "class",
            "def",
            "end",
            "module",
            "initialize",
            "transport",
            "subscribe",
            "incremental",
            "response",
            "query",
            "mutation",
            "send",
            "object_id",
            "respond_to",
            "to_h",
            "hash",
            "inspect",
            "freeze",
            "frozen",
            "clone",
            "dup",
            "method",
            "methods",
            "public_send",
            "tap",
            "then",
            "display",
            "nil",
            "true",
            "false",
            "new",
            "begin",
            "rescue",
            "ensure",
            "return",
            "raise",
            "yield",
            "super",
            "self",
            "while",
            "until",
            "if",
            "unless",
            "case",
            "when",
            "else",
            "elsif",
            "for",
            "in",
            "break",
            "next",
            "redo",
            "retry",
            "do",
            "alias",
            "and",
            "or",
            "not",
            "undef",
            "defined"
        ]
        .contains(&name.as_str()),
        "reserved Ruby GraphQL method {name}"
    );
    Ok(name)
}
mod models;
use models::Models;
#[cfg(test)]
fn render(
    contract: &GraphqlOperations,
    name: &str,
    style: GraphqlStyle,
    groups: &BTreeMap<String, BTreeMap<String, String>>,
) -> Result<(poolster_core::GeneratedTree, BTreeMap<String, String>)> {
    render_advanced(contract, name, style, groups, false, false)
}
fn render_advanced(
    contract: &GraphqlOperations,
    name: &str,
    style: GraphqlStyle,
    groups: &BTreeMap<String, BTreeMap<String, String>>,
    subscriptions: bool,
    incremental: bool,
) -> Result<(poolster_core::GeneratedTree, BTreeMap<String, String>)> {
    ensure!(
        !contract.operations.is_empty(),
        "Ruby GraphQL requires operation documents"
    );
    ensure!(
        !name.is_empty()
            && name
                .chars()
                .all(|c| c.is_ascii_alphanumeric() || "_-".contains(c)),
        "invalid Ruby GraphQL gem name"
    );
    ensure!(
        style == GraphqlStyle::Idiomatic || groups.is_empty(),
        "custom GraphQL groups require idiomatic style"
    );
    let module = pascal_case(name);
    ensure!(
        module
            .chars()
            .next()
            .is_some_and(|c| c.is_ascii_uppercase()),
        "invalid Ruby GraphQL module name"
    );
    ensure!(
        ![
            "Object",
            "Kernel",
            "Class",
            "Module",
            "String",
            "Array",
            "Hash",
            "Integer",
            "Float",
            "Numeric",
            "TrueClass",
            "FalseClass",
            "NilClass",
            "Exception",
            "StandardError",
            "Struct"
        ]
        .contains(&module.as_str()),
        "reserved Ruby GraphQL module name {module}"
    );
    let mut source = format!(
        "# Generated by Poolster. DO NOT EDIT.\nrequire 'json'\nrequire 'net/http'\nrequire 'uri'\nmodule {module}\n"
    );
    source.push_str(include_str!("graphql/runtime.rb.tmpl"));
    source.push_str(include_str!("graphql/streaming.rb.tmpl"));
    let runtime = format!("{source}end\n");
    let mut files = BTreeMap::<String, (String, String)>::new();
    let mut signatures = format!(
        "module {module}\n  class Model\n    def present?: (String | Symbol) -> bool\n    def to_h: () -> Hash[String, untyped]\n  end\n"
    );
    signatures.push_str("  class Transport\n    def initialize: (String, ?headers: Hash[String, String], ?timeout: Numeric, ?scalar_codecs: Hash[String | Symbol, untyped], ?max_frame_bytes: Integer) -> void\n  end\n  class GraphqlResponse[T]\n    def data: () -> T?\n    def errors: () -> Array[Hash[String, untyped]]\n    def extensions: () -> untyped\n    def data_present: () -> bool\n    def status: () -> Symbol\n    def require_data: () -> T\n  end\n");
    signatures.push_str("  class IncrementalFrame\n    def frame: () -> Hash[String, untyped]\n    def data: () -> untyped\n    def final: () -> GraphqlResponse[untyped]?\n  end\n");
    let runtime_signature = format!("{signatures}end\n");
    let mut methods = BTreeMap::new();
    let mut models = Models {
        files: BTreeMap::new(),
        names: [
            "Client",
            "Model",
            "Transport",
            "GraphqlResponse",
            "IncrementalFrame",
            "StreamParser",
            "GraphqlErrors",
            "HttpError",
            "Object",
            "Kernel",
            "Class",
            "Module",
            "String",
            "Array",
            "Hash",
            "Integer",
            "Float",
            "Numeric",
            "Symbol",
            "TrueClass",
            "FalseClass",
            "NilClass",
            "Exception",
            "StandardError",
            "Struct",
            "JSON",
            "URI",
            "Net",
        ]
        .into_iter()
        .map(str::to_string)
        .collect(),
        inputs: contract
            .input_objects
            .keys()
            .map(|name| (name.clone(), pascal_case(name)))
            .collect(),
    };
    for (name, fields) in &contract.input_objects {
        models.model(
            &pascal_case(name),
            &ModelType {
                nullable: false,
                kind: ModelKind::Object(fields.clone()),
            },
            true,
        )?;
    }
    for op in &contract.operations {
        ensure!(
            op.kind != GraphqlOperationKind::Subscription || subscriptions,
            "Ruby GraphQL subscriptions require a separately supported transport"
        );
        let method = method(&op.name)?;
        ensure!(
            !methods.values().any(|v| v == &method),
            "Ruby GraphQL method collision {method}"
        );
        methods.insert(op.name.clone(), method.clone());
        let class = pascal_case(&op.name);
        let variables = ModelType {
            nullable: false,
            kind: ModelKind::Object(op.variables.clone()),
        };
        models.model(&format!("{class}Variables"), &variables, true)?;
        models.model(&format!("{class}Result"), &op.result, false)?;
        let call = if incremental {
            "incremental"
        } else if op.kind == GraphqlOperationKind::Subscription {
            "subscribe"
        } else {
            "execute"
        };
        let returns = if incremental {
            "Enumerator[IncrementalFrame, untyped]".to_string()
        } else if op.kind == GraphqlOperationKind::Subscription {
            format!("Enumerator[GraphqlResponse[{class}Result], untyped]")
        } else {
            format!("GraphqlResponse[{class}Result]")
        };
        let mut operation = String::new();
        writeln!(
            operation,
            "  def self.{method}(transport, variables = {{}})\n    variables = {class}Variables.new(variables) unless variables.is_a?({class}Variables)\n    options = transport.is_a?(Transport) ? {{variables_type: {class}Variables::TYPE}} : {{}}\n    transport.{call}({}, {}, variables.to_h, {class}Result, **options)\n  end",
            ruby_string(&op.document),
            ruby_string(&op.name)
        )?;
        let mut signature = format!(
            "  def self.{method}: (Transport, ?(Hash[String | Symbol, untyped] | {class}Variables)) -> {returns}\n"
        );
        if style != GraphqlStyle::Raw {
            writeln!(
                operation,
                "  class Client\n    def {method}(variables = {{}}); {module}.{method}(@transport, variables); end\n  end"
            )?;
            writeln!(
                signature,
                "  class Client\n    def {method}: (?(Hash[String | Symbol, untyped] | {class}Variables)) -> {returns}\n  end"
            )?;
        }
        files.insert(format!("operations/{method}"), (operation, signature));
    }
    source = format!("module {module}\n");
    source.push_str("  class Client\n    attr_reader :transport\n    def initialize(endpoint, headers: {}, timeout: 30, scalar_codecs: {}, max_frame_bytes: 1048576)\n      @transport = Transport.new(endpoint, headers: headers, timeout: timeout, scalar_codecs: scalar_codecs, max_frame_bytes: max_frame_bytes)\n    end\n");
    let mut selected = groups.clone();
    if selected.is_empty() && style == GraphqlStyle::Idiomatic {
        for op in &contract.operations {
            let group = match op.kind {
                GraphqlOperationKind::Query => "query",
                GraphqlOperationKind::Mutation => "mutation",
                GraphqlOperationKind::Subscription => "subscription",
            };
            selected
                .entry(group.into())
                .or_default()
                .insert(methods[&op.name].clone(), op.name.clone());
        }
    }
    if style == GraphqlStyle::Idiomatic {
        let mut names = BTreeSet::new();
        for (index, (group, items)) in selected.iter().enumerate() {
            let group = snake_case(group);
            ensure!(
                names.insert(group.clone())
                    && !methods.values().any(|m| m == &group)
                    && ![
                        "initialize",
                        "transport",
                        "subscribe",
                        "incremental",
                        "response",
                        "class",
                        "send",
                        "def",
                        "end",
                        "module",
                        "if",
                        "else",
                        "true",
                        "false",
                        "nil",
                        "self",
                        "new",
                        "begin",
                        "rescue",
                        "ensure",
                        "return",
                        "yield",
                        "super",
                        "while",
                        "until",
                        "case",
                        "when",
                        "for",
                        "in",
                        "break",
                        "next",
                        "redo",
                        "retry",
                        "do",
                        "alias",
                        "and",
                        "or",
                        "not",
                        "undef",
                        "hash",
                        "inspect",
                        "freeze",
                        "frozen",
                        "clone",
                        "dup",
                        "method",
                        "methods",
                        "public_send",
                        "to_h"
                    ]
                    .contains(&group.as_str())
                    && group
                        .chars()
                        .next()
                        .is_some_and(|c| c.is_ascii_lowercase() || c == '_')
                    && group.chars().all(|c| c.is_ascii_alphanumeric() || c == '_'),
                "Ruby GraphQL group collision {group}"
            );
            let mut group_source = String::new();
            writeln!(
                group_source,
                "    def {group}; Group{index}.new(@transport); end\n    class Group{index}\n      def initialize(transport); @transport = transport; end"
            )?;
            let mut local = BTreeSet::new();
            let mut group_signature = String::new();
            writeln!(
                group_signature,
                "    def {group}: () -> Group{index}\n    class Group{index}"
            )?;
            for (alias, operation) in items {
                let alias = method(alias)?;
                ensure!(
                    local.insert(alias.clone()),
                    "Ruby GraphQL group method collision {alias}"
                );
                let target = methods
                    .get(operation)
                    .ok_or_else(|| anyhow::anyhow!("unknown GraphQL operation {operation}"))?;
                let class = pascal_case(operation);
                let op = contract
                    .operations
                    .iter()
                    .find(|op| op.name == *operation)
                    .unwrap();
                let returns = if incremental {
                    "Enumerator[IncrementalFrame, untyped]".to_string()
                } else if op.kind == GraphqlOperationKind::Subscription {
                    format!("Enumerator[GraphqlResponse[{class}Result], untyped]")
                } else {
                    format!("GraphqlResponse[{class}Result]")
                };
                files.insert(format!("groups/{group}_{alias}"),(format!("  class Client\n    class Group{index}\n      def {alias}(variables = {{}}); {module}.{target}(@transport, variables); end\n    end\n  end\n"),format!("  class Client\n    class Group{index}\n      def {alias}: (?(Hash[String | Symbol, untyped] | {class}Variables)) -> {returns}\n    end\n  end\n")));
            }
            group_source.push_str("    end\n");
            group_signature.push_str("    end\n");
            files.insert(
                format!("groups/{group}_base"),
                (
                    format!("  class Client\n{group_source}  end\n"),
                    format!("  class Client\n{group_signature}  end\n"),
                ),
            );
        }
    }
    source.push_str("  end\nend\n");
    let file = ruby_file_name(name);
    let mut tree = poolster_core::GeneratedTree::default();
    tree.insert(GeneratedFile::new(
        format!("lib/{file}/runtime.rb"),
        runtime,
    )?)?;
    tree.insert(GeneratedFile::new(
        format!("sig/{file}/runtime.rbs"),
        runtime_signature,
    )?)?;
    tree.insert(GeneratedFile::new(format!("lib/{file}/client.rb"), source)?)?;
    tree.insert(GeneratedFile::new(format!("sig/{file}/client.rbs"),format!("module {module}\n  class Client\n    def initialize: (String, ?headers: Hash[String,String], ?timeout: Numeric, ?scalar_codecs: Hash[String | Symbol, untyped], ?max_frame_bytes: Integer) -> void\n    def transport: () -> Transport\n  end\nend\n"))?)?;
    for (name, (source, signature)) in models.files {
        files.insert(format!("models/{}", snake_case(&name)), (source, signature));
    }
    for (path, (source, signature)) in files {
        tree.insert(GeneratedFile::new(
            format!("lib/{file}/{path}.rb"),
            format!("module {module}\n{source}end\n"),
        )?)?;
        tree.insert(GeneratedFile::new(
            format!("sig/{file}/{path}.rbs"),
            format!("module {module}\n{signature}end\n"),
        )?)?;
    }
    tree.insert(GeneratedFile::new(format!("lib/{file}.rb"),format!("# Generated by Poolster.\nrequire_relative '{file}/runtime'\nrequire_relative '{file}/client'\n%w[models operations groups].each do |dir|\n  Dir[File.join(__dir__, '{file}', dir, '*.rb')].sort.each {{ |path| require path }}\nend\n"))?)?;
    tree.insert(GeneratedFile::new(
        format!("sig/{file}.rbs"),
        "# GraphQL signatures live in the matching directory.\n",
    )?)?;
    source_layout::diagnostics(&mut tree)?;
    Ok((tree, methods))
}
#[cfg(test)]
mod tests;

mod source_layout;
