//! Native Ruby 3.1+ SDK output for Kaji.
//!
//! Generated packages use only Ruby's standard `net/http`, `uri`, and `json`
//! libraries. The public client accepts normal Ruby keyword arguments and has
//! both direct operations and optional resource namespaces.

use std::collections::BTreeMap;
use std::fmt::Write;

use anyhow::{Result, bail};
use kaji_core::{
    AdditionalProperties, Api, GeneratedFile, GeneratedTree, Operation, Schema, SchemaKind,
    SchemaValue, SdkClientStyle,
};

const NOTICE: &str = "# Generated by Kaji. Do not edit.\n";

fn render_sdk(
    api: &Api,
    output_dir: &str,
    package_name: Option<&str>,
    client_style: SdkClientStyle,
) -> Result<GeneratedTree> {
    let root = output_dir.trim_matches('/');
    if root.is_empty() {
        bail!("Ruby SDK output directory cannot be empty");
    }
    let gem = package_name
        .filter(|name| !name.trim().is_empty())
        .map(str::to_owned)
        .unwrap_or_else(|| format!("{}-sdk", kebab_case(&api.name)));
    let module = pascal_case(&gem);
    let file_module = ruby_file_name(&gem);
    let mut tree = GeneratedTree::default();
    insert(
        &mut tree,
        root,
        &format!("{gem}.gemspec"),
        gemspec(api, &gem),
    )?;
    insert(
        &mut tree,
        root,
        "Gemfile",
        "source \"https://rubygems.org\"\n\ngemspec\n".into(),
    )?;
    insert(
        &mut tree,
        root,
        "README.md",
        readme(api, &gem, &module, client_style),
    )?;
    insert(
        &mut tree,
        root,
        "STYLE_GUIDE.md",
        style_guide(api, &module, client_style),
    )?;
    insert(
        &mut tree,
        root,
        &format!("lib/{file_module}.rb"),
        format!(
            "{NOTICE}require_relative \"{file_module}/models\"\nrequire_relative \"{file_module}/client\"\n\nmodule {module}\nend\n"
        ),
    )?;
    insert(
        &mut tree,
        root,
        &format!("lib/{file_module}/models.rb"),
        render_models(api, &module),
    )?;
    insert(
        &mut tree,
        root,
        &format!("lib/{file_module}/client.rb"),
        render_client(api, &module, client_style),
    )?;
    Ok(tree)
}

fn insert(tree: &mut GeneratedTree, root: &str, path: &str, contents: String) -> Result<()> {
    tree.insert(GeneratedFile::new(format!("{root}/{path}"), contents)?)
}

fn gemspec(api: &Api, gem: &str) -> String {
    format!(
        "Gem::Specification.new do |spec|\n  spec.name = {}\n  spec.version = {}\n  spec.summary = {}\n  spec.required_ruby_version = \">= 3.1\"\n  spec.files = Dir[\"lib/**/*.rb\"]\n  spec.require_paths = [\"lib\"]\nend\n",
        ruby_string(gem),
        ruby_string(&ruby_version(&api.version)),
        ruby_string(&format!("Generated Ruby SDK for {}", api.name))
    )
}

fn readme(api: &Api, gem: &str, module: &str, style: SdkClientStyle) -> String {
    let usage = match style {
        SdkClientStyle::Flat => "client.get_contact(contact_id: \"contact_123\")",
        SdkClientStyle::Namespaced => "client.contacts.get(contact_id: \"contact_123\")",
    };
    format!(
        "# {} Ruby SDK\n\nGenerated by Kaji for Ruby 3.1+. It only uses the Ruby standard library.\n\n```sh\ngem install {gem}\n```\n\n```ruby\nrequire {}\n\nclient = {module}::Client.new(base_url: \"https://api.example.com\", api_key: ENV.fetch(\"API_KEY\", nil))\n{usage}\n```\n\nSee [STYLE_GUIDE.md](STYLE_GUIDE.md) for the selected client surface.\n",
        api.name,
        ruby_string(&ruby_file_name(gem)),
    )
}

fn style_guide(api: &Api, module: &str, style: SdkClientStyle) -> String {
    let surface = match style {
        SdkClientStyle::Flat => "Operations are direct methods such as `client.get_contact(...)`.",
        SdkClientStyle::Namespaced => {
            "Operations remain direct methods and are also grouped by resource, such as `client.contacts.get(...)`."
        }
    };
    format!(
        "# {} Ruby SDK style guide\n\nNamespace: `{module}`.\n\n{surface}\n",
        api.name
    )
}

fn render_models(api: &Api, module: &str) -> String {
    let mut out = format!("{NOTICE}require \"json\"\n\nmodule {module}\n  module Models\n");
    for schema in &api.schemas {
        out.push_str(&render_model(schema));
    }
    out.push_str("  end\nend\n");
    out
}

fn render_model(schema: &Schema) -> String {
    let name = pascal_case(&schema.name);
    let mut out = String::new();
    match &schema.value.kind {
        SchemaKind::Object {
            fields,
            additional_properties,
        } => {
            out = format!("    class {name}\n");
            if fields.is_empty() {
                out.push_str("      attr_reader :additional_properties\n");
            } else {
                let attrs = fields
                    .iter()
                    .map(|field| format!(":{}", ruby_identifier(&field.name)))
                    .collect::<Vec<_>>()
                    .join(", ");
                let _ = writeln!(out, "      attr_reader {attrs}");
                if !matches!(additional_properties, AdditionalProperties::Forbidden) {
                    out.push_str("      attr_reader :additional_properties\n");
                }
            }
            let args = fields
                .iter()
                .map(|field| format!("{}: nil", ruby_identifier(&field.name)))
                .collect::<Vec<_>>()
                .join(", ");
            let extra = if matches!(additional_properties, AdditionalProperties::Forbidden) {
                ""
            } else if args.is_empty() {
                "additional_properties: {}"
            } else {
                ", additional_properties: {}"
            };
            let _ = writeln!(out, "      def initialize({args}{extra})");
            for field in fields {
                let id = ruby_identifier(&field.name);
                let _ = writeln!(out, "        @{id} = {id}");
            }
            if !matches!(additional_properties, AdditionalProperties::Forbidden) {
                out.push_str("        @additional_properties = additional_properties || {}\n");
            }
            out.push_str("      end\n\n      def self.from_hash(value)\n        return value unless value.is_a?(Hash)\n");
            let values = fields
                .iter()
                .map(|field| {
                    format!(
                        "{}: value[{}]",
                        ruby_identifier(&field.name),
                        ruby_string(&field.name)
                    )
                })
                .collect::<Vec<_>>()
                .join(", ");
            if matches!(additional_properties, AdditionalProperties::Forbidden) {
                let _ = writeln!(out, "        new({values})");
            } else {
                let known = fields
                    .iter()
                    .map(|field| ruby_string(&field.name))
                    .collect::<Vec<_>>()
                    .join(", ");
                let values = if values.is_empty() {
                    String::new()
                } else {
                    format!("{values}, ")
                };
                let _ = writeln!(
                    out,
                    "        new({values}additional_properties: value.reject {{ |key, _| [{}].include?(key) }})",
                    known
                );
            }
            out.push_str("      end\n\n      def to_h\n        value = {}\n");
            for field in fields {
                let id = ruby_identifier(&field.name);
                let _ = writeln!(
                    out,
                    "        value[{}] = {id} unless {id}.nil?",
                    ruby_string(&field.name)
                );
            }
            if !matches!(additional_properties, AdditionalProperties::Forbidden) {
                out.push_str("        value.merge!(additional_properties)\n");
            }
            out.push_str("        value\n      end\n    end\n\n");
        }
        _ => {
            let ruby_type = ruby_type(&schema.value);
            let _ = writeln!(out, "    {name} = {ruby_type}\n");
        }
    }
    out
}

fn render_client(api: &Api, module: &str, style: SdkClientStyle) -> String {
    let mut out = format!(
        "{NOTICE}require \"net/http\"\nrequire \"uri\"\nrequire \"json\"\nrequire \"cgi\"\n\nmodule {module}\n"
    );
    out.push_str("  class ApiError < StandardError\n    attr_reader :status, :body\n    def initialize(status, body)\n      @status = status\n      @body = body\n      super(\"API request failed with status #{status}\")\n    end\n  end\n\n  class Client\n    def initialize(base_url:, api_key: nil, bearer_token: nil, headers: {}, timeout: 30)\n      @base_url = base_url.sub(%r{/$}, \"\")\n      @api_key = api_key\n      @bearer_token = bearer_token\n      @headers = headers.transform_keys(&:to_s)\n      @timeout = timeout\n");
    if style == SdkClientStyle::Namespaced {
        for resource in resource_operations(api).keys() {
            let _ = writeln!(
                out,
                "      @{} = {}Resource.new(self)",
                ruby_identifier(resource),
                pascal_case(resource)
            );
        }
    }
    out.push_str("    end\n\n");
    if style == SdkClientStyle::Namespaced {
        for resource in resource_operations(api).keys() {
            let _ = writeln!(out, "    attr_reader :{}", ruby_identifier(resource));
        }
        out.push('\n');
    }
    for operation in &api.operations {
        out.push_str(&render_operation(api, operation));
    }
    out.push_str(&render_runtime());
    out.push_str("  end\n\n");
    if style == SdkClientStyle::Namespaced {
        for (resource, operations) in resource_operations(api) {
            out.push_str(&render_resource(&resource, &operations));
        }
    }
    out.push_str("end\n");
    out
}

fn render_operation(api: &Api, operation: &Operation) -> String {
    let name = ruby_identifier(&snake_case(&operation.id));
    let mut args = Vec::new();
    for parameter in &operation.parameters {
        let name = ruby_identifier(&parameter.name);
        args.push(if parameter.required {
            format!("{name}:")
        } else {
            format!("{name}: nil")
        });
    }
    if let Some(body) = &operation.request_body {
        args.push(if body.required {
            "body:".into()
        } else {
            "body: nil".into()
        });
    }
    let signature = args.join(", ");
    let mut out = format!(
        "    def {name}({signature})\n      path = {}\n",
        ruby_string(&operation.path)
    );
    for parameter in operation
        .parameters
        .iter()
        .filter(|parameter| parameter.location == "path")
    {
        let id = ruby_identifier(&parameter.name);
        let _ = writeln!(
            out,
            "      path = path.gsub({}, CGI.escape({id}.to_s))",
            ruby_string(&format!("{{{}}}", parameter.name))
        );
    }
    out.push_str("      query = {}\n");
    for parameter in operation
        .parameters
        .iter()
        .filter(|parameter| parameter.location == "query")
    {
        let id = ruby_identifier(&parameter.name);
        let _ = writeln!(
            out,
            "      query[{}] = {id} unless {id}.nil?",
            ruby_string(&parameter.name)
        );
    }
    out.push_str("      headers = {}\n");
    for parameter in operation
        .parameters
        .iter()
        .filter(|parameter| parameter.location == "header")
    {
        let id = ruby_identifier(&parameter.name);
        let _ = writeln!(
            out,
            "      headers[{}] = {id}.to_s unless {id}.nil?",
            ruby_string(&parameter.name)
        );
    }
    let response = response_model(api, operation);
    let body = if operation.request_body.is_some() {
        "body"
    } else {
        "nil"
    };
    let _ = writeln!(
        out,
        "      result = request({}, path, query: query, headers: headers, body: {body})",
        ruby_string(operation.method.as_str())
    );
    match response.as_deref() {
        Some(model) => {
            let _ = writeln!(
                out,
                "      result.is_a?(Hash) ? Models::{model}.from_hash(result) : result\n    end\n\n"
            );
        }
        None => out.push_str("      result\n    end\n\n"),
    }
    out
}

fn render_runtime() -> String {
    "    private\n\n    def request(method, path, query:, headers:, body:)\n      uri = URI.join(@base_url + \"/\", path.sub(%r{^/}, \"\"))\n      uri.query = URI.encode_www_form(query) unless query.empty?\n      request = Net::HTTP.const_get(method.capitalize).new(uri)\n      merged_headers = @headers.merge(headers)\n      merged_headers[\"Authorization\"] ||= \"Bearer #{@bearer_token}\" if @bearer_token\n      merged_headers[\"X-API-Key\"] ||= @api_key if @api_key\n      merged_headers.each { |key, value| request[key] = value }\n      unless body.nil?\n        request[\"Content-Type\"] ||= \"application/json\"\n        request.body = body.is_a?(String) ? body : JSON.generate(body.respond_to?(:to_h) ? body.to_h : body)\n      end\n      response = Net::HTTP.start(uri.hostname, uri.port, use_ssl: uri.scheme == \"https\", open_timeout: @timeout, read_timeout: @timeout) { |http| http.request(request) }\n      parsed = response.body.nil? || response.body.empty? ? nil : JSON.parse(response.body) rescue response.body\n      raise ApiError.new(response.code.to_i, parsed) unless response.code.to_i.between?(200, 299)\n      parsed\n    end\n".into()
}

fn render_resource(resource: &str, operations: &[&Operation]) -> String {
    let class = format!("{}Resource", pascal_case(resource));
    let mut out =
        format!("  class {class}\n    def initialize(client)\n      @client = client\n    end\n\n");
    for operation in operations {
        let name = ruby_identifier(&snake_case(&operation.id));
        let args = operation
            .parameters
            .iter()
            .map(|parameter| {
                let name = ruby_identifier(&parameter.name);
                if parameter.required {
                    format!("{name}:")
                } else {
                    format!("{name}: nil")
                }
            })
            .chain(operation.request_body.as_ref().map(|body| {
                if body.required {
                    "body:".to_owned()
                } else {
                    "body: nil".to_owned()
                }
            }))
            .collect::<Vec<_>>()
            .join(", ");
        let forwards = operation
            .parameters
            .iter()
            .map(|parameter| {
                let id = ruby_identifier(&parameter.name);
                format!("{id}: {id}")
            })
            .chain(
                operation
                    .request_body
                    .as_ref()
                    .map(|_| "body: body".to_owned()),
            )
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(
            out,
            "    def {name}({args})\n      @client.{name}({forwards})\n    end\n"
        );
    }
    out.push_str("  end\n\n");
    out
}

fn resource_operations(api: &Api) -> BTreeMap<String, Vec<&Operation>> {
    let mut groups = BTreeMap::new();
    for operation in &api.operations {
        let resource = operation
            .path
            .trim_matches('/')
            .split('/')
            .next()
            .filter(|part| !part.is_empty())
            .unwrap_or("default");
        groups
            .entry(snake_case(resource))
            .or_insert_with(Vec::new)
            .push(operation);
    }
    groups
}

fn response_model(api: &Api, operation: &Operation) -> Option<String> {
    let reference = operation.success_schema()?.kind.reference_name()?;
    api.schemas
        .iter()
        .find(|schema| schema.name == reference)
        .and_then(|schema| {
            matches!(schema.value.kind, SchemaKind::Object { .. }).then(|| pascal_case(reference))
        })
}

fn ruby_type(value: &SchemaValue) -> String {
    match &value.kind {
        SchemaKind::Any | SchemaKind::Not { .. } => "Object".into(),
        SchemaKind::Null => "NilClass".into(),
        SchemaKind::Boolean => "TrueClass | FalseClass".into(),
        SchemaKind::Integer => "Integer".into(),
        SchemaKind::Number => "Numeric".into(),
        SchemaKind::String => "String".into(),
        SchemaKind::Array { items } => format!("Array # {}", ruby_type(items)),
        SchemaKind::Object { .. } => "Hash".into(),
        SchemaKind::Reference { reference } => {
            pascal_case(reference.rsplit('/').next().unwrap_or(reference))
        }
        SchemaKind::OneOf { variants } | SchemaKind::AnyOf { variants } => variants
            .iter()
            .map(ruby_type)
            .collect::<Vec<_>>()
            .join(" | "),
        SchemaKind::AllOf { .. } => "Hash".into(),
    }
}

fn ruby_version(version: &str) -> String {
    let parts = version.split('.').collect::<Vec<_>>();
    if parts.len() == 3 && parts.iter().all(|part| part.parse::<u32>().is_ok()) {
        version.into()
    } else {
        "0.1.0".into()
    }
}

fn ruby_string(value: &str) -> String {
    serde_json::to_string(value).expect("strings serialize")
}

fn ruby_file_name(value: &str) -> String {
    snake_case(value)
}

fn ruby_identifier(value: &str) -> String {
    let value = snake_case(value);
    let value = if value.is_empty() {
        "value".into()
    } else {
        value
    };
    match value.as_str() {
        "class" | "module" | "def" | "end" | "private" | "public" | "alias" | "begin"
        | "ensure" | "return" | "self" | "nil" | "true" | "false" => format!("{value}_"),
        _ => value,
    }
}

fn snake_case(value: &str) -> String {
    let mut output = String::new();
    let mut previous_is_lower = false;
    for character in value.chars() {
        if character.is_ascii_alphanumeric() {
            if character.is_ascii_uppercase() && previous_is_lower {
                output.push('_');
            }
            output.push(character.to_ascii_lowercase());
            previous_is_lower = character.is_ascii_lowercase() || character.is_ascii_digit();
        } else if !output.ends_with('_') && !output.is_empty() {
            output.push('_');
            previous_is_lower = false;
        }
    }
    output.trim_matches('_').into()
}

fn kebab_case(value: &str) -> String {
    snake_case(value).replace('_', "-")
}

fn pascal_case(value: &str) -> String {
    let mut output = String::new();
    let mut capitalize = true;
    for character in value.chars() {
        if character.is_ascii_alphanumeric() {
            if capitalize {
                output.push(character.to_ascii_uppercase());
                capitalize = false;
            } else {
                output.push(character);
            }
        } else {
            capitalize = true;
        }
    }
    if output.is_empty() {
        "GeneratedSdk".into()
    } else if output
        .chars()
        .next()
        .is_some_and(|character| character.is_ascii_digit())
    {
        format!("Sdk{output}")
    } else {
        output
    }
}

mod package;
pub use package::{PackageExt, Ruby, Sdk, Settings, package, sdk};

#[cfg(test)]
mod tests {
    use super::*;
    use kaji_core::{Field, HttpMethod, OperationParameter, OperationResponse};
    use std::process::Command;

    #[test]
    fn emits_a_syntax_checked_namespaced_gem() {
        let api = Api {
            name: "Example API".into(),
            version: "1.2.3".into(),
            schemas: vec![Schema::new(
                "Contact",
                SchemaValue::new(SchemaKind::Object {
                    fields: vec![Field {
                        name: "id".into(),
                        value: SchemaValue::new(SchemaKind::String),
                        required: true,
                        annotations: Default::default(),
                    }],
                    additional_properties: AdditionalProperties::Any,
                }),
            )],
            operations: vec![Operation {
                id: "getContact".into(),
                method: HttpMethod::Get,
                path: "/contacts/{contactId}".into(),
                parameters: vec![OperationParameter {
                    name: "contactId".into(),
                    location: "path".into(),
                    required: true,
                    schema: Some(SchemaValue::new(SchemaKind::String)),
                    description: None,
                    annotations: Default::default(),
                }],
                responses: vec![OperationResponse::json(
                    "200",
                    SchemaValue::reference("#/components/schemas/Contact"),
                )],
                ..Operation::default()
            }],
            ..Api::default()
        };
        let tree = render_sdk(
            &api,
            "sdk",
            Some("example-api-sdk"),
            SdkClientStyle::Namespaced,
        )
        .unwrap();
        assert!(
            tree.get("sdk/lib/example_api_sdk/client.rb")
                .unwrap()
                .contains("class ContactsResource")
        );
        assert!(
            tree.get("sdk/lib/example_api_sdk/client.rb")
                .unwrap()
                .contains("def get_contact(contact_id:)")
        );
        let root = tempfile::tempdir().unwrap();
        tree.write_to(root.path()).unwrap();
        if Command::new("ruby").arg("--version").status().is_ok() {
            for path in [
                "sdk/lib/example_api_sdk.rb",
                "sdk/lib/example_api_sdk/client.rb",
                "sdk/lib/example_api_sdk/models.rb",
            ] {
                let status = Command::new("ruby")
                    .args(["-c", path])
                    .current_dir(root.path())
                    .status()
                    .unwrap();
                assert!(status.success(), "generated {path} must be valid Ruby");
            }
        }
    }
}
