//! Typed package composition for the Ruby SDK renderer.

use anyhow::Result;
use kaji_core::SdkClientStyle;
use kaji_core::engine::{
    Contract, Handle, Language, Meta, Package, Plugin, PluginContext, Provision, Requirement,
};

pub struct Ruby;

#[derive(Default)]
pub struct Settings {
    pub package_name: Option<String>,
}

impl Language for Ruby {
    const NAME: &'static str = "ruby";
    type Settings = Settings;
    type Workspace = ();
    fn bundle_middleware(
        tree: &mut kaji_core::GeneratedTree,
        middleware: &[kaji_core::customization::BundledMiddleware],
    ) -> Result<()> {
        crate::bundled_middleware::bundle(tree, middleware)
    }
}

pub fn package(dir: impl Into<String>) -> Package<Ruby> {
    Package::new(dir)
}

pub trait PackageExt {
    fn name(self, name: impl Into<String>) -> Self;
}

impl PackageExt for Package<Ruby> {
    fn name(mut self, name: impl Into<String>) -> Self {
        self.settings_mut().package_name = Some(name.into());
        self
    }
}

pub struct Sdk {
    meta: Meta,
    client_style: Option<SdkClientStyle>,
}

pub fn sdk() -> Sdk {
    Sdk {
        meta: Meta::new(),
        client_style: None,
    }
}

impl Sdk {
    pub fn models(&self) -> Handle<RubyModels> {
        self.meta.handle()
    }
    pub fn flat(mut self) -> Self {
        self.client_style = Some(SdkClientStyle::Flat);
        self
    }

    pub fn namespaced(mut self) -> Self {
        self.client_style = Some(SdkClientStyle::Namespaced);
        self
    }
}

impl Plugin<Ruby> for Sdk {
    fn kind(&self) -> &'static str {
        "ruby-sdk"
    }

    fn meta(&self) -> &Meta {
        &self.meta
    }

    fn provides(&self) -> Vec<Provision> {
        vec![Provision::of::<RubyModels>()]
    }
    fn generate(&self, cx: &mut PluginContext<'_, Ruby>) -> Result<()> {
        cx.files.append(crate::render_sdk(
            cx.api,
            ".",
            cx.settings.package_name.as_deref(),
            self.client_style
                .or(cx.common.client_style)
                .unwrap_or(SdkClientStyle::Namespaced),
        )?)?;
        let gem = cx
            .settings
            .package_name
            .clone()
            .unwrap_or_else(|| format!("{}-sdk", crate::kebab_case(&cx.api.name)));
        cx.publish(RubyModels {
            module: crate::pascal_case(&gem),
            import: crate::ruby_file_name(&gem),
            object_models: cx
                .api
                .schemas
                .iter()
                .filter(|schema| matches!(schema.value.kind, kaji_core::SchemaKind::Object { .. }))
                .map(|schema| (schema.name.clone(), crate::pascal_case(&schema.name)))
                .collect(),
        })
    }
}

#[derive(Clone, Debug)]
pub struct RubyModels {
    pub module: String,
    pub import: String,
    pub object_models: std::collections::BTreeMap<String, String>,
}
impl Contract for RubyModels {
    const NAME: &'static str = "ruby-models";
}
pub struct Roundtrips {
    meta: Meta,
    provider: Option<Handle<RubyModels>>,
    options: kaji_core::samples::SampleOptions,
}
pub fn roundtrips() -> Roundtrips {
    Roundtrips {
        meta: Meta::new(),
        provider: None,
        options: Default::default(),
    }
}
impl Roundtrips {
    pub fn models_from(mut self, sdk: &Sdk) -> Self {
        self.provider = Some(sdk.models());
        self
    }
    pub fn sample_options(mut self, options: kaji_core::samples::SampleOptions) -> Self {
        self.options = options;
        self
    }
}
impl Plugin<Ruby> for Roundtrips {
    fn kind(&self) -> &'static str {
        "ruby-roundtrips"
    }
    fn meta(&self) -> &Meta {
        &self.meta
    }
    fn requires(&self) -> Vec<Requirement> {
        vec![Requirement::on(self.provider)]
    }
    fn generate(&self, cx: &mut PluginContext<'_, Ruby>) -> Result<()> {
        let models = cx.inputs.get::<RubyModels>()?;
        let mut cases = Vec::new();
        let mut diagnostics = Vec::new();
        for schema in &cx.api.schemas {
            if let Some(symbol) = models.object_models.get(&schema.name) {
                let report =
                    kaji_core::samples::schema_samples(cx.api, &schema.value, self.options);
                for sample in report.samples {
                    cases.push(
                        serde_json::json!({"model":symbol,"name":sample.name,"wire":sample.value}),
                    );
                }
                for diagnostic in report.diagnostics {
                    diagnostics.push(format!("{}: {}", schema.name, diagnostic));
                }
            }
        }
        cx.files.emit(kaji_core::GeneratedFile::new(
            "test/roundtrip-fixtures.json",
            serde_json::to_string_pretty(
                &serde_json::json!({"cases":cases,"diagnostics":diagnostics}),
            )?,
        )?)?;
        let script = format!(
            "# Generated by Kaji. Do not edit.\nrequire 'json'\nrequire '{}'\nfixtures = JSON.parse(File.read(File.join(__dir__, 'roundtrip-fixtures.json')))\nfixtures.fetch('cases').each do |sample|\n  klass = {}::Models.const_get(sample.fetch('model'))\n  result = klass.from_hash(sample.fetch('wire')).to_h\n  raise \"Wire roundtrip failed: #{{sample.fetch('model')}} #{{sample.fetch('name')}}\" unless result == sample.fetch('wire')\nend\n",
            models.import, models.module
        );
        cx.files.emit(kaji_core::GeneratedFile::new(
            "test/model_roundtrips.rb",
            script,
        )?)
    }
}
