//! GraphQL framework helpers retain the response envelope instead of assuming success.
use super::*;
use poolster_core::native::GraphqlOperationKind;
use std::fmt::Write;
pub(super) fn generate(plugin: &Query, cx: &mut PluginContext<'_, TypeScript>) -> Result<()> {
    anyhow::ensure!(
        !plugin.http_input.is_explicit() && plugin.provider.is_none(),
        "GraphQL query helpers cannot combine HTTP and GraphQL providers"
    );
    anyhow::ensure!(
        plugin.kinds.is_empty(),
        "GraphQL operation kinds come from the selected client and cannot be overridden"
    );
    if let Some(count) = plugin.operations_per_file {
        anyhow::ensure!(count > 0, "max_operations_per_file must be positive");
        anyhow::ensure!(
            count == 50,
            "GraphQL query helpers currently support single-file output; partition size options are unsupported"
        );
    }
    anyhow::ensure!(
        plugin.layout.is_none() || plugin.layout == Some(poolster_core::SourceLayout::SingleFile),
        "GraphQL query helpers currently support single-file layout"
    );
    let client = cx.inputs.get::<crate::GraphqlClient>()?;
    for name in plugin.include.iter().flatten().chain(plugin.names.keys()) {
        anyhow::ensure!(
            client.operations.contains_key(name),
            "GraphQL query helper refers to unknown operation {name:?}"
        );
    }
    let target = GeneratedFile::new(format!("{}.ts", plugin.output), "")?.path;
    let runtime = crate::Symbol {
        module: client.runtime_module.clone(),
        name: String::new(),
    }
    .import_from(&target)?;
    let (dependency, version) = match plugin.framework {
        QueryFramework::React => ("@tanstack/react-query", "5.104.1"),
        QueryFramework::Vue => ("@tanstack/vue-query", "5.104.1"),
        QueryFramework::Swr => ("swr", "2.5.1"),
    };
    let mut source = format!(
        "// Generated by Poolster. GraphQL errors and partial results stay in GraphqlResult.\nimport type {{ GraphqlTransport, GraphqlResult, RequestOptions }} from {runtime:?};\n"
    );
    match plugin.framework {
        QueryFramework::React | QueryFramework::Vue => writeln!(
            source,
            "import {{ useQuery, useMutation, queryOptions, type QueryClient }} from {dependency:?};"
        )?,
        QueryFramework::Swr => writeln!(
            source,
            "import useSWR from 'swr';\nimport useSWRMutation from 'swr/mutation';"
        )?,
    }
    if matches!(plugin.framework, QueryFramework::Vue) {
        writeln!(
            source,
            "import type {{ UseMutationReturnType, UseQueryReturnType }} from '@tanstack/vue-query';\nimport {{ computed, toValue, type MaybeRefOrGetter }} from 'vue';"
        )?;
    }
    source.push_str("const registryKey = Symbol.for('poolster.graphql.transport-cache.v1');\nconst registryHost = globalThis as unknown as Record<symbol, { ids: WeakMap<object, number>; next: number } | undefined>;\nconst registry = registryHost[registryKey] ??= { ids: new WeakMap<object, number>(), next: 0 };\nfunction graphqlKey(transport: GraphqlTransport, scope: string, operation: string, variables?: object) {\n  if (!scope) throw new Error('GraphQL cacheScope must identify the endpoint and authentication scope');\n  let id = registry.ids.get(transport); if (id === undefined) { id = ++registry.next; registry.ids.set(transport,id); }\n  return ['poolster.graphql', scope, id, operation, variables] as const;\n}\n");
    let mut names = std::collections::BTreeSet::new();
    let mut exports = vec![];
    for (operation, symbols) in &client.operations {
        if plugin
            .include
            .as_ref()
            .is_some_and(|selected| !selected.contains(operation))
        {
            continue;
        }
        anyhow::ensure!(
            symbols.kind != GraphqlOperationKind::Subscription,
            "GraphQL query helpers do not support subscriptions; exclude operation {operation}"
        );
        let naming = plugin.names.get(operation).unwrap_or(operation);
        let function = crate::symbols::camel(naming);
        let hook = format!("use{}", crate::symbols::identifier(naming));
        let options = format!(
            "{function}{}Options",
            if symbols.kind == GraphqlOperationKind::Query {
                "Query"
            } else {
                "Mutation"
            }
        );
        for name in [&hook, &options] {
            anyhow::ensure!(
                names.insert(name.clone()),
                "GraphQL query helper symbol collision: {name}"
            );
        }
        let callable = format!("{function}Operation");
        let vars = format!("{function}Variables");
        let result = format!("{function}Result");
        writeln!(
            source,
            "import {{ {} as {callable}, type {} as {vars}, type {} as {result} }} from {:?};",
            symbols.raw_function.name,
            symbols.variables.name,
            symbols.result.name,
            symbols.raw_function.import_from(&target)?
        )?;
        let mutation_return = if matches!(plugin.framework, QueryFramework::Vue) {
            format!(": UseMutationReturnType<GraphqlResult<{result}>, Error, {vars}, unknown>")
        } else {
            String::new()
        };
        let query_hook = if matches!(plugin.framework, QueryFramework::Vue) {
            format!(
                "export function {hook}(transport: GraphqlTransport, cacheScope: MaybeRefOrGetter<string>, variables: MaybeRefOrGetter<{vars}>, request: Omit<RequestOptions,'signal'> = {{}}, queryClient?: QueryClient): UseQueryReturnType<GraphqlResult<{result}>, Error> {{ return useQuery(computed(() => {options}(transport,toValue(cacheScope),toValue(variables),request)), queryClient); }}"
            )
        } else {
            format!(
                "export function {hook}(transport: GraphqlTransport, cacheScope: string, variables: {vars}, request: Omit<RequestOptions,'signal'> = {{}}, queryClient?: QueryClient) {{ return useQuery({options}(transport,cacheScope,variables,request), queryClient); }}"
            )
        };
        let query_argument = if matches!(plugin.framework, QueryFramework::Vue) {
            format!("queryKey[4] as {vars}")
        } else {
            "variables".into()
        };
        let query_context = if matches!(plugin.framework, QueryFramework::Vue) {
            "signal, queryKey"
        } else {
            "signal"
        };
        let key = serde_json::to_string(operation)?;
        match (symbols.kind, &plugin.framework) {
            (GraphqlOperationKind::Query, QueryFramework::React | QueryFramework::Vue) => {
                writeln!(
                    source,
                    "export function {options}(transport: GraphqlTransport, cacheScope: string, variables: {vars}, request: Omit<RequestOptions, 'signal'> = {{}}) {{\n return queryOptions({{ queryKey: graphqlKey(transport,cacheScope,{key},variables), queryFn: ({{{query_context}}}): Promise<GraphqlResult<{result}>> => {callable}(transport,{query_argument},{{...request,signal}}) }});\n}}\n{query_hook}"
                )?;
            }
            (GraphqlOperationKind::Mutation, QueryFramework::React | QueryFramework::Vue) => {
                writeln!(
                    source,
                    "export function {options}(transport: GraphqlTransport, cacheScope: string, request: RequestOptions = {{}}) {{\n return {{ mutationKey: graphqlKey(transport,cacheScope,{key}), retry: false as const, mutationFn: (variables: {vars}): Promise<GraphqlResult<{result}>> => {callable}(transport,variables,request) }};\n}}\nexport function {hook}(transport: GraphqlTransport, cacheScope: string, request: RequestOptions = {{}}, queryClient?: QueryClient){mutation_return} {{ return useMutation({options}(transport,cacheScope,request), queryClient); }}"
                )?;
            }
            (GraphqlOperationKind::Query, QueryFramework::Swr) => {
                writeln!(
                    source,
                    "export function {options}(transport: GraphqlTransport, cacheScope: string, variables: {vars}, request: RequestOptions = {{}}) {{\n return {{ key: graphqlKey(transport,cacheScope,{key},variables), fetcher: () => {callable}(transport,variables,request) }};\n}}\nexport function {hook}(transport: GraphqlTransport, cacheScope: string, variables: {vars}, request: RequestOptions = {{}}) {{ const options={options}(transport,cacheScope,variables,request); return useSWR<GraphqlResult<{result}>,Error>(options.key,options.fetcher); }}"
                )?;
            }
            (GraphqlOperationKind::Mutation, QueryFramework::Swr) => {
                writeln!(
                    source,
                    "export function {options}(transport: GraphqlTransport, cacheScope: string, request: RequestOptions = {{}}) {{\n return {{ key: graphqlKey(transport,cacheScope,{key}), fetcher: (_key: unknown, {{arg}}: {{arg: {vars}}}) => {callable}(transport,arg,request) }};\n}}\nexport function {hook}(transport: GraphqlTransport, cacheScope: string, request: RequestOptions = {{}}) {{ const options={options}(transport,cacheScope,request); return useSWRMutation(options.key,options.fetcher); }}"
                )?;
            }
            _ => unreachable!(),
        }
        exports.extend([hook, options]);
    }
    for name in exports {
        cx.workspace.declare(&plugin.output, &name, plugin.kind())?;
    }
    cx.files.emit(GeneratedFile::new(target, source)?)?;
    cx.workspace
        .export_namespace(&plugin.output, &crate::symbols::camel(&plugin.output))?;
    cx.workspace.peer_dependency(dependency, version)?;
    if matches!(plugin.framework, QueryFramework::Vue) {
        cx.workspace.peer_dependency("vue", "3.5.43")?;
    } else {
        cx.workspace.peer_dependency("react", "19.3.0")?;
        cx.workspace.dev_dependency("@types/react", "19.3.0")?;
    }
    Ok(())
}
