//! A broker-specific event SDK, distinct from HTTP and GraphQL contracts.
use crate::{Symbol, TypeScript};
use anyhow::{Result, bail, ensure};
use poolster_core::{
    AdditionalProperties, GeneratedFile, SchemaKind, SchemaValue,
    engine::{Contract, Handle, Meta, Plugin, PluginContext, Provision, Requirement},
    native::events::{EventAction, EventOperations},
};
use std::{collections::BTreeMap, fmt::Write, path::PathBuf};
pub struct AsyncApi {
    meta: Meta,
    provider: Option<Handle<EventOperations>>,
}
pub fn asyncapi(provider: Option<Handle<EventOperations>>) -> AsyncApi {
    AsyncApi {
        meta: Meta::new(),
        provider,
    }
}
#[derive(Clone, Debug)]
pub struct KafkaOperationSymbols {
    pub function: Symbol,
    pub payload: Symbol,
    pub action: EventAction,
}
#[derive(Clone, Debug)]
pub struct KafkaClient {
    pub operations: BTreeMap<String, KafkaOperationSymbols>,
    pub runtime_module: PathBuf,
}
impl Contract for KafkaClient {
    const NAME: &'static str = "poolster.typescript.kafka-client.v1";
}
impl AsyncApi {
    pub fn handle(&self) -> Handle<KafkaClient> {
        self.meta.handle()
    }
}
impl Plugin<TypeScript> for AsyncApi {
    fn kind(&self) -> &'static str {
        "typescript-asyncapi-kafka"
    }
    fn meta(&self) -> &Meta {
        &self.meta
    }
    fn supports_native_input(&self) -> bool {
        true
    }
    fn requires(&self) -> Vec<Requirement> {
        vec![Requirement::on(self.provider)]
    }
    fn provides(&self) -> Vec<Provision> {
        vec![Provision::of::<KafkaClient>()]
    }
    fn generate(&self, cx: &mut PluginContext<'_, TypeScript>) -> Result<()> {
        let input = cx.inputs.get::<EventOperations>()?;
        ensure!(
            !input.operations.is_empty(),
            "Kafka generation needs operations"
        );
        let mut source = String::from(
            "/** Generated by Poolster. */\nimport { KafkaClient } from './kafka-runtime.js';\nimport type { KafkaMessage, KafkaReceivedMessage, ConsumeOptions } from './kafka-runtime.js';\nimport type { EachMessagePayload, KafkaConfig, Consumer, RecordMetadata } from 'kafkajs';\n",
        );
        let mut names = [
            "KafkaClient",
            "KafkaMessage",
            "KafkaReceivedMessage",
            "ConsumeOptions",
            "EachMessagePayload",
            "KafkaConfig",
            "Consumer",
            "RecordMetadata",
            "createKafkaClient",
            "Array",
            "Promise",
            "Record",
        ]
        .into_iter()
        .map(str::to_owned)
        .collect::<std::collections::BTreeSet<_>>();
        let mut operations = BTreeMap::new();
        writeln!(
            source,
            "export function createKafkaClient(config: Partial<KafkaConfig> = {{}}): KafkaClient {{ return new KafkaClient({{brokers: {}, clientId: {}, ...config}}); }}",
            serde_json::to_string(&input.broker.brokers)?,
            serde_json::to_string(input.broker.client_id.as_deref().unwrap_or("poolster"))?
        )?;
        for op in &input.operations {
            let type_name = format!("{}Payload", op.name);
            let header_name = format!("{}Headers", op.name);
            let def_name = format!("{}Operation", op.name);
            for name in [&op.name, &type_name, &header_name, &def_name] {
                identifier(name)?;
                ensure!(
                    names.insert(name.clone()),
                    "Kafka TypeScript symbol collision: {name}"
                );
            }
            let payload = cx.workspace.declare("events", &type_name, self.kind())?;
            let function = cx.workspace.declare("events", &op.name, self.kind())?;
            writeln!(
                source,
                "export type {type_name} = {};",
                render(&op.message.payload)?
            )?;
            writeln!(
                source,
                "export type {header_name} = {};",
                op.message
                    .headers
                    .as_ref()
                    .map(render)
                    .transpose()?
                    .unwrap_or("Record<string, string>".into())
            )?;
            let definition = serde_json::json!({"topic":op.topic,"groupId":op.group_id,"clientId":op.client_id,"payloadSchema":op.message.payload_schema,"headersSchema":op.message.headers_schema,"keySchema":op.message.key_schema});
            let mut definition = definition;
            definition
                .as_object_mut()
                .unwrap()
                .retain(|_, v| !v.is_null());
            writeln!(
                source,
                "const {def_name} = {} as const;",
                serde_json::to_string(&definition)?
            )?;
            let required_headers = op.message.headers.as_ref().is_some_and(|schema| matches!(&schema.kind, SchemaKind::Object { fields, .. } if fields.iter().any(|field| field.required)));
            let envelope = format!(
                "KafkaMessage<{type_name}, {header_name}>{}",
                if required_headers {
                    format!(" & {{ headers: {header_name} }}")
                } else {
                    String::new()
                }
            );
            if op.action == EventAction::Send {
                writeln!(
                    source,
                    "export function {}(client: KafkaClient, message: {envelope}): Promise<RecordMetadata[]> {{ return client.send({def_name}, message); }}",
                    op.name
                )?;
            } else {
                writeln!(
                    source,
                    "export function {}(client: KafkaClient, handler: (message: KafkaReceivedMessage<{type_name}, {header_name}>, metadata: EachMessagePayload) => void | Promise<void>, options?: ConsumeOptions): Promise<Consumer> {{ return client.consume({def_name}, handler, options); }}",
                    op.name
                )?;
            }
            operations.insert(
                op.name.clone(),
                KafkaOperationSymbols {
                    function,
                    payload,
                    action: op.action,
                },
            );
        }
        cx.files.emit(GeneratedFile::new("events.ts", source)?)?;
        cx.files.emit(GeneratedFile::new(
            "kafka-runtime.ts",
            include_str!("../templates/kafka_runtime.ts.tmpl"),
        )?)?;
        cx.files.emit(GeneratedFile::new(
            "asyncapi.json",
            serde_json::to_string_pretty(&input.source)?,
        )?)?;
        cx.workspace.export("events")?;
        cx.workspace.export("kafka-runtime")?;
        cx.workspace.package_file(GeneratedFile::new("package.json",serde_json::to_string_pretty(&serde_json::json!({"name":cx.settings.package_name.as_deref().unwrap_or("poolster-kafka-client"),"version":cx.common.package_version.as_deref().unwrap_or("0.0.0"),"type":"module","main":"./dist/index.js","types":"./dist/index.d.ts","exports":{".":{"types":"./dist/index.d.ts","import":"./dist/index.js"}},"scripts":{"build":"tsc -p tsconfig.json"},"dependencies":{"kafkajs":"2.2.4","ajv":"8.17.1"},"devDependencies":{"typescript":"5.9.3","@types/node":"22.19.15"}}))?)?)?;
        cx.workspace.package_file(GeneratedFile::new("tsconfig.json","{\"compilerOptions\":{\"target\":\"ES2022\",\"module\":\"NodeNext\",\"moduleResolution\":\"NodeNext\",\"strict\":true,\"declaration\":true,\"outDir\":\"dist\",\"types\":[\"node\"]},\"include\":[\"**/*.ts\"],\"exclude\":[\"dist\"]}")?)?;
        cx.publish(KafkaClient {
            operations,
            runtime_module: "kafka-runtime".into(),
        })
    }
}
fn identifier(name: &str) -> Result<()> {
    ensure!(
        !name.is_empty()
            && name
                .chars()
                .enumerate()
                .all(|(i, c)| c.is_ascii_alphabetic() || c == '_' || (i > 0 && c.is_ascii_digit())),
        "unsupported TypeScript event identifier {name}"
    );
    ensure!(
        ![
            "default",
            "function",
            "const",
            "let",
            "var",
            "class",
            "import",
            "export",
            "await",
            "yield",
            "return",
            "new",
            "delete",
            "in",
            "if",
            "else",
            "for",
            "while",
            "throw",
            "try",
            "catch",
            "switch",
            "case",
            "break",
            "continue",
            "this",
            "super",
            "null",
            "true",
            "false",
            "typeof",
            "void",
            "enum",
            "interface",
            "extends",
            "implements",
            "private",
            "protected",
            "public",
            "static"
        ]
        .contains(&name),
        "reserved TypeScript event identifier {name}"
    );
    Ok(())
}
fn render(value: &SchemaValue) -> Result<String> {
    let mut ty = if let Some(value) = &value.const_value {
        serde_json::to_string(value)?
    } else if !value.enum_values.is_empty() {
        value
            .enum_values
            .iter()
            .map(serde_json::to_string)
            .collect::<std::result::Result<Vec<_>, _>>()?
            .join(" | ")
    } else {
        match &value.kind {
            SchemaKind::String => "string".into(),
            SchemaKind::Integer | SchemaKind::Number => "number".into(),
            SchemaKind::Boolean => "boolean".into(),
            SchemaKind::Null => "null".into(),
            SchemaKind::Array { items } => format!("Array<{}>", render(items)?),
            SchemaKind::Object {
                fields,
                additional_properties,
            } => {
                let mut object = String::from("{ ");
                for f in fields {
                    write!(
                        object,
                        "{}{}: {}; ",
                        serde_json::to_string(&f.name)?,
                        if f.required { "" } else { "?" },
                        render(&f.value)?
                    )?;
                }
                object.push('}');
                match additional_properties {
                    AdditionalProperties::Forbidden => object,
                    AdditionalProperties::Any | AdditionalProperties::Unspecified => {
                        format!("{object} & Record<string, unknown>")
                    }
                    AdditionalProperties::Schema { .. } => {
                        bail!("typed additionalProperties unsupported for event TypeScript")
                    }
                }
            }
            _ => bail!("unsupported event model kind"),
        }
    };
    if value.nullable {
        ty = format!("({ty}) | null");
    }
    Ok(ty)
}
