//! Selection-specific SDKs consume Poolster contracts rather than parser ASTs.
mod render;
mod scalars;
use crate::TypeScript;
use anyhow::{Result, bail};
use poolster_core::{
    GeneratedFile,
    engine::{Contract, Handle, Meta, Plugin, PluginContext, Provision, Requirement},
    native::{GraphqlOperationKind, GraphqlOperations, ModelField, ModelKind, ModelType},
};
use render::{render_fields, render_type};
pub use scalars::GraphqlScalarMapping;
use std::{collections::BTreeMap, fmt::Write, path::PathBuf};
/// Actual emitted GraphQL operation symbols for downstream generation plugins.
#[derive(Clone, Debug)]
pub struct GraphqlOperationSymbols {
    pub function: crate::Symbol,
    pub variables: crate::Symbol,
    pub result: crate::Symbol,
    pub kind: GraphqlOperationKind,
}
/// Output capability distinct from HTTP SDK contracts.
#[derive(Clone, Debug)]
pub struct GraphqlClient {
    pub operations: BTreeMap<String, GraphqlOperationSymbols>,
    /// Package-relative module without extension.
    pub runtime_module: PathBuf,
}
impl Contract for GraphqlClient {
    const NAME: &'static str = "poolster.typescript.graphql-client.v1";
}
pub struct Graphql {
    meta: Meta,
    provider: Option<Handle<GraphqlOperations>>,
    subscriptions: bool,
    scalars: BTreeMap<String, GraphqlScalarMapping>,
}
pub fn graphql(provider: Option<Handle<GraphqlOperations>>) -> Graphql {
    Graphql {
        meta: Meta::new(),
        provider,
        subscriptions: false,
        scalars: BTreeMap::new(),
    }
}
impl Graphql {
    /// Map a custom scalar's input and output wire types without installing codecs.
    pub fn scalar(mut self, name: impl Into<String>, mapping: GraphqlScalarMapping) -> Self {
        self.scalars.insert(name.into(), mapping);
        self
    }
    pub fn scalars(mut self, mappings: BTreeMap<String, GraphqlScalarMapping>) -> Self {
        self.scalars.extend(mappings);
        self
    }
    pub fn handle(&self) -> Handle<GraphqlClient> {
        self.meta.handle()
    }
    /// Enable subscriptions using a separately injected SubscriptionTransport.
    pub fn subscriptions(mut self) -> Self {
        self.subscriptions = true;
        self
    }
    pub fn label(mut self, label: impl Into<String>) -> Self {
        self.meta = self.meta.label(label);
        self
    }
}
impl Plugin<TypeScript> for Graphql {
    fn kind(&self) -> &'static str {
        "typescript-graphql"
    }
    fn supports_native_input(&self) -> bool {
        true
    }
    fn meta(&self) -> &Meta {
        &self.meta
    }
    fn provides(&self) -> Vec<Provision> {
        vec![Provision::of::<GraphqlClient>()]
    }
    fn requires(&self) -> Vec<Requirement> {
        vec![Requirement::on(self.provider)]
    }
    fn generate(&self, cx: &mut PluginContext<'_, TypeScript>) -> Result<()> {
        let contract = cx.inputs.get::<GraphqlOperations>()?;
        scalars::validate_mappings(&self.scalars, contract)?;
        if contract.operations.is_empty() {
            bail!("GraphQL generation requires operation documents");
        }
        let mut out = String::from(
            "/** Generated by Poolster. */\nimport type { GraphqlTransport, SubscriptionTransport, GraphqlResult, RequestOptions } from './graphql-runtime.js';\n",
        );
        let mut names = [
            "GraphqlTransport",
            "SubscriptionTransport",
            "GraphqlResult",
            "RequestOptions",
            "GraphqlError",
            "GraphqlHttpError",
            "GraphqlProtocolError",
            "createGraphqlHttpTransport",
            "Array",
            "Promise",
            "AsyncIterable",
        ]
        .into_iter()
        .map(str::to_owned)
        .collect::<std::collections::BTreeSet<_>>();
        for fields in contract.input_objects.values() {
            for field in fields {
                validate_type(&field.ty, contract)?;
            }
        }
        for op in &contract.operations {
            validate_type(&op.result, contract)?;
            for field in &op.variables {
                validate_type(&field.ty, contract)?;
            }
        }
        for (name, fields) in &contract.input_objects {
            identifier(name)?;
            writeln!(
                out,
                "export type {name} = {};",
                render_fields(fields, &self.scalars, true)
            )?;
            if !names.insert(name.clone()) {
                bail!("GraphQL TypeScript symbol collision: {name}");
            }
            cx.workspace.declare("graphql", name, self.kind())?;
        }
        let mut operations = BTreeMap::new();
        for op in &contract.operations {
            identifier(&op.name)?;
            let mut symbols = Vec::new();
            for name in [
                format!("{}Variables", op.name),
                format!("{}Result", op.name),
                op.name.clone(),
            ] {
                if !names.insert(name.clone()) {
                    bail!("GraphQL TypeScript symbol collision: {name}");
                }
                symbols.push(cx.workspace.declare("graphql", &name, self.kind())?);
            }
            operations.insert(
                op.name.clone(),
                GraphqlOperationSymbols {
                    variables: symbols[0].clone(),
                    result: symbols[1].clone(),
                    function: symbols[2].clone(),
                    kind: op.kind,
                },
            );
            let variables = format!("{}Variables", op.name);
            let result = format!("{}Result", op.name);
            writeln!(
                out,
                "export type {variables} = {};",
                render_fields(&op.variables, &self.scalars, true)
            )?;
            writeln!(
                out,
                "export type {result} = {};",
                render_type(&op.result, &self.scalars, false)
            )?;
            let doc = serde_json::to_string(&op.document)?;
            let name = serde_json::to_string(&op.name)?;
            if op.kind == GraphqlOperationKind::Subscription {
                if !self.subscriptions {
                    bail!(
                        "GraphQL subscription {} requires separately enabled injected subscription transport capability",
                        op.name
                    );
                }
                writeln!(
                    out,
                    "export function {}(transport: SubscriptionTransport, variables: {variables}, options?: RequestOptions): AsyncIterable<GraphqlResult<{result}>> {{ return transport.subscribe<{result}>({doc}, {name}, variables, options); }}",
                    op.name
                )?;
            } else {
                writeln!(
                    out,
                    "export function {}(transport: GraphqlTransport, variables: {variables}, options?: RequestOptions): Promise<GraphqlResult<{result}>> {{ return transport.execute<{result}>({doc}, {name}, variables, options); }}",
                    op.name
                )?;
            }
        }
        cx.files.emit(GeneratedFile::new("graphql.ts", out)?)?;
        cx.files.emit(GeneratedFile::new(
            "graphql-runtime.ts",
            include_str!("../templates/graphql_runtime.ts.tmpl"),
        )?)?;
        cx.workspace.export("graphql")?;
        cx.workspace.export("graphql-runtime")?;
        cx.workspace.package_file(GeneratedFile::new("package.json", serde_json::to_string_pretty(&serde_json::json!({"name": cx.settings.package_name.as_deref().unwrap_or("poolster-graphql-client"), "version":cx.common.package_version.as_deref().unwrap_or("0.0.0"), "type":"module", "main":"./dist/index.js", "types":"./dist/index.d.ts", "exports":{".":{"types":"./dist/index.d.ts","import":"./dist/index.js"}}, "scripts":{"build":"tsc -p tsconfig.json"}, "devDependencies":{"typescript":"5.9.3"}}))?)?)?;
        cx.workspace.package_file(GeneratedFile::new("tsconfig.json", "{\"compilerOptions\":{\"target\":\"ES2022\",\"module\":\"NodeNext\",\"moduleResolution\":\"NodeNext\",\"strict\":true,\"declaration\":true,\"outDir\":\"dist\",\"lib\":[\"ES2022\",\"DOM\"]},\"include\":[\"**/*.ts\"],\"exclude\":[\"dist\"]}\n")?)?;
        cx.publish(GraphqlClient {
            operations,
            runtime_module: "graphql-runtime".into(),
        })
    }
}
fn identifier(value: &str) -> Result<()> {
    const RESERVED: &[&str] = &[
        "default",
        "class",
        "function",
        "var",
        "let",
        "const",
        "import",
        "export",
        "return",
        "new",
        "delete",
        "in",
        "instanceof",
        "typeof",
        "void",
        "await",
        "yield",
        "enum",
        "extends",
        "implements",
        "interface",
        "package",
        "private",
        "protected",
        "public",
        "static",
        "null",
        "true",
        "false",
        "this",
        "super",
        "switch",
        "case",
        "break",
        "continue",
        "throw",
        "try",
        "catch",
        "finally",
        "while",
        "do",
        "for",
        "if",
        "else",
        "with",
        "debugger",
        "eval",
        "arguments",
        "any",
        "string",
        "number",
        "boolean",
        "unknown",
        "never",
        "object",
        "symbol",
        "bigint",
        "undefined",
    ];
    if value.is_empty()
        || !value
            .chars()
            .enumerate()
            .all(|(i, c)| c.is_ascii_alphabetic() || c == '_' || (i > 0 && c.is_ascii_digit()))
        || RESERVED.contains(&value)
    {
        bail!("GraphQL name {value:?} cannot be emitted as a TypeScript identifier");
    }
    Ok(())
}
fn validate_type(ty: &ModelType, contract: &GraphqlOperations) -> Result<()> {
    match &ty.kind {
        ModelKind::Named(name) => {
            identifier(name)?;
            if !contract.input_objects.contains_key(name) {
                bail!("GraphQL contract references missing input type {name}");
            }
        }
        ModelKind::Object(fields) => {
            let mut names = std::collections::BTreeSet::new();
            for field in fields {
                if !names.insert(&field.name) {
                    bail!("GraphQL contract contains duplicate field {}", field.name);
                }
                validate_type(&field.ty, contract)?;
            }
        }
        ModelKind::List(item) => validate_type(item, contract)?,
        ModelKind::Union(items) => {
            for item in items {
                validate_type(item, contract)?;
            }
        }
        ModelKind::Enum(items) if items.is_empty() => bail!("GraphQL contract contains empty enum"),
        _ => {}
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn substituted_models_reject_unsafe_names_and_missing_refs() {
        let contract = GraphqlOperations {
            schema_source: String::new(),
            operation_source: String::new(),
            operations: vec![],
            input_objects: Default::default(),
        };
        for name in ["Missing", "Injected; export const bad = 1"] {
            let ty = ModelType {
                nullable: false,
                kind: ModelKind::Named(name.into()),
            };
            assert!(validate_type(&ty, &contract).is_err());
        }
        assert!(
            validate_type(
                &ModelType {
                    nullable: false,
                    kind: ModelKind::Enum(vec![])
                },
                &contract
            )
            .is_err()
        );
        assert_eq!(
            render_type(
                &ModelType {
                    nullable: false,
                    kind: ModelKind::Union(vec![])
                },
                &BTreeMap::new(),
                false
            ),
            "never"
        );
    }
}
