//! Selection-specific SDKs consume Poolster contracts rather than parser ASTs.
mod facade;
mod render;
mod validation;
pub use facade::GraphqlStyle;
use validation::{identifier, validate_type};
mod scalars;
use crate::TypeScript;
use anyhow::{Result, bail};
use poolster_core::{
    GeneratedFile,
    engine::{Contract, Handle, Meta, Plugin, PluginContext, Provision, Requirement},
    native::{GraphqlOperationKind, GraphqlOperations, ModelField, ModelKind, ModelType},
};
use render::{render_fields, render_type};
pub use scalars::GraphqlScalarMapping;
use std::{collections::BTreeMap, fmt::Write, path::PathBuf};
/// Actual emitted GraphQL operation symbols for downstream generation plugins.
#[derive(Clone, Debug)]
pub struct GraphqlOperationSymbols {
    pub function: crate::Symbol,
    /// Canonical camelCase standalone operation, retaining the original function.
    pub raw_function: crate::Symbol,
    pub variables: crate::Symbol,
    pub result: crate::Symbol,
    pub kind: GraphqlOperationKind,
}
/// Output capability distinct from HTTP SDK contracts.
#[derive(Clone, Debug)]
pub struct GraphqlClient {
    pub operations: BTreeMap<String, GraphqlOperationSymbols>,
    /// Package-relative module without extension.
    pub runtime_module: PathBuf,
    pub style: GraphqlStyle,
    pub factory: Option<crate::Symbol>,
    pub methods: BTreeMap<String, String>,
    /// Authoritative selected contract used to render this client.
    pub definition: GraphqlOperations,
    pub scalars: BTreeMap<String, GraphqlScalarMapping>,
}
impl Contract for GraphqlClient {
    const NAME: &'static str = "poolster.typescript.graphql-client.v1";
}
pub struct Graphql {
    meta: Meta,
    provider: Option<Handle<GraphqlOperations>>,
    subscriptions: bool,
    style: GraphqlStyle,
    groups: BTreeMap<String, BTreeMap<String, String>>,
    scalars: BTreeMap<String, GraphqlScalarMapping>,
}
pub fn graphql(provider: Option<Handle<GraphqlOperations>>) -> Graphql {
    Graphql {
        meta: Meta::new(),
        provider,
        subscriptions: false,
        style: GraphqlStyle::Idiomatic,
        groups: BTreeMap::new(),
        scalars: BTreeMap::new(),
    }
}
impl Graphql {
    pub fn group(
        mut self,
        group: impl Into<String>,
        method: impl Into<String>,
        operation: impl Into<String>,
    ) -> Self {
        self.groups
            .entry(group.into())
            .or_default()
            .insert(method.into(), operation.into());
        self
    }
    pub fn groups(mut self, groups: BTreeMap<String, BTreeMap<String, String>>) -> Self {
        self.groups = groups;
        self
    }

    pub fn raw(mut self) -> Self {
        self.style = GraphqlStyle::Raw;
        self
    }
    pub fn flat(mut self) -> Self {
        self.style = GraphqlStyle::Flat;
        self
    }
    pub fn idiomatic(mut self) -> Self {
        self.style = GraphqlStyle::Idiomatic;
        self
    }
    pub fn namespaced(self) -> Self {
        self.idiomatic()
    }

    /// Map a custom scalar's input and output wire types without installing codecs.
    pub fn scalar(mut self, name: impl Into<String>, mapping: GraphqlScalarMapping) -> Self {
        self.scalars.insert(name.into(), mapping);
        self
    }
    pub fn scalars(mut self, mappings: BTreeMap<String, GraphqlScalarMapping>) -> Self {
        self.scalars.extend(mappings);
        self
    }
    pub fn handle(&self) -> Handle<GraphqlClient> {
        self.meta.handle()
    }
    /// Enable subscriptions using a separately injected SubscriptionTransport.
    pub fn subscriptions(mut self) -> Self {
        self.subscriptions = true;
        self
    }
    pub fn label(mut self, label: impl Into<String>) -> Self {
        self.meta = self.meta.label(label);
        self
    }
}
impl Plugin<TypeScript> for Graphql {
    fn kind(&self) -> &'static str {
        "typescript-graphql"
    }
    fn supports_native_input(&self) -> bool {
        true
    }
    fn meta(&self) -> &Meta {
        &self.meta
    }
    fn provides(&self) -> Vec<Provision> {
        vec![Provision::of::<GraphqlClient>()]
    }
    fn requires(&self) -> Vec<Requirement> {
        vec![Requirement::on(self.provider)]
    }
    fn generate(&self, cx: &mut PluginContext<'_, TypeScript>) -> Result<()> {
        let mut oversized = Vec::new();
        let contract = cx.inputs.get::<GraphqlOperations>()?;
        scalars::validate_mappings(&self.scalars, contract)?;
        if contract.operations.is_empty() {
            bail!("GraphQL generation requires operation documents");
        }
        let mut out = String::from(
            "/** Generated by Poolster. */\nimport type { GraphqlTransport, SubscriptionTransport, GraphqlResult, RequestOptions } from './graphql-runtime.js';\n",
        );
        let mut model_exports = String::new();
        let mut operation_exports = String::new();
        let mut file_names = std::collections::BTreeSet::new();
        let mut names = [
            "GraphqlTransport",
            "SubscriptionTransport",
            "GraphqlResult",
            "RequestOptions",
            "GraphqlError",
            "GraphqlHttpError",
            "GraphqlProtocolError",
            "createGraphqlHttpTransport",
            "Array",
            "Promise",
            "AsyncIterable",
            "createClient",
            "GraphqlClientOptions",
            "GraphqlBoundClient",
            "HeadersInit",
        ]
        .into_iter()
        .map(str::to_owned)
        .collect::<std::collections::BTreeSet<_>>();
        for fields in contract.input_objects.values() {
            for field in fields {
                validate_type(&field.ty, contract)?;
            }
        }
        for op in &contract.operations {
            validate_type(&op.result, contract)?;
            for field in &op.variables {
                validate_type(&field.ty, contract)?;
            }
        }
        for (name, fields) in &contract.input_objects {
            identifier(name)?;
            let file_name = poolster_core::files::source_file_stem(name);
            anyhow::ensure!(
                file_names.insert(file_name.to_ascii_lowercase()),
                "GraphQL source filename collision: {name}"
            );
            let mut model_source = String::from("/** Generated by Poolster. */\n");
            let mut dependencies = std::collections::BTreeSet::new();
            for field in fields {
                named_dependencies(&field.ty, &mut dependencies);
            }
            for other in &dependencies {
                if other != name {
                    writeln!(
                        model_source,
                        "import type {{ {other} }} from './{}.js';",
                        poolster_core::files::source_file_stem(other)
                    )?;
                }
            }
            writeln!(
                model_source,
                "export type {name} = {};",
                render_fields(fields, &self.scalars, true)
            )?;
            if !names.insert(name.clone()) {
                bail!("GraphQL TypeScript symbol collision: {name}");
            }
            emit_source(
                &mut cx.files,
                GeneratedFile::new(format!("graphql/models/{file_name}.ts"), model_source)?,
                &mut oversized,
            )?;
            writeln!(
                model_exports,
                "export type {{ {name} }} from './graphql/models/{file_name}.js';"
            )?;
            cx.workspace.declare("graphql", name, self.kind())?;
        }
        let mut operations = BTreeMap::new();
        let mut ordered_operations: Vec<_> = contract.operations.iter().collect();
        ordered_operations.sort_by_key(|op| &op.name);
        for op in ordered_operations {
            identifier(&op.name)?;
            let mut symbols = Vec::new();
            for name in [
                format!("{}Variables", op.name),
                format!("{}Result", op.name),
                op.name.clone(),
            ] {
                if !names.insert(name.clone()) {
                    bail!("GraphQL TypeScript symbol collision: {name}");
                }
                symbols.push(cx.workspace.declare("graphql", &name, self.kind())?);
            }
            let raw_name = crate::symbols::camel(&op.name);
            let raw_function = if raw_name == op.name {
                symbols[2].clone()
            } else {
                if !names.insert(raw_name.clone()) {
                    bail!("GraphQL TypeScript symbol collision: {raw_name}");
                }
                cx.workspace.declare("graphql", &raw_name, self.kind())?
            };
            operations.insert(
                op.name.clone(),
                GraphqlOperationSymbols {
                    variables: symbols[0].clone(),
                    result: symbols[1].clone(),
                    function: symbols[2].clone(),
                    raw_function,
                    kind: op.kind,
                },
            );
            let mut model_source = String::from("/** Generated by Poolster. */\n");
            let file_name = poolster_core::files::source_file_stem(&op.name);
            anyhow::ensure!(
                file_names.insert(file_name.to_ascii_lowercase()),
                "GraphQL source filename collision: {}",
                op.name
            );
            let mut dependencies = std::collections::BTreeSet::new();
            for field in &op.variables {
                named_dependencies(&field.ty, &mut dependencies);
            }
            for input in &dependencies {
                writeln!(
                    model_source,
                    "import type {{ {input} }} from './{}.js';",
                    poolster_core::files::source_file_stem(input)
                )?;
            }
            let variables = format!("{}Variables", op.name);
            let result = format!("{}Result", op.name);
            writeln!(
                model_source,
                "export type {variables} = {};",
                render_fields(&op.variables, &self.scalars, true)
            )?;
            writeln!(
                model_source,
                "export type {result} = {};",
                render_type(&op.result, &self.scalars, false)
            )?;
            emit_source(
                &mut cx.files,
                GeneratedFile::new(format!("graphql/models/{file_name}.ts"), model_source)?,
                &mut oversized,
            )?;
            writeln!(
                model_exports,
                "export type {{ {variables}, {result} }} from './graphql/models/{file_name}.js';"
            )?;
            let mut operation_source = format!(
                "/** Generated by Poolster. */\nimport type {{ GraphqlTransport, SubscriptionTransport, GraphqlResult, RequestOptions }} from '../../graphql-runtime.js';\nimport type {{ {variables}, {result} }} from '../models/{file_name}.js';\n"
            );
            let doc = serde_json::to_string(&op.document)?;
            let name = serde_json::to_string(&op.name)?;
            if op.kind == GraphqlOperationKind::Subscription {
                if !self.subscriptions {
                    bail!(
                        "GraphQL subscription {} requires separately enabled injected subscription transport capability",
                        op.name
                    );
                }
                writeln!(
                    operation_source,
                    "export function {}(transport: SubscriptionTransport, variables: {variables}, options?: RequestOptions): AsyncIterable<GraphqlResult<{result}>> {{ return transport.subscribe<{result}>({doc}, {name}, variables, options); }}",
                    op.name
                )?;
            } else {
                writeln!(
                    operation_source,
                    "export function {}(transport: GraphqlTransport, variables: {variables}, options?: RequestOptions): Promise<GraphqlResult<{result}>> {{ return transport.execute<{result}>({doc}, {name}, variables, options); }}",
                    op.name
                )?;
            }
            let alias = crate::symbols::camel(&op.name);
            if alias != op.name {
                writeln!(operation_source, "export const {alias} = {};", op.name)?;
            }
            emit_source(
                &mut cx.files,
                GeneratedFile::new(
                    format!("graphql/operations/{file_name}.ts"),
                    operation_source,
                )?,
                &mut oversized,
            )?;
            writeln!(
                operation_exports,
                "export * from './graphql/operations/{file_name}.js';"
            )?;
        }
        let mut client_files = BTreeMap::new();
        let methods = facade::render_files(
            &mut out,
            self.style,
            contract,
            &self.groups,
            &mut client_files,
        )?;
        for (path, content) in client_files {
            emit_source(
                &mut cx.files,
                GeneratedFile::new(path, content)?,
                &mut oversized,
            )?;
        }
        let factory = if self.style != GraphqlStyle::Raw {
            cx.workspace
                .declare("graphql", "GraphqlClientOptions", self.kind())?;
            cx.workspace
                .declare("graphql", "GraphqlBoundClient", self.kind())?;
            Some(
                cx.workspace
                    .declare("graphql", "createClient", self.kind())?,
            )
        } else {
            None
        };
        let mut entry = String::from(
            "/** Public GraphQL entry point. Generated by Poolster. */\nexport * from './graphql-models.js';\nexport * from './graphql-operations.js';\n",
        );
        if self.style != GraphqlStyle::Raw {
            entry.push_str("export * from './graphql-client.js';\n");
            emit_source(
                &mut cx.files,
                GeneratedFile::new("graphql-client.ts", out)?,
                &mut oversized,
            )?;
        }
        for (category, exports) in [("models", model_exports), ("operations", operation_exports)] {
            let lines: Vec<_> = exports.lines().collect();
            let mut barrel = String::from("/** Generated exports. */\n");
            for (index, chunk) in lines.chunks(64).enumerate() {
                let source = chunk
                    .join("\n")
                    .replace(&format!("'./graphql/{category}/"), "'../")
                    + "\n";
                emit_source(
                    &mut cx.files,
                    GeneratedFile::new(
                        format!("graphql/{category}/_exports/part_{index}.ts"),
                        source,
                    )?,
                    &mut oversized,
                )?;
                writeln!(
                    barrel,
                    "export * from './graphql/{category}/_exports/part_{index}.js';"
                )?;
            }
            emit_source(
                &mut cx.files,
                GeneratedFile::new(format!("graphql-{category}.ts"), barrel)?,
                &mut oversized,
            )?;
        }
        emit_source(
            &mut cx.files,
            GeneratedFile::new("graphql.ts", entry)?,
            &mut oversized,
        )?;
        emit_source(
            &mut cx.files,
            GeneratedFile::new(
                "graphql-runtime.ts",
                include_str!("../templates/graphql_runtime.ts.tmpl"),
            )?,
            &mut oversized,
        )?;
        cx.workspace.export("graphql")?;
        cx.workspace.export("graphql-runtime")?;
        cx.workspace.package_file(GeneratedFile::new("package.json", serde_json::to_string_pretty(&serde_json::json!({"name": cx.settings.package_name.as_deref().unwrap_or("poolster-graphql-client"), "version":cx.common.package_version.as_deref().unwrap_or("0.0.0"), "type":"module", "main":"./dist/index.js", "types":"./dist/index.d.ts", "exports":{".":{"types":"./dist/index.d.ts","import":"./dist/index.js"}}, "scripts":{"build":"tsc -p tsconfig.json"}, "devDependencies":{"typescript":"5.9.3"}}))?)?)?;
        cx.workspace.package_file(GeneratedFile::new("tsconfig.json", "{\"compilerOptions\":{\"target\":\"ES2022\",\"module\":\"NodeNext\",\"moduleResolution\":\"NodeNext\",\"strict\":true,\"declaration\":true,\"outDir\":\"dist\",\"lib\":[\"ES2022\",\"DOM\"]},\"include\":[\"**/*.ts\"],\"exclude\":[\"dist\"]}\n")?)?;
        if !oversized.is_empty() {
            cx.files.emit(GeneratedFile::new(
                ".poolster/source-layout-diagnostics.json",
                serde_json::to_string_pretty(&oversized)?,
            )?)?;
        }
        cx.publish(GraphqlClient {
            operations,
            runtime_module: "graphql-runtime".into(),
            style: self.style,
            factory,
            methods,
            definition: contract.clone(),
            scalars: self.scalars.clone(),
        })
    }
}

fn named_dependencies(ty: &ModelType, names: &mut std::collections::BTreeSet<String>) {
    match &ty.kind {
        ModelKind::Named(name) => {
            names.insert(name.clone());
        }
        ModelKind::List(item) => named_dependencies(item, names),
        ModelKind::Object(fields) => {
            for field in fields {
                named_dependencies(&field.ty, names);
            }
        }
        ModelKind::Union(variants) => {
            for variant in variants {
                named_dependencies(variant, names);
            }
        }
        _ => {}
    }
}

fn emit_source(
    files: &mut poolster_core::engine::Emitter<'_>,
    file: GeneratedFile,
    oversized: &mut Vec<serde_json::Value>,
) -> Result<()> {
    if file.contents.len() > 128 * 1024 {
        oversized.push(serde_json::json!({"path": file.path, "bytes": file.contents.len(), "max_file_bytes": 128 * 1024, "reason": "GraphQL source exceeds the grouping budget; retained intact. Review selection size or layout."}));
    }
    files.emit(file)
}
