const assert = require('node:assert/strict');
const { createClient } = require('./runtime.js');
let seen;
let media = 'application/x-ndjson';
let body = '{"value":1}\n{"value":2}\n';
const client = process.env.KAJI_CONTROL_AXIOS
  ? createClient({ client: { request: async request => { seen = request; return { status: 200, headers: { 'content-type': media }, data: request.responseType === 'arraybuffer' ? Buffer.from(body) : body }; } }, retry: false })
  : createClient({ fetch: async (url, request) => { seen = { url, ...request }; return new Response(body, { headers: { 'content-type': media } }); }, retry: false });
(async () => {
  const result = await client({ method: 'GET', url: '/records', querystring: { filter: { tag: ['a b', 'x&y'], zero: 0 } }, wholeQuery: { name: 'filter', contentType: 'application/x-www-form-urlencoded' } });
  assert.equal(seen.url, '/records?tag=a+b&tag=x%26y&zero=0');
  assert.deepEqual(result.data, [{ value: 1 }, { value: 2 }]);
  await client({ method: 'POST', url: '/records', body: [{ value: 7 }, null], contentType: { request: 'application/json-seq' } });
  assert.equal(seen.body ?? seen.data, '\x1e{"value":7}\n\x1enull\n');
  await client({ method: 'POST', url: '/mixed', body: [{ value: 9 }, ['nested', null]], contentType: { request: 'multipart/mixed' }, multipartPlan: { content_type: 'multipart/mixed', prefix_encoding: [{ contentType: 'application/json' }, { contentType: 'multipart/mixed', prefixEncoding: [{ contentType: 'text/plain' }, { contentType: 'application/json' }] }] } });
  const multipart = seen.body ?? seen.data;
  assert(multipart instanceof Blob);
  const mime = await multipart.text();
  assert(multipart.type.startsWith('multipart/mixed; boundary='));
  assert(mime.includes('Content-Type: application/json\r\n\r\n{"value":9}'));
  assert(mime.includes('Content-Type: multipart/mixed; boundary='));
  assert(mime.includes('Content-Type: text/plain\r\n\r\nnested'));
  assert(mime.includes('Content-Type: application/json\r\n\r\nnull'));
  assert(!mime.includes('Content-Disposition: form-data'));
  await client({ method: 'GET', url: '/items/{selector}', path: { selector: { id: 0 } }, query: { filter: { enabled: false } }, headers: { condition: { id: 1 } }, cookies: { preferences: { id: 2 } }, styles: { path: { selector: { contentType: 'application/json' } }, query: { filter: { contentType: 'application/json' } }, header: { condition: { contentType: 'application/json' } }, cookie: { preferences: { contentType: 'application/json' } } } });
  const parsed = new URL(seen.url, 'https://api.example');
  assert.equal(decodeURIComponent(parsed.pathname), '/items/{"id":0}');
  if (process.env.KAJI_CONTROL_AXIOS) assert.equal(seen.params.filter, '{"enabled":false}');
  else assert.equal(parsed.searchParams.get('filter'), '{"enabled":false}');
  const headers = new Headers(seen.headers);
  assert.equal(headers.get('condition'), '{"id":1}');
  assert.equal(decodeURIComponent(headers.get('cookie')), 'preferences={"id":2}');
  media = 'application/json-seq'; body = '\x1e9223372036854775807\n';
  const shape = { kind: 'array', items: { kind: 'integer', integer: 'bigint' } };
  const jsonPlan = { lossless: true, refs: {}, requests: { 'application/json-seq': shape }, responses: { '200': { 'application/json-seq': shape } } };
  assert.deepEqual((await client({ method: 'POST', url: '/records', body: [9223372036854775807n], contentType: { request: 'application/json-seq' }, jsonPlan })).data, [9223372036854775807n]);
  assert.equal(seen.body ?? seen.data, '\x1e9223372036854775807\n');
  media = 'application/json-seq'; body = '\x1e{"value":3}\n\x1e{"value":4}\n';
  assert.deepEqual((await client({ method: 'GET', url: '/records' })).data, [{ value: 3 }, { value: 4 }]);
  media = 'multipart/mixed'; body = '--part\r\nContent-Type: text/plain\r\n\r\nvalue\r\n--part--\r\n';
  const mimeResponse = (await client({ method: 'GET', url: '/mixed', responseType: 'arraybuffer' })).data;
  assert.equal(Buffer.from(mimeResponse).toString('utf8'), body);
  media = 'application/json-seq';
  body = '\x1e{"broken":\n';
  await assert.rejects(client({ method: 'GET', url: '/records' }));
  body = '{"preamble":true}\x1e{}';
  await assert.rejects(client({ method: 'GET', url: '/records' }));
  await assert.rejects(client({ method: 'GET', url: '/records', querystring: { filter: 'x=1#bad' }, wholeQuery: { name: 'filter', contentType: 'text/plain' } }));
})().catch(error => { console.error(error); process.exitCode = 1; });
