//! TypeScript target plugins.
//!
//! Each plugin owns one concern, so a project can combine models with exactly
//! the transports it wants. The generated source is plain TypeScript: Rust is
//! the only code that runs while generation is happening.

use std::fmt::Write;

use anyhow::Result;
use serde_json::{Value, json};

use poolster_core::GeneratedFile;
use poolster_core::ast::{AdditionalProperties, Api, SchemaKind, SchemaValue};

mod query;
pub use query::{TypeScriptReactQuery, TypeScriptSwr, TypeScriptVueQuery};
pub(crate) use query::{query_exports, render_query_operation};

mod cypress;
mod faker;
mod msw;
mod zod;
pub use cypress::TypeScriptCypress;
pub use faker::TypeScriptFaker;
pub use msw::TypeScriptMsw;
pub use zod::TypeScriptZod;
pub(crate) use zod::{render_zod, render_zod_operation_registry, render_zod_operation_schemas};

const NOTICE: &str = "// Generated by Poolster Codegen. Do not edit.\n";

/// Explicit settings for standalone auxiliary artifacts. These renderers return
/// files; plugin authors decide how to publish them and their dependencies.
#[derive(Clone, Debug)]
pub struct ArtifactOptions {
    pub output_dir: Option<String>,
    pub package_name: Option<String>,
    pub naming: Naming,
    pub openapi_spec: Option<String>,
    pub title: Option<String>,
    /// Import prefix from the generated artifact to the operation modules.
    pub clients_import: String,
    pub group_by_tag: bool,
    /// Split auxiliary output at declaration boundaries near this byte budget.
    pub max_file_bytes: usize,
    pub layout: Option<poolster_core::SourceLayout>,
    pub fixture_options: crate::FixtureOptions,
    pub cypress_options: crate::CypressOptions,
}
impl Default for ArtifactOptions {
    fn default() -> Self {
        Self {
            output_dir: None,
            package_name: None,
            naming: Naming::CamelCase,
            openapi_spec: None,
            title: None,
            clients_import: "./clients".into(),
            group_by_tag: true,
            max_file_bytes: 128 * 1024,
            layout: None,
            fixture_options: Default::default(),
            cypress_options: Default::default(),
        }
    }
}
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub enum Naming {
    #[default]
    CamelCase,
    PascalCase,
    SnakeCase,
}

/// Emits reusable TypeScript types from the normalized schema graph.
#[derive(Default)]
pub struct TypeScriptModels;

impl TypeScriptModels {
    pub fn generate(&self, api: &Api, config: &ArtifactOptions) -> Result<Vec<GeneratedFile>> {
        crate::auxiliary_layout::models(api, config)
    }
}

/// Emits `index.ts`, package metadata, and a strict TypeScript configuration.
#[derive(Default)]
pub struct TypeScriptPackage;

impl TypeScriptPackage {
    pub fn generate(&self, api: &Api, config: &ArtifactOptions) -> Result<Vec<GeneratedFile>> {
        let index = format!("{NOTICE}\nexport * from './models';\n");
        let package_name = config
            .package_name
            .clone()
            .unwrap_or_else(|| format!("@poolster/{}", package_slug(&api.name)));
        let package = json!({
            "name": package_name,
            "version": api.version,
            "description": format!("{} API client generated by Poolster Codegen", api.name),
            "type": "module",
            "sideEffects": false,
            "exports": {
                ".": { "types": "./dist/index.d.ts", "import": "./dist/index.js" },
                "./*": { "types": "./dist/*.d.ts", "import": "./dist/*.js" }
            },
            "files": ["dist"],
            "scripts": { "build": "tsc -p tsconfig.json" },
            "devDependencies": { "typescript": "^5.9.3" }
        });
        Ok(vec![
            GeneratedFile::new(output_path(config, "index.ts"), index)?,
            GeneratedFile::new(
                output_path(config, "package.json"),
                format!("{}\n", serde_json::to_string_pretty(&package)?),
            )?,
            GeneratedFile::new(output_path(config, "tsconfig.json"), tsconfig())?,
        ])
    }
}

pub(crate) fn output_path(config: &ArtifactOptions, file: &str) -> String {
    let directory = config.output_dir.as_deref().unwrap_or("typescript");
    match directory {
        "" | "." => file.to_owned(),
        _ => format!("{directory}/{file}"),
    }
}

mod schema;
pub(crate) use schema::*;

fn tsconfig() -> &'static str {
    r#"{
  "compilerOptions": {
    "declaration": true,
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "outDir": "dist",
    "strict": true,
    "skipLibCheck": true,
    "target": "ES2022"
  },
  "include": ["*.ts"]
}
"#
}

mod names;
pub(crate) use names::*;

mod documentation;
pub(crate) use documentation::extra_output_path;
pub use documentation::{McpToolManifest, ReDoc};

#[cfg(test)]
mod tests;
