//! Executable source-resolved workflows, independent from HTTP SDK model plugins.
use crate::TypeScript;
use anyhow::{Result, ensure};
use poolster_core::{
    GeneratedFile,
    engine::{Contract, Handle, Meta, Plugin, PluginContext, Provision, Requirement},
    native::{ModelField, ModelKind, ModelType, workflows::WorkflowOperations},
};
use std::{collections::BTreeMap, fmt::Write, path::PathBuf};

#[derive(Clone, Debug)]
pub struct WorkflowClient {
    pub workflows: BTreeMap<String, crate::Symbol>,
    pub runtime_module: PathBuf,
}
impl Contract for WorkflowClient {
    const NAME: &'static str = "poolster.typescript.workflow-client.v1";
}
pub struct WorkflowRunner {
    meta: Meta,
    provider: Option<Handle<WorkflowOperations>>,
}
pub fn workflow(provider: Option<Handle<WorkflowOperations>>) -> WorkflowRunner {
    WorkflowRunner {
        meta: Meta::new(),
        provider,
    }
}
impl WorkflowRunner {
    pub fn handle(&self) -> Handle<WorkflowClient> {
        self.meta.handle()
    }
    pub fn label(mut self, name: impl Into<String>) -> Self {
        self.meta = self.meta.label(name);
        self
    }
}
fn model(ty: &ModelType) -> String {
    let value = match &ty.kind {
        ModelKind::Scalar(name) => match name.as_str() {
            "String" => "string",
            "Boolean" => "boolean",
            "Int" | "Float" => "number",
            _ => "unknown",
        }
        .into(),
        ModelKind::Enum(values) => values
            .iter()
            .map(|v| serde_json::to_string(v).unwrap())
            .collect::<Vec<_>>()
            .join(" | "),
        ModelKind::Object(fields) => fields_type(fields),
        ModelKind::List(item) => format!("Array<{}>", model(item)),
        _ => "unknown".into(),
    };
    if ty.nullable {
        format!("({value}) | null")
    } else {
        value
    }
}
fn fields_type(fields: &[ModelField]) -> String {
    format!(
        "{{ {} }}",
        fields
            .iter()
            .map(|field| format!(
                "{}{}: {};",
                serde_json::to_string(&field.name).unwrap(),
                if field.optional || field.default_value.is_some() {
                    "?"
                } else {
                    ""
                },
                model(&field.ty)
            ))
            .collect::<Vec<_>>()
            .join(" ")
    )
}
impl Plugin<TypeScript> for WorkflowRunner {
    fn kind(&self) -> &'static str {
        "typescript-workflow"
    }
    fn supports_native_input(&self) -> bool {
        true
    }
    fn meta(&self) -> &Meta {
        &self.meta
    }
    fn requires(&self) -> Vec<Requirement> {
        vec![Requirement::on(self.provider)]
    }
    fn provides(&self) -> Vec<Provision> {
        vec![Provision::of::<WorkflowClient>()]
    }
    fn generate(&self, cx: &mut PluginContext<'_, TypeScript>) -> Result<()> {
        let contract = cx.inputs.get::<WorkflowOperations>()?;
        ensure!(
            !contract.workflows.is_empty(),
            "workflow runner requires source-resolved workflows"
        );
        let mut out = String::from(
            "/** Generated by Poolster. */\nimport { executeWorkflow } from './workflow-runtime.js';\nimport type { WorkflowDefinition, WorkflowRunOptions, WorkflowExecution } from './workflow-runtime.js';\n",
        );
        writeln!(
            out,
            "const definitions = JSON.parse({}) as WorkflowDefinition[];",
            serde_json::to_string(&serde_json::to_string(&contract.workflows)?)?
        )?;
        let mut workflows = BTreeMap::new();
        let mut symbols = std::collections::HashSet::new();
        for item in &contract.workflows {
            // Encode UTF-8 bytes, avoiding collisions and reserved JS identifiers.
            let suffix = item
                .id
                .as_bytes()
                .iter()
                .map(|byte| format!("{byte:02x}"))
                .collect::<String>();
            let function = format!("runWorkflow_{suffix}");
            ensure!(
                symbols.insert(function.clone()),
                "duplicate workflow id {:?}",
                item.id
            );
            let ty = format!("WorkflowInputs_{suffix}");
            writeln!(out, "export type {ty} = {};", fields_type(&item.inputs))?;
            writeln!(
                out,
                "export function {function}(inputs: {ty}, options?: WorkflowRunOptions): Promise<WorkflowExecution> {{ return executeWorkflow(definitions, {}, inputs, options); }}",
                serde_json::to_string(&item.id)?
            )?;
            workflows.insert(
                item.id.clone(),
                crate::Symbol {
                    name: function,
                    module: "workflows".into(),
                },
            );
        }
        out.push_str("export function runWorkflow(workflowId: string, inputs: Record<string, unknown>, options?: WorkflowRunOptions): Promise<WorkflowExecution> { return executeWorkflow(definitions, workflowId, inputs, options); }\n");
        cx.files.emit(GeneratedFile::new("workflows.ts", out)?)?;
        cx.files.emit(GeneratedFile::new(
            "workflow-runtime.ts",
            include_str!("../templates/workflow_runtime.ts.tmpl"),
        )?)?;
        cx.workspace.export("workflows")?;
        cx.workspace.export("workflow-runtime")?;
        cx.workspace.package_file(GeneratedFile::new("package.json", serde_json::to_string_pretty(&serde_json::json!({"name":cx.settings.package_name.as_deref().unwrap_or("poolster-workflow-runner"),"version":cx.common.package_version.as_deref().unwrap_or("0.0.0"),"type":"module","main":"./dist/index.js","types":"./dist/index.d.ts","exports":{".":{"types":"./dist/index.d.ts","import":"./dist/index.js"}},"scripts":{"build":"tsc -p tsconfig.json"},"devDependencies":{"typescript":"5.9.3"}}))?)?)?;
        cx.workspace.package_file(GeneratedFile::new("tsconfig.json", "{\"compilerOptions\":{\"target\":\"ES2022\",\"module\":\"NodeNext\",\"moduleResolution\":\"NodeNext\",\"strict\":true,\"declaration\":true,\"outDir\":\"dist\",\"lib\":[\"ES2022\",\"DOM\"]},\"include\":[\"**/*.ts\"],\"exclude\":[\"dist\"]}\n")?)?;
        cx.publish(WorkflowClient {
            workflows,
            runtime_module: "workflow-runtime".into(),
        })
    }
}
