[package]
name = "poolster-plugin-symfony"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Symfony bundle generator for Poolster PHP SDKs"
publish = false

[dependencies]
anyhow = "1.0.102"
poolster-core = { path = "../../core" }
