[package]
name = "poolster-input-capnproto"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Native capnproto input provider for Poolster"
publish = ["crates-io"]

[dependencies]
poolster-core = { version = "0.5.0-alpha.1", path = "../../core" }
anyhow = "1.0.102"
capnp = "0.25"
