//! Structured TypeScript model generation.
//!
//! The structured target keeps model and operation type files separate so SDK
//! packages remain easy to navigate as an OpenAPI contract grows.

use std::collections::BTreeSet;
use std::fmt::Write;

use anyhow::Result;
use serde_json::Value;

use crate::ast::{AdditionalProperties, Api, Operation, SchemaKind, SchemaValue};
use crate::{CodegenPlugin, GeneratedFile, GeneratorConfig};

const NOTICE: &str = "/**\n * Generated by Kaji (https://kaji.dev/).\n * Do not edit manually.\n * Source: text content\n */\n\n";
const NOTICE_WITHOUT_SOURCE: &str =
    "/**\n * Generated by Kaji (https://kaji.dev/).\n * Do not edit manually.\n */\n\n";

/// Emits TypeScript model and operation type files for the structured SDK
/// target.
#[derive(Default)]
pub struct StructuredTypeScriptModels;

impl CodegenPlugin for StructuredTypeScriptModels {
    fn name(&self) -> &'static str {
        "structured-typescript-models"
    }

    fn generate(&self, api: &Api, config: &GeneratorConfig) -> Result<Vec<GeneratedFile>> {
        let output_dir = config
            .get("output_dir")
            .map(String::as_str)
            .unwrap_or("typescript")
            .trim_matches('/');
        // SDK package profiles may opt into separate
        // component and operation type directories, preventing an OpenAPI
        // component such as `CreateContact` from overwriting an equally named
        // operation type.
        let schema_output_dir = config
            .get("schema_output_dir")
            .map(String::as_str)
            .unwrap_or(output_dir)
            .trim_matches('/');
        let operation_output_dir = config
            .get("operation_output_dir")
            .map(String::as_str)
            .unwrap_or(output_dir)
            .trim_matches('/');
        let group_by_tag = matches!(
            config
                .get("group_type")
                .or_else(|| config.get("group.type"))
                .map(String::as_str),
            Some("tag")
        );
        let options = RenderOptions::from_config(config);
        let notice = generated_notice(api);
        let schemas = api.schemas.iter().map(|schema| {
            let file = format!("{}.ts", schema_file_identifier(&schema.name));
            let path = if schema_output_dir.is_empty() {
                file
            } else {
                format!("{schema_output_dir}/{file}")
            };
            GeneratedFile::new(
                path,
                render_schema(&schema.name, &schema.value, &options, &notice),
            )
        });
        let operations = api.operations.iter().map(|operation| {
            let file = format!("{}.ts", type_identifier(&operation.id));
            let group = group_by_tag.then(|| operation_tag_directory(operation));
            let directory = match group {
                Some(group) if operation_output_dir.is_empty() => group,
                Some(group) => format!("{operation_output_dir}/{group}"),
                None => operation_output_dir.to_owned(),
            };
            let path = if directory.is_empty() {
                file
            } else {
                format!("{directory}/{file}")
            };
            GeneratedFile::new(path, render_operation(operation, &options, &notice))
        });

        schemas.chain(operations).collect()
    }
}

fn operation_tag_directory(operation: &Operation) -> String {
    operation
        .annotations
        .get("tags")
        .and_then(Value::as_array)
        .and_then(|tags| tags.first())
        .and_then(Value::as_str)
        .map(lower_camel_identifier)
        .filter(|tag| !tag.is_empty())
        .unwrap_or_else(|| "default".into())
}

/// Formatting choices supported by the structured TypeScript generator.
/// Both snake_case and camelCase keys are accepted for ergonomic Rust and
/// JSON configuration.
#[derive(Clone)]
struct RenderOptions {
    array_type: ArrayType,
    optional_type: OptionalType,
    syntax: Syntax,
    enum_type: EnumType,
    enum_key_casing: EnumKeyCasing,
    enum_const_casing: EnumConstCasing,
    enum_type_suffix: String,
    integer_as_string: bool,
    remove_optional_properties: bool,
}

impl RenderOptions {
    fn from_config(config: &GeneratorConfig) -> Self {
        let array_type = match config
            .get("array_type")
            .or_else(|| config.get("arrayType"))
            .map(String::as_str)
        {
            Some("generic") => ArrayType::Generic,
            _ => ArrayType::Array,
        };
        let optional_type = match config
            .get("optional_type")
            .or_else(|| config.get("optionalType"))
            .map(String::as_str)
        {
            Some("questionTokenAndUndefined") => OptionalType::QuestionTokenAndUndefined,
            Some("undefined") => OptionalType::Undefined,
            _ => OptionalType::QuestionToken,
        };
        let syntax = match config
            .get("syntax_type")
            .or_else(|| config.get("syntaxType"))
            .map(String::as_str)
        {
            Some("interface") => Syntax::Interface,
            _ => Syntax::Type,
        };
        let enum_type = match config
            .get("enum_type")
            .or_else(|| config.get("enumType"))
            .map(String::as_str)
        {
            Some("asConst") => EnumType::AsConst,
            Some("enum") => EnumType::Enum,
            Some("constEnum") => EnumType::ConstEnum,
            _ => EnumType::Literal,
        };
        let enum_key_casing = match config
            .get("enum_key_casing")
            .or_else(|| config.get("enumKeyCasing"))
            .map(String::as_str)
        {
            Some("none") => EnumKeyCasing::None,
            Some("camelCase") => EnumKeyCasing::CamelCase,
            Some("pascalCase") => EnumKeyCasing::PascalCase,
            Some("snakeCase") => EnumKeyCasing::SnakeCase,
            Some("screamingSnakeCase") => EnumKeyCasing::ScreamingSnakeCase,
            _ => EnumKeyCasing::None,
        };
        let enum_const_casing = match config
            .get("enum_const_casing")
            .or_else(|| config.get("enumConstCasing"))
            .map(String::as_str)
        {
            Some("pascalCase") => EnumConstCasing::PascalCase,
            _ => EnumConstCasing::CamelCase,
        };
        let enum_type_suffix = config
            .get("enum_type_suffix")
            .or_else(|| config.get("enumTypeSuffix"))
            .map(|suffix| match suffix.as_str() {
                // Lower-case aliases are convenient in hand-written JSON.
                "key" => "Key".into(),
                "value" => "Value".into(),
                _ => suffix.clone(),
            })
            .unwrap_or_else(|| "Key".into());
        let transformers = config
            .get("transformers")
            .and_then(|value| serde_json::from_str::<Value>(value).ok())
            .and_then(|value| value.as_object().cloned());
        let integer_as_string = transformer_enabled(
            config,
            &transformers,
            &["integer_to_string", "integerToString"],
        );
        let remove_optional_properties = transformer_enabled(
            config,
            &transformers,
            &["remove_optional_properties", "removeOptionalProperties"],
        );
        Self {
            array_type,
            optional_type,
            syntax,
            enum_type,
            enum_key_casing,
            enum_const_casing,
            enum_type_suffix,
            integer_as_string,
            remove_optional_properties,
        }
    }
}

fn transformer_enabled(
    config: &GeneratorConfig,
    transformers: &Option<serde_json::Map<String, Value>>,
    names: &[&str],
) -> bool {
    names.iter().any(|name| {
        config.get(*name).is_some_and(|value| value == "true")
            || transformers
                .as_ref()
                .and_then(|transformers| transformers.get(*name))
                .and_then(Value::as_bool)
                .unwrap_or(false)
    })
}

#[derive(Clone, Copy)]
enum ArrayType {
    /// Kaji's default `array` setting, e.g. `string[]`.
    Array,
    /// Kaji's `generic` setting, e.g. `Array<string>`.
    Generic,
}

#[derive(Clone, Copy)]
enum OptionalType {
    /// Kaji's default: `name?: T`.
    QuestionToken,
    /// Kaji's `questionTokenAndUndefined`: `name?: T | undefined`.
    QuestionTokenAndUndefined,
    /// Kaji's `undefined`: `name: T | undefined`.
    Undefined,
}

#[derive(Clone, Copy)]
enum Syntax {
    Type,
    Interface,
}

#[derive(Clone, Copy)]
enum EnumType {
    Literal,
    AsConst,
    Enum,
    ConstEnum,
}

#[derive(Clone, Copy)]
enum EnumKeyCasing {
    None,
    CamelCase,
    PascalCase,
    SnakeCase,
    ScreamingSnakeCase,
}

#[derive(Clone, Copy)]
enum EnumConstCasing {
    CamelCase,
    PascalCase,
}

fn generated_notice(api: &Api) -> String {
    match api.annotations.get("source").and_then(Value::as_str) {
        Some("") => NOTICE_WITHOUT_SOURCE.into(),
        Some(source) => format!(
            "/**\n * Generated by Kaji (https://kaji.dev/).\n * Do not edit manually.\n * Source: {source}\n */\n\n"
        ),
        None => NOTICE.into(),
    }
}

fn render_schema(name: &str, value: &SchemaValue, options: &RenderOptions, notice: &str) -> String {
    let identifier = type_identifier(name);
    if !value.enum_values.is_empty() {
        return match options.enum_type {
            EnumType::Literal => format!(
                "{notice}export type {identifier} = {}\n",
                value
                    .enum_values
                    .iter()
                    .map(kaji_literal)
                    .collect::<Vec<_>>()
                    .join(" | ")
            ),
            EnumType::AsConst => {
                render_as_const_enum(&identifier, &value.enum_values, options, notice)
            }
            EnumType::Enum => render_named_enum(&identifier, &value.enum_values, options, notice),
            EnumType::ConstEnum => {
                render_const_enum(&identifier, &value.enum_values, options, notice)
            }
        };
    }
    if let (
        Syntax::Interface,
        SchemaKind::Object {
            fields,
            additional_properties,
        },
    ) = (options.syntax, &value.kind)
    {
        return format!(
            "{notice}export interface {identifier} {}\n",
            render_object(fields, additional_properties, options)
        );
    }
    let body = match &value.kind {
        SchemaKind::Object {
            fields,
            additional_properties,
        } => render_object(fields, additional_properties, options),
        _ => render_value(value, options),
    };
    format!("{notice}export type {identifier} = {body}\n")
}

fn render_as_const_enum(
    identifier: &str,
    values: &[Value],
    options: &RenderOptions,
    notice: &str,
) -> String {
    let value_name = match options.enum_const_casing {
        EnumConstCasing::CamelCase => lower_camel_identifier(identifier),
        EnumConstCasing::PascalCase => identifier.into(),
    };
    let mut source = format!("{notice}export const {value_name} = {{\n");
    for (index, value) in values.iter().enumerate() {
        let key = enum_member_name(identifier, value, index, options.enum_key_casing);
        let _ = writeln!(source, "  {key}: {},", kaji_literal(value));
    }
    source.push_str("} as const\n\n");
    source.push_str(&format!(
        "export type {identifier}{} = (typeof {value_name})[keyof typeof {value_name}]\n",
        options.enum_type_suffix
    ));
    source
}

fn render_named_enum(
    identifier: &str,
    values: &[Value],
    options: &RenderOptions,
    notice: &str,
) -> String {
    render_enum_declaration(identifier, values, "export enum", options, notice)
}

fn render_const_enum(
    identifier: &str,
    values: &[Value],
    options: &RenderOptions,
    notice: &str,
) -> String {
    render_enum_declaration(identifier, values, "export const enum", options, notice)
}

fn render_enum_declaration(
    identifier: &str,
    values: &[Value],
    declaration: &str,
    options: &RenderOptions,
    notice: &str,
) -> String {
    let mut source = format!("{notice}{declaration} {identifier} {{\n");
    for (index, value) in values.iter().enumerate() {
        let key = enum_member_name(identifier, value, index, options.enum_key_casing);
        let _ = writeln!(source, "  {key} = {},", kaji_literal(value));
    }
    source.push_str("}\n");
    source
}

fn enum_member_name(
    identifier: &str,
    value: &Value,
    index: usize,
    casing: EnumKeyCasing,
) -> String {
    let Some(value) = value.as_str() else {
        return match casing {
            EnumKeyCasing::None => format!("{identifier}_{}", index + 1),
            EnumKeyCasing::CamelCase => {
                format!("{}{}", lower_camel_identifier(identifier), index + 1)
            }
            EnumKeyCasing::PascalCase => format!("{identifier}{}", index + 1),
            EnumKeyCasing::SnakeCase => {
                format!("{}_{}", identifier.to_ascii_lowercase(), index + 1)
            }
            EnumKeyCasing::ScreamingSnakeCase => {
                format!("{}_{}", identifier.to_ascii_uppercase(), index + 1)
            }
        };
    };
    if matches!(casing, EnumKeyCasing::None) {
        return property_name(value);
    }
    let words = value
        .split(|character: char| !character.is_ascii_alphanumeric())
        .filter(|word| !word.is_empty())
        .map(|word| word.to_ascii_lowercase())
        .collect::<Vec<_>>();
    if words.is_empty() {
        return property_name(value);
    }
    let name = match casing {
        EnumKeyCasing::None => unreachable!("handled above"),
        EnumKeyCasing::CamelCase => words
            .iter()
            .enumerate()
            .map(|(index, word)| {
                if index == 0 {
                    word.clone()
                } else {
                    upper_camel_word(word)
                }
            })
            .collect(),
        EnumKeyCasing::PascalCase => words.iter().map(|word| upper_camel_word(word)).collect(),
        EnumKeyCasing::SnakeCase => words.join("_"),
        EnumKeyCasing::ScreamingSnakeCase => words.join("_").to_ascii_uppercase(),
    };
    property_name(&name)
}

fn upper_camel_word(word: &str) -> String {
    let mut characters = word.chars();
    match characters.next() {
        Some(first) => first.to_uppercase().collect::<String>() + characters.as_str(),
        None => String::new(),
    }
}

fn render_object_fields(fields: &[crate::ast::Field], options: &RenderOptions) -> String {
    render_object(fields, &AdditionalProperties::Unspecified, options)
}

/// Kaji's TypeScript printer turns OpenAPI `readOnly` into a property modifier
/// and collapses `additionalProperties` into one string index signature. An
/// index signature alongside named properties must be `unknown` because each
/// declared property has to be assignable to it in TypeScript.
fn render_object(
    fields: &[crate::ast::Field],
    additional_properties: &AdditionalProperties,
    options: &RenderOptions,
) -> String {
    if fields.is_empty()
        && matches!(
            additional_properties,
            AdditionalProperties::Unspecified | AdditionalProperties::Forbidden
        )
    {
        return "object".into();
    }
    let mut object = String::from("{\n");
    for field in fields {
        if options.remove_optional_properties && !field.required {
            continue;
        }
        let optional = optional_marker(field.required, options.optional_type);
        let read_only = field.value.read_only
            || field
                .annotations
                .get("readOnly")
                .and_then(Value::as_bool)
                .unwrap_or(false);
        let _ = writeln!(
            object,
            "  {}{}{}: {}",
            if read_only { "readonly " } else { "" },
            property_name(&field.name),
            optional,
            render_optional_value(&field.value, field.required, options)
        );
    }
    let index_value = match additional_properties {
        AdditionalProperties::Any => Some("unknown".into()),
        AdditionalProperties::Schema { value } if fields.is_empty() => {
            Some(render_value(value, options))
        }
        AdditionalProperties::Schema { .. } if !fields.is_empty() => Some("unknown".into()),
        AdditionalProperties::Unspecified | AdditionalProperties::Forbidden => None,
        AdditionalProperties::Schema { .. } => unreachable!("fields emptiness is exhaustive"),
    };
    if let Some(index_value) = index_value {
        let _ = writeln!(object, "  [key: string]: {index_value}");
    }
    object.push('}');
    object
}

fn render_operation(operation: &Operation, options: &RenderOptions, notice: &str) -> String {
    struct MediaResponse {
        content_type: String,
        value: String,
        description: Option<String>,
        doc_type: Option<String>,
    }

    struct ResponseType {
        status: String,
        name: String,
        media: Vec<MediaResponse>,
    }

    let identifier = type_identifier(&operation.id);
    let mut inline_enums = Vec::new();
    let mut inline_enum_names = BTreeSet::new();
    for response in &operation.responses {
        for media in &response.media_types {
            if let Some(schema) = &media.schema {
                collect_inline_enums(schema, options, &mut inline_enum_names, &mut inline_enums);
            }
        }
    }
    if let Some(body) = &operation.request_body {
        for media in &body.media_types {
            if let Some(schema) = &media.schema {
                collect_inline_enums(schema, options, &mut inline_enum_names, &mut inline_enums);
            }
        }
    }
    let parameter_groups = [("path", "Path"), ("query", "Query"), ("header", "Headers")]
        .into_iter()
        .filter_map(|(location, suffix)| {
            // Kaji keeps the first occurrence of an exactly duplicated
            // `(in, name)` parameter, while distinct casing variants remain
            // separate OpenAPI properties.
            let mut names = BTreeSet::new();
            let parameters = operation
                .parameters
                .iter()
                .filter(|parameter| {
                    parameter.location == location && names.insert(parameter.name.as_str())
                })
                .collect::<Vec<_>>();
            (!parameters.is_empty()).then_some((suffix, parameters))
        })
        .collect::<Vec<_>>();
    let response_types = operation
        .responses
        .iter()
        .map(|response| {
            let name = format!("{identifier}Status{}", type_identifier(&response.status));
            let media = response
                .media_types
                .iter()
                .map(|media| MediaResponse {
                    content_type: media.content_type.clone(),
                    value: media
                        .schema
                        .as_ref()
                        .map(|schema| render_operation_value(schema, options))
                        .unwrap_or_else(|| "void".into()),
                    description: None,
                    doc_type: None,
                })
                .collect();
            ResponseType {
                status: response.status.clone(),
                name,
                media,
            }
        })
        .collect::<Vec<_>>();
    let body_media = operation
        .request_body
        .as_ref()
        .map(|body| {
            body.media_types
                .iter()
                .map(|media| MediaResponse {
                    content_type: media.content_type.clone(),
                    value: media
                        .schema
                        .as_ref()
                        .map(|schema| render_operation_value(schema, options))
                        .unwrap_or_else(|| "unknown".into()),
                    description: media
                        .schema
                        .as_ref()
                        .and_then(|schema| schema.description.clone()),
                    doc_type: media.schema.as_ref().map(schema_doc_type),
                })
                .collect::<Vec<_>>()
        })
        .unwrap_or_default();

    let mut source = String::from(notice);
    for inline_enum in inline_enums {
        source.push_str(&inline_enum);
        source.push('\n');
    }
    for (suffix, parameters) in &parameter_groups {
        let _ = writeln!(source, "export type {identifier}{suffix} = {{");
        for parameter in parameters {
            let optional = if parameter.required { "" } else { "?" };
            let value = parameter
                .schema
                .as_ref()
                .map(|schema| render_operation_value(schema, options))
                .unwrap_or_else(|| "unknown".into());
            let _ = writeln!(
                source,
                "  {}{optional}: {value}",
                property_name(&parameter.name)
            );
        }
        source.push_str("}\n\n");
    }
    for response in &response_types {
        if response.media.len() > 1 {
            let media_names = response
                .media
                .iter()
                .map(|media| {
                    let name = format!(
                        "{}{}",
                        response.name,
                        media_type_identifier(&media.content_type)
                    );
                    let _ = writeln!(source, "export type {name} = {}\n", media.value);
                    name
                })
                .collect::<Vec<_>>();
            let _ = writeln!(
                source,
                "export type {} = {}\n",
                response.name,
                media_names.join(" | ")
            );
        } else {
            let value = response
                .media
                .first()
                .map(|media| media.value.as_str())
                .unwrap_or("void");
            let _ = writeln!(source, "export type {} = {value}\n", response.name);
        }
    }
    if body_media.len() > 1 {
        let media_names = body_media
            .iter()
            .map(|media| {
                let name = format!(
                    "{identifier}Body{}",
                    media_type_identifier(&media.content_type)
                );
                let _ = writeln!(source, "export type {name} = {}\n", media.value);
                name
            })
            .collect::<Vec<_>>();
        let _ = writeln!(
            source,
            "export type {identifier}Body = {}\n",
            media_names.join(" | ")
        );
    } else if let Some(body) = body_media.first() {
        if let (Some(description), Some(doc_type)) = (&body.description, &body.doc_type) {
            let _ = writeln!(
                source,
                "/**\n * @description {description}\n * @type {doc_type}\n */"
            );
        }
        let _ = writeln!(source, "export type {identifier}Body = {}\n", body.value);
    }
    source.push_str(&format!("export type {identifier}Options = {{\n"));
    if !body_media.is_empty() {
        source.push_str(&format!("  body: {identifier}Body\n"));
    } else {
        source.push_str("  body?: never\n");
    }
    for (location, suffix, property) in [
        ("path", "Path", "path"),
        ("query", "Query", "query"),
        ("header", "Headers", "headers"),
    ] {
        if parameter_groups
            .iter()
            .any(|(group_suffix, _)| *group_suffix == suffix)
        {
            let required = operation
                .parameters
                .iter()
                .any(|parameter| parameter.location == location && parameter.required);
            let optional = if required { "" } else { "?" };
            source.push_str(&format!("  {property}{optional}: {identifier}{suffix}\n"));
        } else if location == "header" {
            source.push_str("  headers?: never\n");
        } else {
            source.push_str(&format!("  {location}?: never\n"));
        }
    }
    source.push_str("}\n\n");
    source.push_str(&format!("export type {identifier}Responses = {{\n"));
    for response in &response_types {
        if response.media.len() > 1 {
            let _ = writeln!(source, "  {}:", response_status_key(&response.status));
            for media in &response.media {
                let media_name = format!(
                    "{}{}",
                    response.name,
                    media_type_identifier(&media.content_type)
                );
                let _ = writeln!(
                    source,
                    "    | {{\n        contentType: {}\n        data: {media_name}\n      }}",
                    kaji_literal(&Value::String(media.content_type.clone()))
                );
            }
        } else {
            let _ = writeln!(
                source,
                "  {}: {}",
                response_status_key(&response.status),
                response.name
            );
        }
    }
    source.push_str("}\n\n/**\n * @description Union of all possible responses\n */\n");
    let response = response_types
        .iter()
        .map(|response| response.name.as_str())
        .collect::<Vec<_>>()
        .join(" | ");
    source.push_str(&format!("export type {identifier}Response = {response}\n"));
    source
}

/// Inline OpenAPI schemas can retain Kaji's resolved AST name in a safe
/// extension. When present, Kaji emits their enum declaration before the
/// operation model and fields refer to that generated alias.
fn inline_enum_name(value: &SchemaValue) -> Option<&str> {
    value
        .extensions
        .get("kaji_name")
        .or_else(|| value.extensions.get("x-kaji-name"))
        .and_then(Value::as_str)
        .filter(|name| !name.is_empty())
}

fn collect_inline_enums(
    value: &SchemaValue,
    options: &RenderOptions,
    names: &mut BTreeSet<String>,
    declarations: &mut Vec<String>,
) {
    if !value.enum_values.is_empty()
        && let Some(name) = inline_enum_name(value)
        && names.insert(name.into())
    {
        let declaration = match options.enum_type {
            EnumType::Literal => String::new(),
            EnumType::AsConst => render_as_const_enum(name, &value.enum_values, options, ""),
            EnumType::Enum => render_named_enum(name, &value.enum_values, options, ""),
            EnumType::ConstEnum => render_const_enum(name, &value.enum_values, options, ""),
        };
        if !declaration.is_empty() {
            declarations.push(declaration);
        }
    }

    match &value.kind {
        SchemaKind::Array { items } => collect_inline_enums(items, options, names, declarations),
        SchemaKind::Object {
            fields,
            additional_properties,
        } => {
            for field in fields {
                collect_inline_enums(&field.value, options, names, declarations);
            }
            if let AdditionalProperties::Schema { value } = additional_properties {
                collect_inline_enums(value, options, names, declarations);
            }
        }
        SchemaKind::OneOf { variants }
        | SchemaKind::AnyOf { variants }
        | SchemaKind::AllOf { variants } => {
            for variant in variants {
                collect_inline_enums(variant, options, names, declarations);
            }
        }
        SchemaKind::Any
        | SchemaKind::Null
        | SchemaKind::Boolean
        | SchemaKind::Integer
        | SchemaKind::Number
        | SchemaKind::String
        | SchemaKind::Reference { .. }
        | SchemaKind::Not { .. } => {}
    }
}

fn schema_doc_type(schema: &SchemaValue) -> String {
    match &schema.kind {
        SchemaKind::Object { .. } => "object",
        SchemaKind::Array { .. } => "array",
        SchemaKind::String => "string",
        SchemaKind::Boolean => "boolean",
        SchemaKind::Integer | SchemaKind::Number => "number",
        SchemaKind::Null => "null",
        SchemaKind::Any | SchemaKind::Not { .. } => "unknown",
        SchemaKind::Reference { .. }
        | SchemaKind::OneOf { .. }
        | SchemaKind::AnyOf { .. }
        | SchemaKind::AllOf { .. } => "object",
    }
    .into()
}

fn response_status_key(status: &str) -> String {
    if status == "default" {
        "default".into()
    } else {
        kaji_literal(&Value::String(status.into()))
    }
}

fn render_operation_value(value: &SchemaValue, options: &RenderOptions) -> String {
    match &value.kind {
        SchemaKind::Object { fields, .. } if fields.is_empty() => "object".into(),
        SchemaKind::Object { fields, .. } => render_object_fields(fields, options),
        _ => render_value(value, options),
    }
}

fn media_type_identifier(content_type: &str) -> String {
    match content_type {
        "application/json" => return "Json".into(),
        "application/xml" | "text/xml" => return "Xml".into(),
        "multipart/form-data" => return "FormData".into(),
        _ => {}
    }
    content_type
        .split(|character: char| !character.is_ascii_alphanumeric())
        .filter(|part| !part.is_empty())
        .map(type_identifier)
        .collect::<String>()
}

fn render_optional_value(value: &SchemaValue, required: bool, options: &RenderOptions) -> String {
    let rendered = render_value(value, options);
    if !required
        && matches!(
            options.optional_type,
            OptionalType::QuestionTokenAndUndefined | OptionalType::Undefined
        )
    {
        format!("{rendered} | undefined")
    } else {
        rendered
    }
}

fn optional_marker(required: bool, optional_type: OptionalType) -> &'static str {
    if required || matches!(optional_type, OptionalType::Undefined) {
        ""
    } else {
        "?"
    }
}

fn render_value(value: &SchemaValue, options: &RenderOptions) -> String {
    let body = if let Some(constant) = value.const_value.as_ref() {
        kaji_literal(constant)
    } else {
        match &value.kind {
            SchemaKind::Any | SchemaKind::Not { .. } => "unknown".into(),
            SchemaKind::Null => "null".into(),
            SchemaKind::Boolean => "boolean".into(),
            SchemaKind::Integer if options.integer_as_string => "string".into(),
            SchemaKind::Integer | SchemaKind::Number => "number".into(),
            SchemaKind::String => "string".into(),
            SchemaKind::Array { items } => match options.array_type {
                ArrayType::Array => format!("{}[]", render_value(items, options)),
                ArrayType::Generic => format!("Array<{}>", render_value(items, options)),
            },
            SchemaKind::Reference { reference } => {
                type_identifier(reference.rsplit('/').next().unwrap_or(reference))
            }
            SchemaKind::OneOf { variants } | SchemaKind::AnyOf { variants } => variants
                .iter()
                .map(|variant| render_value(variant, options))
                .collect::<Vec<_>>()
                .join(" | "),
            SchemaKind::AllOf { variants } => variants
                .iter()
                .map(|variant| render_value(variant, options))
                .collect::<Vec<_>>()
                .join(" & "),
            SchemaKind::Object {
                fields,
                additional_properties,
            } => render_object(fields, additional_properties, options),
        }
    };
    let body = if !value.enum_values.is_empty() {
        if let Some(name) = inline_enum_name(value) {
            match options.enum_type {
                EnumType::AsConst => format!("{name}{}", options.enum_type_suffix),
                EnumType::Enum | EnumType::ConstEnum => name.into(),
                EnumType::Literal => value
                    .enum_values
                    .iter()
                    .map(kaji_literal)
                    .collect::<Vec<_>>()
                    .join(" | "),
            }
        } else {
            value
                .enum_values
                .iter()
                .map(kaji_literal)
                .collect::<Vec<_>>()
                .join(" | ")
        }
    } else {
        body
    };
    if value.nullable && body != "null" {
        format!("{body} | null")
    } else {
        body
    }
}

fn kaji_literal(value: &Value) -> String {
    match value {
        Value::String(value) => format!("'{}'", value.replace('\\', "\\\\").replace('\'', "\\'")),
        _ => serde_json::to_string(value).unwrap_or_else(|_| "unknown".into()),
    }
}

fn property_name(value: &str) -> String {
    if value
        .chars()
        .next()
        .is_some_and(|first| first.is_ascii_alphabetic() || first == '_' || first == '$')
        && value.chars().all(|character| {
            character.is_ascii_alphanumeric() || character == '_' || character == '$'
        })
    {
        value.into()
    } else {
        kaji_literal(&Value::String(value.into()))
    }
}

/// Kaji resolves a dotted schema name into a nested namespace but writes the
/// terminal segment as the source filename (for example `enumNames.Type`
/// becomes `Type.ts` while its declaration remains `EnumNamesType`).
fn schema_file_identifier(value: &str) -> String {
    type_identifier(value.rsplit('.').next().unwrap_or(value))
}

fn type_identifier(value: &str) -> String {
    let mut output = String::new();
    let mut uppercase = true;
    for character in value.chars() {
        if character.is_ascii_alphanumeric() {
            if uppercase {
                output.extend(character.to_uppercase());
            } else {
                output.push(character);
            }
            uppercase = false;
        } else {
            uppercase = true;
        }
    }
    if output.is_empty() {
        "Type".into()
    } else {
        output
    }
}

fn lower_camel_identifier(value: &str) -> String {
    let pascal = type_identifier(value);
    let mut characters = pascal.chars();
    match characters.next() {
        Some(first) => first.to_lowercase().collect::<String>() + characters.as_str(),
        None => "type".into(),
    }
}
