//! GraphQL model, operation and facade source plan.
use super::*;

pub(super) fn render_capabilities(
    contract: &GraphqlOperations,
    module: &str,
    style: GraphqlStyle,
    groups: &BTreeMap<String, BTreeMap<String, String>>,
    subscriptions: bool,
    mappings: &BTreeMap<String, GraphqlScalarMapping>,
    incremental: Option<&GraphqlIncrementalOperations>,
) -> Result<(BTreeMap<String, String>, BTreeMap<String, String>)> {
    ensure!(
        !module.is_empty()
            && module
                .chars()
                .all(|c| c.is_ascii_alphanumeric() || "._/-".contains(c))
            && !module.contains(".."),
        "invalid Go module name"
    );
    ensure!(
        !contract.operations.is_empty(),
        "Go GraphQL generation requires operations"
    );
    let package = crate::go_package_name(module.rsplit('/').next().unwrap_or(module));
    ensure!(!package.is_empty(), "invalid Go package name");
    let mut source = format!("// Code generated by Poolster. DO NOT EDIT.\npackage {package}\n");
    source.push_str(include_str!("runtime.go.tmpl"));
    let header = format!("// Code generated by Poolster. DO NOT EDIT.\npackage {package}\n");
    let runtime = include_str!("runtime.go.tmpl");
    let declarations_start = runtime.find("// Optional").unwrap();
    let client_start = runtime.find("type Client struct").unwrap();
    let transport_start = runtime.find("func execute[").unwrap();
    let mut files = BTreeMap::new();
    files.insert(
        "graphql_runtime.go".into(),
        header.clone()
            + "import (\"encoding/json\";\"fmt\")\n"
            + &runtime[declarations_start..client_start],
    );
    files.insert(
        "graphql_client.go".into(),
        header.clone() + "import \"net/http\"\n" + &runtime[client_start..transport_start],
    );
    files.insert(
        "graphql_transport.go".into(),
        header.clone() + &runtime[..declarations_start] + &runtime[transport_start..],
    );
    files.insert(
        "graphql_codecs.go".into(),
        header.clone() + include_str!("codecs.go.tmpl"),
    );
    files.insert(
        "graphql_sse.go".into(),
        header.clone() + include_str!("sse.go.tmpl"),
    );
    files.insert(
        "graphql_incremental.go".into(),
        header.clone() + include_str!("incremental.go.tmpl"),
    );
    files.insert(
        "graphql_shapes.go".into(),
        header.clone() + "var graphqlInputShapes = map[string]*graphqlScalarShape{}\n",
    );
    // Each input has its own declaration. A registry of unrelated inputs is not
    // atomic: splitting it keeps large schemas within the per-file budget.
    for (name, fields) in &contract.input_objects {
        let shape = serde_json::to_string(&graphql_scalar_fields(fields))?;
        files.insert(
            filename("input_shape", name),
            header.clone()
                + &format!(
                    "func init() {{\n\tgraphqlInputShapes[{name:?}] = parseScalarShape({shape:?})\n}}\n"
                ),
        );
    }
    let mut models = models::Models::default();
    models.mappings = mappings.clone();
    for (name, fields) in &contract.input_objects {
        models.object(&ident(name), fields, true)?;
    }
    let mut symbols = BTreeMap::new();
    for op in &contract.operations {
        ensure!(
            op.kind != GraphqlOperationKind::Subscription
                || (subscriptions && incremental.is_none()),
            "Go GraphQL subscriptions require .subscriptions(); incremental subscriptions are unsupported"
        );
        let name = ident(&op.name);
        ensure!(
            !symbols.values().any(|v| v == &name),
            "GraphQL operation naming collision: {name}"
        );
        ensure!(
            !["Execute", "Query", "Mutation"].contains(&name.as_str()),
            "GraphQL operation conflicts with reserved client method {name}"
        );
        models.object(&format!("{name}Variables"), &op.variables, true)?;
        models.named_type(&format!("{name}Result"), &op.result, false)?;
        symbols.insert(op.name.clone(), name.clone());
        let document = serde_json::to_string(&op.document)?;
        let operation = serde_json::to_string(&op.name)?;
        let operation_start = source.len();
        let input_shape = serde_json::to_string(&graphql_scalar_fields(&op.variables))?;
        let result_shape = serde_json::to_string(&graphql_scalar_shape(&op.result))?;
        let response = if incremental.is_some() {
            format!("IncrementalStream[{name}Result]")
        } else if op.kind == GraphqlOperationKind::Subscription {
            format!("Subscription[{name}Result]")
        } else {
            format!("GraphQLResponse[{name}Result]")
        };
        let execute = if incremental.is_some() {
            "incrementalExecute"
        } else if op.kind == GraphqlOperationKind::Subscription {
            "subscribe"
        } else {
            "executeShaped"
        };
        let selections = incremental.and_then(|value| value.selections.get(&op.name));
        let extra = if incremental.is_some() {
            format!(
                ", {}",
                serde_json::to_string(&serde_json::to_string(&selections)?)?
            )
        } else {
            String::new()
        };
        writeln!(source,"const {name}Document = {document}\nvar {name}InputShape = parseScalarShape({input_shape:?})\nvar {name}ResultShape = parseScalarShape({result_shape:?})\nfunc {name}(ctx context.Context, client *Client, variables {name}Variables) (*{response}, error) {{\n\treturn {execute}[{name}Result](\n\t\tctx, client, {operation}, {name}Document, variables,\n\t\t{name}InputShape, {name}ResultShape{extra},\n\t)\n}}\n").unwrap();
        if style == GraphqlStyle::Flat {
            writeln!(source,"func (c *Client) {name}(ctx context.Context, variables {name}Variables) (*{response}, error) {{\n\treturn {name}(ctx, c, variables)\n}}\n").unwrap();
        }
        files.insert(
            filename("operation", &name),
            header.clone() + "import \"context\"\n" + &source[operation_start..],
        );
    }
    if style == GraphqlStyle::Idiomatic {
        let mut groups = groups.clone();
        if groups.is_empty() {
            for op in &contract.operations {
                let group = match op.kind {
                    GraphqlOperationKind::Query => "Query",
                    GraphqlOperationKind::Mutation => "Mutation",
                    GraphqlOperationKind::Subscription => "Subscription",
                };
                groups
                    .entry(group.into())
                    .or_default()
                    .insert(op.name.clone(), op.name.clone());
            }
        }
        let mut group_names = std::collections::BTreeSet::new();
        for (group, methods) in groups {
            let group = ident(&group);
            ensure!(
                group_names.insert(group.clone()),
                "GraphQL group naming collision"
            );
            ensure!(
                group != "Execute",
                "GraphQL group conflicts with client method"
            );
            let group_start = source.len();
            writeln!(source,"type {group}Client struct {{\n\tclient *Client\n}}\n\nfunc (c *Client) {group}() *{group}Client {{\n\treturn &{group}Client{{client: c}}\n}}").unwrap();
            files.insert(
                filename("group", &group),
                header.clone() + &source[group_start..],
            );
            let mut names = std::collections::BTreeSet::new();
            for (method, operation) in methods {
                let method = ident(&method);
                ensure!(
                    names.insert(method.clone()),
                    "GraphQL method naming collision"
                );
                let name = symbols
                    .get(&operation)
                    .ok_or_else(|| anyhow::anyhow!("unknown GraphQL operation {operation}"))?;
                let method_start = source.len();
                let kind = contract
                    .operations
                    .iter()
                    .find(|op| op.name == operation)
                    .unwrap()
                    .kind;
                let response = if incremental.is_some() {
                    format!("IncrementalStream[{name}Result]")
                } else if kind == GraphqlOperationKind::Subscription {
                    format!("Subscription[{name}Result]")
                } else {
                    format!("GraphQLResponse[{name}Result]")
                };
                writeln!(source,"func (g *{group}Client) {method}(ctx context.Context, variables {name}Variables) (*{response}, error) {{\n\treturn {name}(ctx, g.client, variables)\n}}\n").unwrap();
                files.insert(
                    filename("group_method", &serde_json::to_string(&(&group, &method))?),
                    header.clone() + "import \"context\"\n" + &source[method_start..],
                );
            }
        }
    } else {
        ensure!(
            groups.is_empty(),
            "GraphQL custom groups require idiomatic style"
        );
    }
    source.push_str(&models.source);
    let mut declarations = std::collections::BTreeSet::new();
    for line in source.lines() {
        let Some(rest) = line
            .strip_prefix("type ")
            .or_else(|| line.strip_prefix("const "))
            .or_else(|| line.strip_prefix("func "))
        else {
            continue;
        };
        if rest.starts_with('(') {
            continue;
        }
        let name = rest.split([' ', '[', '(']).next().unwrap_or_default();
        ensure!(
            declarations.insert(name.to_string()),
            "GraphQL generated declaration collision: {name}"
        );
    }
    for (path, body) in models.files {
        let imports = [
            ("encoding/json", "json."),
            ("fmt", "fmt."),
            ("time", "time."),
        ]
        .into_iter()
        .filter(|(_, needle)| body.contains(needle))
        .map(|(package, _)| format!("{package:?}"))
        .collect::<Vec<_>>();
        let imports = if imports.is_empty() {
            String::new()
        } else {
            format!("import (\n\t{}\n)\n\n", imports.join("\n\t"))
        };
        files.insert(path, header.clone() + &imports + &body);
    }
    let oversized=files.iter().filter(|(_,body)|body.len()>128*1024).map(|(path,body)|serde_json::json!({"path":path,"bytes":body.len(),"max_file_bytes":128*1024,"reason":"Atomic Go GraphQL declaration exceeds the source grouping budget; source retained intact."})).collect::<Vec<_>>();
    if !oversized.is_empty() {
        files.insert(
            ".poolster/source-layout-diagnostics.json".into(),
            serde_json::to_string_pretty(&oversized)?,
        );
    }
    Ok((files, symbols))
}
