[package]
name = "poolster-input-graphql"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Native graphql input provider for Poolster"
publish = false

[dependencies]
poolster-core = { path = "../../kaji-core" }
anyhow = "1.0.102"
apollo-compiler = "1.32"

[dev-dependencies]
tempfile = "3.27.0"
