//! Java 17+ SDK generation for Poolster.
//!
//! This plugin consumes Poolster's neutral [`Api`] AST and emits a self-contained,
//! build-tool-agnostic Java package. The generated runtime deliberately uses
//! the JDK's `java.net.http.HttpClient`; Jackson is the only runtime dependency
//! and handles generated records, JSON bodies, and typed responses.

#[cfg(test)]
mod model_compat_tests;
mod models;
mod multipart;
mod naming;
mod native_names;
mod operation_samples;
mod operation_tests;
mod operations;
mod pagination;
mod presence;
mod resources;
mod runtime;
mod surface;
#[cfg(test)]
use models::render_model;
use models::render_model_parts;
use naming::*;
pub use operation_tests::{OperationTests, operation_tests};
#[cfg(test)]
use operations::render_operation;
use operations::{render_client_facade, render_operation_chunk};
pub use package::NativeSdk;
use pagination::{java_pagination, render_pagination_operation};
use resources::{
    render_resource_chunk, render_resource_facade, resource_accessor_name, resource_operations,
};
use runtime::*;
use surface::*;
#[cfg(test)]
mod call_options_tests;
mod oauth;
pub use oauth::{OAuth, oauth};
mod webhooks;
use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write;
pub use webhooks::{Webhooks, webhooks};

use anyhow::{Result, bail};
use poolster_core::{
    AdditionalProperties, Api, Field, GeneratedFile, GeneratedTree, Operation, OperationParameter,
    OperationResponse, Schema, SchemaKind, SchemaValue, SdkClientStyle,
};
use serde_json::Value;

const NOTICE: &str = "// Generated by Poolster. Do not edit.\n";
/// Keeps even unusually verbose OpenAPI operations near a comfortably
/// navigable source-file size on very large API descriptions.
const OPERATIONS_PER_FILE: usize = 64;

/// Generates a Java 17+ SDK below `output_dir`.
///
/// `package_name` is a Java package name, such as `com.poolster.email`. When
/// absent, one is deterministically derived under `io.poolster`. The returned
/// tree is not written automatically, allowing profiles to compose multiple
/// language targets safely before materializing them.
#[cfg(test)]
fn render_test_sdk(
    api: &Api,
    output_dir: &str,
    package_name: Option<&str>,
) -> Result<GeneratedTree> {
    render_sdk(api, output_dir, package_name, SdkClientStyle::Flat)
}

/// Generates a Java 17+ SDK with either the original direct-operation client
/// or a resource-namespaced facade. In namespaced mode the direct operations
/// remain available as direct entry points.
#[cfg(test)]
fn render_sdk(
    api: &Api,
    output_dir: &str,
    package_name: Option<&str>,
    style: SdkClientStyle,
) -> Result<GeneratedTree> {
    render_sdk_with_policy(api, output_dir, package_name, style, false)
}

fn render_sdk_with_policy(
    api: &Api,
    output_dir: &str,
    package_name: Option<&str>,
    style: SdkClientStyle,
    open_enums: bool,
) -> Result<GeneratedTree> {
    let prepared = prepare_api(api);
    let api = &prepared;
    multipart::validate(api)?;

    for operation in &api.operations {
        let extension = poolster_core::poolster_extension(&operation.annotations, "pagination")
            .or_else(|| operation.annotations.get("x-speakeasy-pagination"));
        if extension
            .and_then(|extension| extension.get("type"))
            .and_then(Value::as_str)
            == Some("page")
        {
            poolster_core::pagination::normalize_pagination(api, operation, None)?;
        }
    }
    let root = normalized_output_dir(output_dir)?;
    let package = package_name
        .filter(|name| !name.trim().is_empty())
        .map(java_package_name)
        .unwrap_or_else(|| format!("io.poolster.{}", package_segment(&api.name)));
    if package.is_empty() {
        bail!("a Java package name could not be derived from the API name");
    }
    let package_path = package.replace('.', "/");
    let artifact = format!("{}-sdk", package_segment(&api.name));
    let version = package_version(&api.version);
    let mut tree = GeneratedTree::default();

    insert(
        &mut tree,
        &root,
        "settings.gradle",
        settings_gradle(&artifact),
    )?;
    insert(
        &mut tree,
        &root,
        "build.gradle",
        build_gradle(&package, &artifact, &version),
    )?;
    insert(
        &mut tree,
        &root,
        "pom.xml",
        pom_xml(&package, &artifact, &version),
    )?;
    insert(
        &mut tree,
        &root,
        "README.md",
        readme(api, &package, &artifact, style),
    )?;
    insert(
        &mut tree,
        &root,
        "STYLE_GUIDE.md",
        style_guide(api, &package, style),
    )?;
    insert(
        &mut tree,
        &root,
        &format!("src/main/java/{package_path}/ApiException.java"),
        api_exception(&package),
    )?;
    insert(
        &mut tree,
        &root,
        &format!("src/main/java/{package_path}/ClientConfig.java"),
        client_config(&package),
    )?;
    insert(
        &mut tree,
        &root,
        &format!("src/main/java/{package_path}/RetryConfig.java"),
        retry_config(&package),
    )?;
    insert(
        &mut tree,
        &root,
        &format!("src/main/java/{package_path}/ClientHooks.java"),
        client_hooks(&package),
    )?;
    insert(
        &mut tree,
        &root,
        &format!("src/main/java/{package_path}/ClientCallOptions.java"),
        include_str!("call_options.java.txt").replace("__PACKAGE__", &package),
    )?;
    multipart::emit(api, &root, &package, &mut tree)?;
    for (index, schema) in api.schemas.iter().enumerate() {
        for (filename, source) in render_model_parts(schema, &package, open_enums, index)? {
            insert(
                &mut tree,
                &root,
                &format!("src/main/java/{package_path}/model/{filename}"),
                source,
            )?;
        }
    }
    insert(
        &mut tree,
        &root,
        &format!("src/main/java/{package_path}/ClientBase.java"),
        render_client_base(api, &package),
    )?;
    let operation_overhead = render_operation_chunk(api, &[], &package, 0).len() + 64;
    let units = api
        .operations
        .iter()
        .map(|operation| poolster_core::source_layout::SourceUnit {
            bytes: render_operation_chunk(api, std::slice::from_ref(operation), &package, 0)
                .len()
                .saturating_sub(operation_overhead - 64),
            resource: None,
        })
        .collect::<Vec<_>>();
    let groups = poolster_core::source_layout::SourceLayout::Chunked {
        max_file_bytes: 128 * 1024,
        max_declarations: Some(OPERATIONS_PER_FILE),
    }
    .groups(&units, operation_overhead)?;
    let operation_chunks = groups
        .iter()
        .map(|indices| {
            indices
                .iter()
                .map(|index| api.operations[*index].clone())
                .collect::<Vec<_>>()
        })
        .collect::<Vec<_>>();
    for (index, operations) in operation_chunks.iter().enumerate() {
        insert(
            &mut tree,
            &root,
            &format!("src/main/java/{package_path}/internal/Operations{index:03}.java"),
            render_operation_chunk(api, operations, &package, index),
        )?;
    }
    insert(
        &mut tree,
        &root,
        &format!("src/main/java/{package_path}/Client.java"),
        render_client_facade(api, &package, style, operation_chunks.len()),
    )?;
    if style == SdkClientStyle::Namespaced {
        for (resource, operations) in resource_operations(api) {
            let overhead = render_resource_chunk(&resource, &[], &package, 0).len() + 64;
            let units = operations
                .iter()
                .map(|operation| poolster_core::source_layout::SourceUnit {
                    bytes: render_resource_chunk(
                        &resource,
                        std::slice::from_ref(operation),
                        &package,
                        0,
                    )
                    .len()
                    .saturating_sub(overhead - 64),
                    resource: None,
                })
                .collect::<Vec<_>>();
            let groups = poolster_core::source_layout::SourceLayout::Chunked {
                max_file_bytes: 128 * 1024,
                max_declarations: Some(100),
            }
            .groups(&units, overhead)?;
            for (index, indices) in groups.iter().enumerate() {
                let operations = indices
                    .iter()
                    .map(|index| operations[*index].clone())
                    .collect::<Vec<_>>();
                insert(
                    &mut tree,
                    &root,
                    &format!(
                        "src/main/java/{package_path}/internal/resources/{resource}ResourcePart{index:03}.java"
                    ),
                    render_resource_chunk(&resource, &operations, &package, index),
                )?;
            }
            insert(
                &mut tree,
                &root,
                &format!("src/main/java/{package_path}/{resource}Resource.java"),
                render_resource_facade(&resource, &package, groups.len()),
            )?;
        }
    }
    if api.schemas.is_empty() {
        let imports = tree
            .iter()
            .filter(|(path, _)| path.extension().is_some_and(|ext| ext == "java"))
            .map(|(path, source)| {
                (
                    path.to_path_buf(),
                    source.replace(&format!("import {package}.model.*;\n"), ""),
                )
            })
            .collect::<Vec<_>>();
        for (path, source) in imports {
            tree.replace(GeneratedFile::new(path, source)?)?;
        }
    }
    let oversized = tree.iter().filter_map(|(path, source)| {
        let native = path.extension().and_then(|value| value.to_str()) == Some("java");
        (native && source.len() > 128 * 1024).then(|| serde_json::json!({"path":path,"bytes":source.len(),"max_file_bytes":128*1024,"reason":"Atomic native declaration or public facade exceeds the grouping budget; source was retained intact."}))
    }).collect::<Vec<_>>();
    if !oversized.is_empty() {
        insert(
            &mut tree,
            &root,
            ".poolster/source-layout-diagnostics.json",
            serde_json::to_string_pretty(&oversized)?,
        )?;
    }
    Ok(tree)
}

fn normalized_output_dir(output_dir: &str) -> Result<String> {
    let root = output_dir.trim_matches('/');
    if root.split('/').any(|part| part == "..") {
        bail!("Java SDK output directory cannot contain parent-directory components");
    }
    Ok(root.to_owned())
}

fn insert(tree: &mut GeneratedTree, root: &str, path: &str, contents: String) -> Result<()> {
    let path = match root {
        "" | "." => path.to_owned(),
        _ => format!("{root}/{path}"),
    };
    tree.insert(GeneratedFile::new(path, contents)?)
}

fn settings_gradle(artifact: &str) -> String {
    format!("rootProject.name = '{artifact}'\n")
}

fn build_gradle(package: &str, artifact: &str, version: &str) -> String {
    format!(
        "plugins {{\n    id 'java-library'\n    id 'maven-publish'\n}}\n\ngroup = '{package}'\nversion = '{version}'\n\njava {{\n    toolchain {{\n        languageVersion = JavaLanguageVersion.of(17)\n    }}\n    withSourcesJar()\n}}\n\nrepositories {{\n    mavenCentral()\n}}\n\ndependencies {{\n    api 'com.fasterxml.jackson.core:jackson-databind:2.18.3'\n    api 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.18.3'\n}}\n\npublishing {{\n    publications {{\n        maven(MavenPublication) {{\n            from components.java\n            artifactId = '{artifact}'\n        }}\n    }}\n}}\n"
    )
}

fn pom_xml(package: &str, artifact: &str, version: &str) -> String {
    format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<project xmlns=\"http://maven.apache.org/POM/4.0.0\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd\">\n  <modelVersion>4.0.0</modelVersion>\n  <groupId>{package}</groupId>\n  <artifactId>{artifact}</artifactId>\n  <version>{version}</version>\n  <properties>\n    <maven.compiler.release>17</maven.compiler.release>\n    <maven.compiler.source>17</maven.compiler.source>\n    <maven.compiler.target>17</maven.compiler.target>\n    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>\n  </properties>\n  <dependencies>\n    <dependency><groupId>com.fasterxml.jackson.core</groupId><artifactId>jackson-databind</artifactId><version>2.18.3</version></dependency>\n    <dependency><groupId>com.fasterxml.jackson.datatype</groupId><artifactId>jackson-datatype-jsr310</artifactId><version>2.18.3</version></dependency>\n  </dependencies>\n</project>\n"
    )
}

fn readme(api: &Api, package: &str, artifact: &str, style: SdkClientStyle) -> String {
    let call = match style {
        SdkClientStyle::Flat => "client.getContact(new Client.GetContactRequest(id));",
        SdkClientStyle::Namespaced => "client.contacts().get(new Client.GetContactRequest(id));",
    };
    let middleware = r#"## Runtime customization

Supply a customer-owned `java.net.http.HttpClient` in `ClientConfig`:

```java
var config = new ClientConfig(
    "https://api.example.com", System.getenv("API_KEY"),
    "Authorization", "Bearer", java.util.Map.of(), customerHttpClient,
    java.time.Duration.ofSeconds(30), RetryConfig.defaults(), null);
var client = new Client(config);
```

`customerHttpClient` can be a delegating `HttpClient` subclass. Implement its
abstract methods, forward client configuration and both `sendAsync` overloads,
and wrap `send(request, bodyHandler)` (the path used by this SDK). Rebuild an
immutable request with `HttpRequest.newBuilder(request, (name, value) -> true)`
to change headers, method, URI or body before forwarding. Return a replacement
`HttpResponse<T>` to rewrite a response or short circuit, preserving the supplied
body handler's `T` representation. Catch and translate transport failures while
preserving interruption. Observer hooks do not return replacement requests or
responses. The decorator sees each transport attempt, including SDK retries;
keep rewrites repeatable and avoid consuming streaming bodies during inspection.
"#;
    format!(
        "# {artifact}\n\nGenerated Java 17+ SDK for {}. See [STYLE_GUIDE.md](STYLE_GUIDE.md) for the selected public API.\n\n```java\nimport {package}.Client;\nimport {package}.ClientConfig;\n\nvar client = new Client(new ClientConfig(\"https://api.example.com\", System.getenv(\"API_KEY\")));\n{call}\n```\n\nThe package supports both Gradle (`build.gradle`) and Maven (`pom.xml`).\n\n{middleware}",
        api.name
    )
}

fn style_guide(api: &Api, package: &str, style: SdkClientStyle) -> String {
    let surface = match style {
        SdkClientStyle::Flat => {
            "## Flat client\n\nOperations are exposed directly on `Client`, for example `client.getContact(input)`. This package was generated with `SdkClientStyle.Flat`."
        }
        SdkClientStyle::Namespaced => {
            "## Namespaced client\n\nOperations are grouped by the first OpenAPI tag, falling back to a stable path resource. Use `client.contacts().get(input)`. Direct methods remain on `Client` for migration. This package was generated with `SdkClientStyle.Namespaced`."
        }
    };
    format!(
        "# {} Java SDK style guide\n\nPackage: `{package}`.\n\n{surface}\n\n## Pagination\n\nA declared safe cursor or offset/limit contract adds `{{operation}}Pages(input)`, a lazy `Iterable` of the operation's normal response type. It reuses the ordinary operation for every page. Cursor inputs may be string query, header, or required path parameters; path cursors require an initial value under OpenAPI. Legacy offset/page inputs use optional direct integer query parameters; referenced integer control schemas do not receive helpers. declared `type: page` also accepts required integer query inputs and validates `outputs.results` against the response schema. Omitted pages default to 1 and offsets to 0; explicit zero is preserved. Results-based helpers stop on empty or short arrays, guard integer overflow, and reject negative inputs or nonpositive limits. Cursor and same-origin URL helpers stop on repeated continuations. Every helper stops after 10,000 pages. JSONPath field/array selectors and RFC 6901 pointers are supported. Body continuations stay explicit rather than being guessed.\n\n## Media and streaming\n\nNon-JSON success responses are returned as `byte[]`; non-JSON request bodies accept `byte[]`. A `text/event-stream` operation returns `Stream<String>` containing complete event data payloads (multiline data fields are joined with a newline; metadata and comments are ignored). Close that stream when finished.\n",
        api.name
    )
}

fn declared_error_responses(operation: &Operation) -> Vec<&OperationResponse> {
    operation
        .responses
        .iter()
        .filter(|response| {
            response
                .status
                .parse::<u16>()
                .is_ok_and(|status| !(200..300).contains(&status))
        })
        .collect()
}

fn declared_error_schema(response: &OperationResponse) -> Option<&SchemaValue> {
    response
        .media_types
        .iter()
        .find(|media| is_json_media(&media.content_type))
        .and_then(|media| media.schema.as_ref())
}

fn java_error_name(operation: &Operation, response: &OperationResponse) -> String {
    format!(
        "{}Status{}Exception",
        type_name(&operation.id),
        response.status
    )
}

fn java_error_mapper_name(operation: &Operation) -> String {
    format!("map{}Error", type_name(&operation.id))
}

/// Error types are nested under Client so the package retains one public
/// transport exception file while callers can catch operation/status-specific
/// classes. A malformed declared error body remains available as raw text.
fn render_declared_error_types(output: &mut String, api: &Api) {
    for operation in &api.operations {
        let responses = declared_error_responses(operation);
        if responses.is_empty() {
            continue;
        }
        let mapper = java_error_mapper_name(operation);
        let _ = writeln!(
            output,
            "    private RuntimeException {mapper}(ApiException error) {{\n        return switch (error.statusCode()) {{"
        );
        for response in &responses {
            let status = &response.status;
            let error = java_error_name(operation, response);
            if let Some(schema) = declared_error_schema(response) {
                let class = response_class(schema);
                let _ = writeln!(
                    output,
                    "            case {status} -> new {error}(error, decodeDeclaredError(error.responseBody(), {class}.class));"
                );
            } else {
                let _ = writeln!(output, "            case {status} -> new {error}(error);");
            }
        }
        output.push_str("            default -> error;\n        };\n    }\n\n");
        for response in responses {
            let error = java_error_name(operation, response);
            if let Some(schema) = declared_error_schema(response) {
                let body = operation_response_type(schema);
                let _ = writeln!(
                    output,
                    "    public static final class {error} extends ApiException {{\n        private final {body} body;\n        private {error}(ApiException source, {body} body) {{ super(source.statusCode(), source.responseBody(), source.retryAfter(), source.retryAfterMillis()); this.body = body; }}\n        public {body} body() {{ return body; }}\n    }}\n"
                );
            } else {
                let _ = writeln!(
                    output,
                    "    public static final class {error} extends ApiException {{\n        private {error}(ApiException source) {{ super(source.statusCode(), source.responseBody(), source.retryAfter(), source.retryAfterMillis()); }}\n    }}\n"
                );
            }
        }
    }
    output.push_str("    private <T> T decodeDeclaredError(String response, Class<T> type) {\n        if (response == null || response.isBlank()) return null;\n        try { return mapper.readValue(response, type); } catch (JsonProcessingException ignored) { return null; }\n    }\n\n");
}

#[cfg(test)]
mod tests;

mod package;
pub use package::{Java, PackageExt, Sdk, Settings, package, sdk};

mod bundled_middleware;

#[cfg(test)]
mod source_layout_tests;
