[package]
name = "poolster-plugin-go"
version.workspace = true
edition = "2024"
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Native Go SDK generator for Poolster"
publish = ["crates-io"]

[dependencies]
anyhow = "1.0.102"
poolster-core = { version = "0.5.0-alpha.1", path = "../../core" }
serde_json = "1.0.138"

[dev-dependencies]
tempfile = "3.27.0"
