//! Native Go SDK generation for Poolster.
//!
//! HTTP providers consume the neutral [`Api`] model. The [`grpc`] provider
//! consumes owned Protobuf RPC contracts and invokes pinned official Go generators.
//! Input parser library types do not cross either output interface.

pub mod contracts;

use std::{
    collections::{BTreeMap, BTreeSet},
    fmt::Write,
};

use anyhow::{Result, bail};
use poolster_core::{
    AdditionalProperties, Api, GeneratedFile, GeneratedTree, Operation, OperationParameter, Schema,
    SchemaKind, SchemaValue, SdkClientStyle,
};

const NOTICE: &str = "// Code generated by Poolster. DO NOT EDIT.\n";

pub mod graphql;
pub use graphql::{
    Graphql, GraphqlClient, GraphqlScalarMapping, GraphqlStyle, graphql, graphql_incremental,
};
pub mod grpc;
pub use grpc::{Grpc, GrpcToolchain, grpc};

mod composition;
mod layout;
mod operation_tests;
mod page_pagination;
mod symbols;
pub use operation_tests::{OperationTests, operation_tests};
pub mod providers;
mod response_validation;
pub use providers::{client, models, operations, roundtrip_tests, transport};

mod http;
use http::*;

mod models;
use models::*;

mod runtime;
use runtime::*;

mod responses;
use responses::*;

mod operations;
use operations::*;

mod pagers;
use pagers::*;

mod parameters;
use parameters::*;

mod resources;
use resources::*;

mod naming;
use naming::*;

#[cfg(test)]
mod tests;

mod bundled_middleware;
mod package;
pub use package::{Go, PackageExt, Sdk, Settings, package, sdk};

mod webhooks;
pub use webhooks::{Webhooks, webhooks};

mod oauth;
pub use oauth::{OAuth, oauth};
