//! Generates a distributable Rust command-line client from Poolster's neutral API.
//!
//! The generated `poolster_extension.rs` is emitted as a custom file. It is the
//! stable, user-owned place for provider-specific login, request signing, and
//! observability without editing generated command wiring.

use anyhow::{Result, bail};
use poolster_core::{
    Api, GeneratedFile, Operation, SchemaKind, SchemaValue, SecuritySchemeCatalog,
    SecuritySchemeKind,
    engine::{Language, Meta, Package, Plugin, PluginContext},
};

const NOTICE: &str = "// Generated by Poolster. Do not edit.\n";

mod package;
pub use package::{PackageExt, RustCli, Settings, package};
mod http;
pub use http::{Cli, cli};
mod manifest;
use manifest::*;
mod commands;
use commands::*;
mod operations;
use operations::*;
mod docs;
use docs::*;
mod names;
use names::*;
mod extensions;
use extensions::*;
#[cfg(test)]
mod tests;

#[path = "lib_input.rs"]
mod http_input;

mod graphql;
pub use graphql::{Graphql, graphql};
