//! Selection-specific model, operation and facade emission.
use super::*;

#[cfg(test)]
pub(super) fn render(
    contract: &GraphqlOperations,
    style: GraphqlStyle,
    groups: &BTreeMap<String, BTreeMap<String, String>>,
) -> Result<(BTreeMap<String, String>, BTreeMap<String, String>)> {
    render_advanced(contract, style, groups, false, false)
}
pub(super) fn render_advanced(
    contract: &GraphqlOperations,
    style: GraphqlStyle,
    groups: &BTreeMap<String, BTreeMap<String, String>>,
    subscriptions: bool,
    incremental: bool,
) -> Result<(BTreeMap<String, String>, BTreeMap<String, String>)> {
    ensure!(
        !contract.operations.is_empty(),
        "Swift GraphQL generation requires operations"
    );
    let mut source = String::from("// Generated by Poolster.\n");
    source.push_str(include_str!("runtime/runtime.swift.tmpl"));
    let runtime = include_str!("runtime/runtime.swift.tmpl");
    let client_start = runtime.find("public final class GraphqlClient").unwrap();
    let header = "// Generated by Poolster.\nimport Foundation\n#if canImport(FoundationNetworking)\nimport FoundationNetworking\n#endif\n";
    let mut files = BTreeMap::new();
    files.insert(
        "Runtime/GraphqlRuntime.swift".into(),
        String::from("// Generated by Poolster.\n") + &runtime[..client_start],
    );
    files.insert(
        "Client/GraphqlClient.swift".into(),
        header.to_owned() + &runtime[client_start..],
    );
    files.insert(
        "Runtime/GraphqlAdvanced.swift".into(),
        header.to_owned() + include_str!("runtime/advanced.swift.tmpl"),
    );
    let mut models = models::Models::default();
    for (name, fields) in &contract.input_objects {
        models.object(&ident(name), fields)?;
    }
    let mut symbols = BTreeMap::new();
    for op in &contract.operations {
        ensure!(
            op.kind != GraphqlOperationKind::Subscription || subscriptions,
            "Swift GraphQL subscriptions require a separate unsupported transport"
        );
        let name = ident(&op.name);
        ensure!(
            !symbols.values().any(|v| v == &name),
            "GraphQL operation naming collision {name}"
        );
        ensure!(
            !["Execute", "GraphqlClient", "Query", "Mutation"].contains(&name.as_str()),
            "GraphQL operation conflicts with runtime {name}"
        );
        models.object(&format!("{name}Variables"), &op.variables)?;
        let result = models.ty(&format!("{name}Result"), &op.result)?;
        let args = if op.variables.is_empty() {
            String::new()
        } else {
            format!(", variables: {name}Variables")
        };
        let vars = if op.variables.is_empty() {
            "GraphqlEmptyVariables()"
        } else {
            "variables"
        };
        let method = member(&op.name);
        let return_type = if incremental {
            format!("AsyncThrowingStream<GraphqlIncrementalSnapshot<{result}>,Error>")
        } else if op.kind == GraphqlOperationKind::Subscription {
            format!("AsyncThrowingStream<GraphqlResponse<{result}>,Error>")
        } else {
            format!("GraphqlResponse<{result}>")
        };
        let execution = if incremental {
            "incremental"
        } else if op.kind == GraphqlOperationKind::Subscription {
            "subscribe"
        } else {
            "executeWithScalars"
        };
        let variable_shape = literal(&serde_json::to_string(
            &poolster_core::native::graphql_scalar_fields(&op.variables),
        )?);
        let result_shape = literal(&serde_json::to_string(
            &poolster_core::native::graphql_scalar_shape(&op.result),
        )?);
        let input_shapes: BTreeMap<_, _> = contract
            .input_objects
            .iter()
            .map(|(name, fields)| (name, poolster_core::native::graphql_scalar_fields(fields)))
            .collect();
        let inputs = literal(&serde_json::to_string(&input_shapes)?);
        let operation_start = source.len();
        writeln!(source,"public func {method}(client: GraphqlClient{args}) async throws -> {return_type} {{\n  try await client.{execution}(operationName:{},document:{},variables:{vars},resultType:{result}.self,variableShape:{variable_shape},resultShape:{result_shape},inputs:{inputs})\n}}",literal(&op.name),literal(&op.document)).unwrap();
        if style == GraphqlStyle::Flat {
            let args = args.trim_start_matches(", ");
            writeln!(source,"extension GraphqlClient {{\n  public func {method}({args}) async throws -> {return_type} {{\n    try await self.{execution}(operationName:{},document:{},variables:{vars},resultType:{result}.self,variableShape:{variable_shape},resultShape:{result_shape},inputs:{inputs})\n  }}\n\n}}",literal(&op.name),literal(&op.document)).unwrap();
        }
        files.insert(
            format!("Operations/{}", filename(&format!("Operation{name}"))),
            header.to_owned() + &source[operation_start..],
        );
        symbols.insert(op.name.clone(), name);
    }
    if style == GraphqlStyle::Idiomatic {
        let mut groups = groups.clone();
        if groups.is_empty() {
            for op in &contract.operations {
                groups
                    .entry(
                        if op.kind == GraphqlOperationKind::Query {
                            "query"
                        } else if op.kind == GraphqlOperationKind::Subscription {
                            "subscription"
                        } else {
                            "mutation"
                        }
                        .into(),
                    )
                    .or_default()
                    .insert(op.name.clone(), op.name.clone());
            }
        }
        let mut names = std::collections::BTreeSet::new();
        for (group, methods) in groups {
            let property = member(&group);
            let group = ident(&group);
            ensure!(
                names.insert(group.clone()) && group != "Execute",
                "GraphQL group naming collision"
            );
            files.insert(format!("Groups/{}/{}",filename(&group).trim_end_matches(".swift"),filename(&format!("{group}Group"))),header.to_owned()+&format!("extension GraphqlClient {{\n  public var {property}: {group}Group {{\n    {group}Group(client:self)\n  }}\n\n}}\n\npublic struct {group}Group {{\n  let client: GraphqlClient\n}}\n\n"));
            writeln!(source,"extension GraphqlClient {{\n  public var {property}: {group}Group {{\n    {group}Group(client:self)\n  }}\n\n}}\n\npublic struct {group}Group {{\n  fileprivate let client: GraphqlClient").unwrap();
            let mut names = std::collections::BTreeSet::new();
            for (method, operation) in methods {
                let method = member(&method);
                ensure!(
                    names.insert(method.clone()) && method != "`client`",
                    "GraphQL method naming collision"
                );
                let name = symbols
                    .get(&operation)
                    .ok_or_else(|| anyhow::anyhow!("unknown GraphQL operation {operation}"))?;
                let op = contract
                    .operations
                    .iter()
                    .find(|op| op.name == operation)
                    .unwrap();
                let args = if op.variables.is_empty() {
                    String::new()
                } else {
                    format!("variables: {name}Variables")
                };
                let vars = if op.variables.is_empty() {
                    "GraphqlEmptyVariables()"
                } else {
                    "variables"
                };
                let method_start = source.len();
                let return_type = if incremental {
                    format!("AsyncThrowingStream<GraphqlIncrementalSnapshot<{name}Result>,Error>")
                } else if op.kind == GraphqlOperationKind::Subscription {
                    format!("AsyncThrowingStream<GraphqlResponse<{name}Result>,Error>")
                } else {
                    format!("GraphqlResponse<{name}Result>")
                };
                let execution = if incremental {
                    "incremental"
                } else if op.kind == GraphqlOperationKind::Subscription {
                    "subscribe"
                } else {
                    "executeWithScalars"
                };
                let variable_shape = literal(&serde_json::to_string(
                    &poolster_core::native::graphql_scalar_fields(&op.variables),
                )?);
                let result_shape = literal(&serde_json::to_string(
                    &poolster_core::native::graphql_scalar_shape(&op.result),
                )?);
                let input_shapes: BTreeMap<_, _> = contract
                    .input_objects
                    .iter()
                    .map(|(name, fields)| {
                        (name, poolster_core::native::graphql_scalar_fields(fields))
                    })
                    .collect();
                let inputs = literal(&serde_json::to_string(&input_shapes)?);
                writeln!(source,"public func {method}({args}) async throws -> {return_type} {{\n  try await client.{execution}(operationName:{},document:{},variables:{vars},resultType:{name}Result.self,variableShape:{variable_shape},resultShape:{result_shape},inputs:{inputs})\n}}",literal(&op.name),literal(&op.document)).unwrap();
                files.insert(
                    format!(
                        "Groups/{}/{}",
                        filename(&group).trim_end_matches(".swift"),
                        filename(&serde_json::to_string(&("group_method", &group, &method))?)
                    ),
                    header.to_owned()
                        + &format!("extension {group}Group {{\n  ")
                        + &source[method_start..]
                        + "}\n",
                );
            }
            source.push_str("}\n");
        }
    } else {
        ensure!(
            groups.is_empty(),
            "GraphQL custom groups require idiomatic style"
        );
    }
    source.push_str(&models.source);
    let mut declarations = std::collections::BTreeSet::new();
    for line in source.lines() {
        for prefix in ["public final class ", "public struct ", "public enum "] {
            if let Some(rest) = line.strip_prefix(prefix) {
                let name = rest.split([' ', '<', ':', '{']).next().unwrap_or_default();
                ensure!(
                    declarations.insert(name.to_owned()),
                    "GraphQL generated declaration collision {name}"
                );
            }
        }
    }
    for (path, body) in models.files {
        files.insert(path, header.to_owned() + &body);
    }
    let oversized=files.iter().filter(|(_,body)|body.len()>128*1024).map(|(path,body)|serde_json::json!({"path":path,"bytes":body.len(),"max_file_bytes":128*1024,"reason":"Atomic Swift GraphQL declaration exceeds the source grouping budget; source retained intact."})).collect::<Vec<_>>();
    if !oversized.is_empty() {
        files.insert(
            ".poolster/source-layout-diagnostics.json".into(),
            serde_json::to_string_pretty(&oversized)?,
        );
    }
    Ok((files, symbols))
}

pub(super) fn filename(value: &str) -> String {
    let readable = ident(value);
    let prefix = readable.chars().take(80).collect::<String>();
    let hash = value
        .as_bytes()
        .iter()
        .fold(0xcbf29ce484222325_u64, |h, b| {
            (h ^ u64::from(*b)).wrapping_mul(0x100000001b3)
        });
    format!("{prefix}_{hash:016x}.swift")
}
