[package]
name = "poolster-inputs"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Convenience bundle of native input providers for Poolster"
publish = ["crates-io"]

[features]
default = ["openapi", "graphql", "asyncapi", "arazzo", "protobuf", "capnproto"]
graphql = ["dep:poolster-input-graphql"]
asyncapi = ["dep:poolster-input-asyncapi"]
arazzo = ["dep:poolster-input-arazzo"]
protobuf = ["dep:poolster-input-protobuf"]
capnproto = ["dep:poolster-input-capnproto"]

openapi = ["dep:poolster-input-openapi"]

[dependencies]
poolster-input-openapi = { version = "0.5.0", path = "../openapi", optional = true }
poolster-core = { version = "0.5.0", path = "../../core" }
anyhow = "1.0.102"
poolster-input-graphql = { version = "0.5.0", path = "../graphql", optional = true }
poolster-input-asyncapi = { version = "0.5.0", path = "../asyncapi", optional = true }
poolster-input-arazzo = { version = "0.5.0", path = "../arazzo", optional = true }
poolster-input-protobuf = { version = "0.5.0", path = "../protobuf", optional = true }
poolster-input-capnproto = { version = "0.5.0", path = "../capnproto", optional = true }

[dev-dependencies]
tempfile = "3.27.0"
