//! Native Python SDK output for Poolster.
//!
//! This crate deliberately consumes the normalized `poolster_core::Api`
//! model rather than OpenAPI directly. It therefore composes with the same
//! sidecar and profile pipeline as every other Poolster language target.

mod docs;
mod errors;
mod identifiers;
mod operations;
mod pagination;
mod types;
use docs::*;
use errors::*;
use operations::*;
use pagination::*;
mod resources;
use resources::*;
use types::*;
mod symbols;
use identifiers::*;

use std::{collections::BTreeMap, fmt::Write};

use anyhow::{Result, bail};
use poolster_core::{
    AdditionalProperties, Api, GeneratedFile, GeneratedTree, Operation, RetryClass, Schema,
    SchemaKind, SchemaValue, SdkClientStyle, StreamingKind, analyze_operation,
};
use serde_json::Value;

mod response_validation;

#[cfg(test)]
mod extension_compat_tests;

const NOTICE: &str = "# Generated by Poolster. Do not edit.\n";

fn pagination_annotation(operation: &Operation) -> Option<&Value> {
    operation
        .annotations
        .get("x-poolster-pagination")
        .or_else(|| operation.annotations.get("x-kaji-pagination"))
        .or_else(|| operation.annotations.get("x-speakeasy-pagination"))
}

fn idempotency_annotation(operation: &Operation) -> Option<&Value> {
    operation
        .annotations
        .get("x-poolster-idempotency-resolved")
        .or_else(|| operation.annotations.get("x-kaji-idempotency-resolved"))
}

/// Generates an installable, typed Python SDK below `output_dir`.
///
/// The package uses only the Python standard library at runtime. `package_name`
/// controls both the distribution name in `pyproject.toml` and the import
/// package (with hyphens normalized to underscores). When omitted it is
/// derived from the API title.
#[cfg(test)]
fn render_test_sdk(
    api: &Api,
    output_dir: &str,
    package_name: Option<&str>,
) -> Result<GeneratedTree> {
    render_sdk(api, output_dir, package_name, SdkClientStyle::Flat)
}

/// Generates a Python SDK with either direct operations or resource namespaces.
fn render_sdk(
    api: &Api,
    output_dir: &str,
    package_name: Option<&str>,
    client_style: SdkClientStyle,
) -> Result<GeneratedTree> {
    let prepared = symbols::prepare(api);
    let api = prepared.as_ref();
    for operation in &api.operations {
        if pagination_annotation(operation)
            .and_then(|v| v.get("type"))
            .and_then(Value::as_str)
            == Some("page")
        {
            poolster_core::pagination::normalize_pagination(api, operation, None)?;
        }
    }
    let root = output_dir.trim_matches('/');
    if root.is_empty() {
        bail!("Python SDK output directory cannot be empty");
    }

    let distribution = package_name
        .map(str::to_owned)
        .unwrap_or_else(|| format!("{}-sdk", kebab_case(&api.name)));
    let module = python_module_name(&distribution);
    let mut tree = GeneratedTree::default();
    tree.insert(GeneratedFile::new(
        format!("{root}/pyproject.toml"),
        render_pyproject(&distribution, &api.version),
    )?)?;
    // Keep source files comfortably navigable for very large descriptions.
    // `models` remains a normal import package, so `from sdk.models import X`
    // stays exactly the same for callers.
    tree.insert(GeneratedFile::new(
        format!("{root}/src/{module}/models/__init__.py"),
        render_models_init(api),
    )?)?;
    tree.insert(GeneratedFile::new(
        format!("{root}/src/{module}/models/chunks/__init__.py"),
        format!("{NOTICE}# Bounded model re-export partitions.\n"),
    )?)?;
    for (index, schemas) in api.schemas.chunks(100).enumerate() {
        tree.insert(GeneratedFile::new(
            format!("{root}/src/{module}/models/chunks/exports_{index:03}.py"),
            render_model_exports(schemas),
        )?)?;
    }
    tree.insert(GeneratedFile::new(
        format!("{root}/src/{module}/models/_model_codec.py"),
        include_str!("../templates/model_codec.py"),
    )?)?;
    for schema in &api.schemas {
        tree.insert(GeneratedFile::new(
            format!(
                "{root}/src/{module}/models/{}.py",
                schema_file_name(&schema.name)
            ),
            render_model(schema),
        )?)?;
    }
    tree.insert(GeneratedFile::new(
        format!("{root}/src/{module}/runtime.py"),
        render_runtime(api),
    )?)?;
    tree.insert(GeneratedFile::new(
        format!("{root}/src/{module}/presence.py"),
        include_str!("../templates/presence.py"),
    )?)?;
    for (path, contents) in render_partitioned_errors(api) {
        tree.insert(GeneratedFile::new(
            format!("{root}/src/{module}/{path}"),
            contents,
        )?)?;
    }
    for (path, contents) in response_validation::render_partitioned(api) {
        tree.insert(GeneratedFile::new(
            format!("{root}/src/{module}/{path}"),
            contents,
        )?)?;
    }
    tree.insert(GeneratedFile::new(
        format!("{root}/src/{module}/multipart.py"),
        include_str!("../templates/multipart.py"),
    )?)?;
    if api
        .operations
        .iter()
        .any(|operation| operation_body_kind(operation).ends_with("multipart"))
    {
        tree.insert(GeneratedFile::new(
            format!("{root}/MULTIPART.md"),
            include_str!("../templates/multipart_readme.md"),
        )?)?;
    }
    tree.insert(GeneratedFile::new(
        format!("{root}/src/{module}/oauth.py"),
        include_str!("../templates/oauth.py"),
    )?)?;
    for (index, range) in python_operation_groups(api).into_iter().enumerate() {
        let operations = &api.operations[range];
        tree.insert(GeneratedFile::new(
            format!("{root}/src/{module}/operations_{index:03}.py"),
            render_operation_chunk(api, operations, index),
        )?)?;
    }
    if client_style == SdkClientStyle::Namespaced {
        let resource_names = resource_operations(api).keys().cloned().collect::<Vec<_>>();
        tree.insert(GeneratedFile::new(
            format!("{root}/src/{module}/resources/__init__.py"),
            render_resources_init(resource_names.len()),
        )?)?;
        tree.insert(GeneratedFile::new(
            format!("{root}/src/{module}/resources/chunks/__init__.py"),
            format!("{NOTICE}# Bounded resource re-export partitions.\n"),
        )?)?;
        for (index, resources) in resource_names.chunks(100).enumerate() {
            tree.insert(GeneratedFile::new(
                format!("{root}/src/{module}/resources/chunks/exports_{index:03}.py"),
                render_resource_exports(resources),
            )?)?;
        }
        for (resource, resource_operations) in resource_operations(api) {
            let file = schema_file_name(&resource);
            let groups = python_resource_groups(api, &resource, &resource_operations);
            let group_count = groups.len();
            for (index, range) in groups.into_iter().enumerate() {
                let operations = &resource_operations[range];
                tree.insert(GeneratedFile::new(
                    format!("{root}/src/{module}/resources/{file}_part_{index:03}.py"),
                    render_resource_chunk(api, &resource, &resource_operations, operations, index),
                )?)?;
            }
            tree.insert(GeneratedFile::new(
                format!("{root}/src/{module}/resources/{file}.py"),
                render_resource_facade(&resource, group_count),
            )?)?;
        }
    }
    tree.insert(GeneratedFile::new(
        format!("{root}/src/{module}/client.py"),
        render_client_facade(api, client_style),
    )?)?;
    tree.insert(GeneratedFile::new(
        format!("{root}/src/{module}/__init__.py"),
        render_init(api, client_style),
    )?)?;
    tree.insert(GeneratedFile::new(
        format!("{root}/README.md"),
        render_readme(api, &distribution, &module, client_style),
    )?)?;
    tree.insert(GeneratedFile::new(
        format!("{root}/api.md"),
        render_api_reference(api),
    )?)?;
    if client_style == SdkClientStyle::Namespaced {
        tree.insert(GeneratedFile::new(
            format!("{root}/STYLE_GUIDE.md"),
            render_style_guide(api, &module),
        )?)?;
    }
    Ok(tree)
}

/// Add native async operations while sharing the exact synchronous model package.
fn render_sdk_with_async(
    api: &Api,
    output_dir: &str,
    package_name: Option<&str>,
    style: SdkClientStyle,
    enabled: bool,
) -> Result<GeneratedTree> {
    let mut tree = render_sdk(api, output_dir, package_name, style)?;
    if !enabled {
        return Ok(tree);
    }
    let root = output_dir.trim_matches('/');
    let distribution = package_name
        .map(str::to_owned)
        .unwrap_or_else(|| format!("{}-sdk", kebab_case(&api.name)));
    let module = python_module_name(&distribution);
    let prefix = format!("{root}/src/{module}/");
    let mut files = Vec::new();
    for (path, contents) in tree.iter() {
        let path = path.to_string_lossy();
        let Some(relative) = path.strip_prefix(&prefix) else {
            continue;
        };
        if relative.starts_with("operations_") {
            files.push((
                format!("{prefix}async_{relative}"),
                async_operation_source(contents),
            ));
        } else if let Some(resource) = relative.strip_prefix("resources/") {
            files.push((
                format!("{prefix}async_resources/{resource}"),
                async_resource_source(contents),
            ));
        }
    }
    for (path, contents) in files {
        tree.insert(GeneratedFile::new(path, contents)?)?;
    }
    tree.insert(GeneratedFile::new(
        format!("{prefix}async_runtime.py"),
        include_str!("../templates/async_runtime.py"),
    )?)?;
    let facade = render_client_facade(api, style)
        .replace(
            "from .runtime import BaseClient",
            "from .async_runtime import AsyncBaseClient",
        )
        .replace("from .operations_", "from .async_operations_")
        .replace("from .resources.", "from .async_resources.")
        .replace("class Client(", "class AsyncClient(")
        .replace(", BaseClient)", ", AsyncBaseClient)")
        .replace(
            "class AsyncClient(BaseClient)",
            "class AsyncClient(AsyncBaseClient)",
        );
    tree.insert(GeneratedFile::new(
        format!("{prefix}async_client.py"),
        facade,
    )?)?;
    let init_path = format!("{prefix}__init__.py");
    let init = format!(
        "{}\nfrom .async_client import AsyncClient\n",
        tree.get(&init_path).unwrap()
    );
    tree.replace(GeneratedFile::new(init_path, init)?)?;
    let manifest_path = format!("{root}/pyproject.toml");
    let manifest = format!(
        "{}\n[project.optional-dependencies]\nasync = [\"httpx>=0.27,<1\"]\n",
        tree.get(&manifest_path).unwrap()
    );
    tree.replace(GeneratedFile::new(manifest_path, manifest)?)?;
    Ok(tree)
}

// These transformations apply only to Poolster's own generated operation grammar.
// Models, wire codecs, signatures and pagination declarations remain shared.
fn async_operation_source(source: &str) -> String {
    source
        .replace("Any, Iterator, cast", "Any, AsyncIterator, cast")
        .replace("Iterator[", "AsyncIterator[")
        .replace("    def ", "    async def ")
        .replace("result = self._request(", "result = await self._request(")
        .replace(
            "result = self._event_stream(",
            "result = await self._event_stream(",
        )
        .replace("response = self.", "response = await self.")
}
fn async_resource_source(source: &str) -> String {
    let source = source
        .replace("Any, Iterator", "Any, AsyncIterator")
        .replace("Iterator[", "AsyncIterator[");
    let mut output = String::new();
    for line in source.lines() {
        let line = if line.starts_with("    def ")
            && !line.contains("__init__")
            && !line.contains("_pages(")
        {
            line.replacen("    def ", "    async def ", 1)
        } else if line.contains("return self._client.") && !line.contains("_pages(") {
            line.replacen("return self._client.", "return await self._client.", 1)
        } else {
            line.to_owned()
        };
        output.push_str(&line);
        output.push('\n');
    }
    output
}

fn render_pyproject(package_name: &str, version: &str) -> String {
    format!(
        "[build-system]\nrequires = [\"hatchling\"]\nbuild-backend = \"hatchling.build\"\n\n[project]\nname = {package_name:?}\nversion = {:?}\ndescription = \"Generated Python client for {}\"\nrequires-python = \">=3.10\"\nlicense = {{ text = \"MIT\" }}\nclassifiers = [\n  \"Programming Language :: Python :: 3\",\n  \"Programming Language :: Python :: 3 :: Only\",\n  \"Typing :: Typed\",\n]\n\n[tool.hatch.build.targets.wheel]\npackages = [\"src/{}\"]\n",
        python_package_version(version),
        package_name,
        python_module_name(package_name),
    )
}

fn render_models_init(api: &Api) -> String {
    let mut output = format!(
        "{NOTICE}\nfrom __future__ import annotations\n\nfrom dataclasses import MISSING as _MISSING, fields as _fields, is_dataclass as _is_dataclass\nfrom typing import Any as _Any\n\n\ndef _to_wire(value: _Any) -> _Any:\n    \"\"\"Convert generated dataclasses into JSON-compatible values.\"\"\"\n    if _is_dataclass(value) and not isinstance(value, type):\n        result = {{}}\n        present = next((getattr(value, item.name) for item in _fields(value) if item.metadata.get(\"present_fields\")), None)\n        for item in _fields(value):\n            current = getattr(value, item.name)\n            if item.metadata.get(\"additional_properties\"):\n                result.update(_to_wire(current))\n        for item in _fields(value):\n            current = getattr(value, item.name)\n            if not item.metadata.get(\"internal\") and not item.metadata.get(\"additional_properties\") and (current is not None or (present is not None and item.metadata.get(\"wire_name\", item.name) in present) or (item.default is _MISSING and item.default_factory is _MISSING)):\n                result[item.metadata.get(\"wire_name\", item.name)] = _to_wire(current)\n        return result\n    if isinstance(value, list):\n        return [_to_wire(item) for item in value]\n    if isinstance(value, dict):\n        return {{key: _to_wire(item) for key, item in value.items()}}\n    return value\n\n"
    );
    for index in 0..api.schemas.len().div_ceil(100) {
        let _ = writeln!(output, "from .chunks.exports_{index:03} import *");
    }
    output
}

fn render_model_exports(schemas: &[Schema]) -> String {
    let mut output = format!("{NOTICE}from __future__ import annotations\n\n");
    for schema in schemas {
        let name = python_type_name(&schema.name);
        let file = schema_file_name(&schema.name);
        let _ = writeln!(output, "from ..{file} import {name}");
    }
    output
}

fn render_resources_init(resources: usize) -> String {
    let mut output = format!("{NOTICE}from __future__ import annotations\n\n");
    for index in 0..resources.div_ceil(100) {
        let _ = writeln!(output, "from .chunks.exports_{index:03} import *");
    }
    output
}

fn render_resource_exports(resources: &[String]) -> String {
    let mut output = format!("{NOTICE}from __future__ import annotations\n\n");
    for resource in resources {
        let file = schema_file_name(resource);
        let class = format!("{}Resource", pascal_case(resource));
        let _ = writeln!(output, "from ..{file} import {class}");
    }
    output
}

fn render_model(schema: &Schema) -> String {
    let mut output = format!(
        "{NOTICE}from __future__ import annotations\n\nfrom dataclasses import dataclass, field as _poolster_field\nfrom typing import Any, Literal, TYPE_CHECKING\nfrom ._model_codec import decode_model_value\n\nif TYPE_CHECKING:\n    from typing import TypeAlias\n\n"
    );
    let mut references = std::collections::BTreeSet::new();
    python_references(&schema.value, &mut references);
    references.remove(&python_type_name(&schema.name));
    if !references.is_empty() {
        output.push_str("if TYPE_CHECKING:\n");
        for reference in references {
            let _ = writeln!(output, "    from . import {reference}");
        }
        output.push('\n');
    }
    render_schema(&mut output, schema);
    output
}

fn python_references(value: &SchemaValue, names: &mut std::collections::BTreeSet<String>) {
    match &value.kind {
        SchemaKind::Reference { reference } => {
            names.insert(python_type_name(
                reference.rsplit('/').next().unwrap_or(reference),
            ));
        }
        SchemaKind::Array { items } => python_references(items, names),
        SchemaKind::Object {
            fields,
            additional_properties,
        } => {
            for field in fields {
                python_references(&field.value, names);
            }
            if let AdditionalProperties::Schema { value } = additional_properties {
                python_references(value, names);
            }
        }
        SchemaKind::OneOf { variants }
        | SchemaKind::AnyOf { variants }
        | SchemaKind::AllOf { variants } => {
            for variant in variants {
                python_references(variant, names);
            }
        }
        SchemaKind::Not { schema } => python_references(schema, names),
        _ => {}
    }
}

fn python_decode_shape(value: &SchemaValue) -> String {
    match &value.kind {
        SchemaKind::Reference { reference } => format!(
            "(\"ref\", {:?})",
            python_type_name(reference.rsplit('/').next().unwrap_or(reference))
        ),
        SchemaKind::Array { items } => format!("(\"array\", {})", python_decode_shape(items)),
        SchemaKind::Object { fields, .. } => format!(
            "(\"object\", {{{}}})",
            fields
                .iter()
                .map(|field| format!("{:?}: {}", field.name, python_decode_shape(&field.value)))
                .collect::<Vec<_>>()
                .join(", ")
        ),
        _ => "None".into(),
    }
}

fn render_schema(output: &mut String, schema: &Schema) {
    let name = python_type_name(&schema.name);
    match &schema.value.kind {
        SchemaKind::Object {
            fields,
            additional_properties,
        } => {
            let mut additional_field = "additional_properties".to_owned();
            while fields
                .iter()
                .any(|item| python_field_identifier(fields, item) == additional_field)
            {
                additional_field.insert(0, '_');
            }
            let mut present_field = "_poolster_present_fields".to_owned();
            while fields
                .iter()
                .any(|item| python_field_identifier(fields, item) == present_field)
                || present_field == additional_field
            {
                present_field.insert(0, '_');
            }
            output.push_str("@dataclass\n");
            let _ = writeln!(output, "class {name}:");
            // Required fields must precede fields with defaults in a dataclass.
            for required in [true, false] {
                for item in fields.iter().filter(|item| item.required == required) {
                    let field_name = python_field_identifier(fields, item);
                    let field_type = python_type(&item.value);
                    if item.required {
                        if field_name == item.name {
                            let _ = writeln!(output, "    {field_name}: {field_type}");
                        } else {
                            let _ = writeln!(
                                output,
                                "    {field_name}: {field_type} = _poolster_field(metadata={{\"wire_name\": {:?}}})",
                                item.name
                            );
                        }
                    } else if field_name == item.name {
                        let _ = writeln!(output, "    {field_name}: {field_type} | None = None");
                    } else {
                        let _ = writeln!(
                            output,
                            "    {field_name}: {field_type} | None = _poolster_field(default=None, metadata={{\"wire_name\": {:?}}})",
                            item.name
                        );
                    }
                }
            }
            if !matches!(additional_properties, AdditionalProperties::Forbidden) {
                let additional_type = match additional_properties {
                    AdditionalProperties::Schema { value } => python_type(value),
                    _ => "Any".to_owned(),
                };
                let _ = writeln!(
                    output,
                    "    {additional_field}: dict[str, {}] = _poolster_field(default_factory=dict, metadata={{\"additional_properties\": True}})",
                    additional_type
                );
            }
            let _ = writeln!(
                output,
                "    {present_field}: frozenset[str] | None = _poolster_field(default=None, init=False, repr=False, compare=False, metadata={{\"internal\": True, \"present_fields\": True}})"
            );
            output.push_str("\n    @classmethod\n");
            let _ = writeln!(
                output,
                "    def from_dict(cls, value: dict[str, Any]) -> \"{name}\":"
            );
            if fields.is_empty() && matches!(additional_properties, AdditionalProperties::Forbidden)
            {
                output.push_str("        return cls()\n");
            } else {
                output.push_str("        instance = cls(\n");
                for item in fields {
                    let field_name = python_field_identifier(fields, item);
                    let accessor = if item.required {
                        format!("value[{key:?}]", key = item.name)
                    } else {
                        format!("value.get({key:?})", key = item.name)
                    };
                    let shape = python_decode_shape(&item.value);
                    let accessor = if shape == "None" {
                        accessor
                    } else {
                        format!("decode_model_value({accessor}, {shape})")
                    };
                    let _ = writeln!(output, "            {field_name}={accessor},");
                }
                if !matches!(additional_properties, AdditionalProperties::Forbidden) {
                    let declared = fields
                        .iter()
                        .map(|item| format!("{:?}", item.name))
                        .collect::<Vec<_>>()
                        .join(", ");
                    let item = match additional_properties {
                        AdditionalProperties::Schema { value } => {
                            format!("decode_model_value(item, {})", python_decode_shape(value))
                        }
                        _ => "item".into(),
                    };
                    let _ = writeln!(
                        output,
                        "            {additional_field}={{key: {item} for key, item in value.items() if key not in [{declared}]}},"
                    );
                }
                let _ = writeln!(
                    output,
                    "        )\n        instance.{present_field} = frozenset(value)\n        return instance"
                );
            }
        }
        _ if !schema.value.enum_values.is_empty() => {
            let values = schema
                .value
                .enum_values
                .iter()
                .map(python_literal)
                .collect::<Vec<_>>();
            let future = if schema
                .value
                .extensions
                .get("x-poolster-open-enum")
                .or_else(|| schema.value.extensions.get("x-kaji-open-enum"))
                .and_then(serde_json::Value::as_bool)
                == Some(true)
            {
                let mut primitives = std::collections::BTreeSet::new();
                for value in &schema.value.enum_values {
                    primitives.insert(if value.is_string() {
                        "str"
                    } else if value.is_boolean() {
                        "bool"
                    } else if value.is_i64() || value.is_u64() {
                        "int"
                    } else if value.is_number() {
                        "float"
                    } else {
                        "None"
                    });
                }
                format!(
                    " | {}",
                    primitives.into_iter().collect::<Vec<_>>().join(" | ")
                )
            } else {
                String::new()
            };
            let _ = writeln!(output, "{name} = Literal[{}]{future}", values.join(", "));
        }
        _ => {
            let mut references = std::collections::BTreeSet::new();
            python_references(&schema.value, &mut references);
            let annotation = python_type(&schema.value);
            if references.is_empty() {
                let _ = writeln!(output, "{name} = {annotation}");
            } else {
                // Future annotations do not defer a type alias assignment. A
                // PEP 613 forward alias also avoids circular model imports.
                let _ = writeln!(output, "{name}: TypeAlias = {annotation:?}");
            }
        }
    }
}

/// The transport/runtime is deliberately separate from API operations.  Large
/// specs then load a small stable client plus bounded operation modules.
fn render_runtime(api: &Api) -> String {
    let errors = if partition_python_errors(api) {
        "from .errors import *\n".into()
    } else {
        render_declared_error_classes(api)
    };
    let output = format!(
        r#"{NOTICE}
from __future__ import annotations

import json
import time
import re
from dataclasses import fields, is_dataclass, replace
from typing import Any, Callable, Iterator, cast
from urllib.error import HTTPError, URLError
from urllib.parse import quote, urlencode, urljoin, urlsplit
from urllib.request import Request, urlopen

from .models import *
from .models import _to_wire as to_wire
from .multipart import MultipartBody, FilePart, JsonPart, RawJsonPart, encode_multipart
from .response_validation import ResponseDecodeError


class ApiError(Exception):
    """An unsuccessful HTTP response returned by the API.

    ``body`` is decoded using the OpenAPI error response schema, when one was
    declared. ``headers`` retains request IDs and rate-limit information.
    """

    def __init__(self, status_code: int, headers: dict[str, str], body: Any) -> None:
        self.status_code = status_code
        self.headers = headers
        self.body = body
        super().__init__(f"API request failed with status {{status_code}}")


{errors}
def _poolster_json_path(value: Any, path: str) -> Any:
    """Supported paths start at ``$`` or use RFC 6901 JSON pointers; never evaluate code."""
    current = to_wire(value)
    if path.startswith("/"):
        segments = []
        for item in path[1:].split("/"):
            if re.search(r"~(?![01])", item):
                return None
            segments.append(item.replace("~1", "/").replace("~0", "~"))
    elif path.startswith("$"):
        segments = []
        rest = path[1:]
        while rest:
            match = re.match(r"(?:\.([^.[\]]+)|\[(-?\d+)\])", rest)
            if match is None:
                return None
            segments.append(match.group(1) if match.group(1) is not None else int(match.group(2)))
            rest = rest[match.end():]
    else:
        return None
    for segment in segments:
        if isinstance(current, list):
            if path.startswith("/") and (not isinstance(segment, str) or re.fullmatch(r"0|[1-9][0-9]*", segment) is None):
                return None
            try:
                index = int(segment)
            except (ValueError, TypeError):
                return None
            if index < -len(current) or index >= len(current):
                return None
            current = current[index]
        elif isinstance(current, dict) and segment in current:
            current = current[segment]
        else:
            return None
    return current


def _poolster_with_body_value(body: Any, wire_name: str, value: Any) -> Any:
    """Copy a generated JSON request body with one declared field replaced."""
    if is_dataclass(body) and not isinstance(body, type):
        for item in fields(body):
            if item.metadata.get("wire_name", item.name) == wire_name:
                result = replace(body, **{{item.name: value}})
                for internal in fields(body):
                    if internal.metadata.get("present_fields"):
                        previous = getattr(body, internal.name)
                        if previous is not None:
                            setattr(result, internal.name, previous | {{wire_name}})
                return result
        raise TypeError(f"request body has no declared {{wire_name!r}} field")
    if isinstance(body, dict):
        return {{**body, wire_name: value}}
    raise TypeError("body pagination requires a generated dataclass or dictionary JSON body")


class BaseClient:
    """Configurable synchronous client for {}."""

    def __init__(
        self,
        base_url: str,
        *,
        api_key: str | None = None,
        bearer_token: str | None = None,
        token_provider: Callable[[str | None], str] | None = None,
        headers: dict[str, str] | None = None,
        timeout: float = 30.0,
        max_retries: int = 2,
        retry_initial_delay: float = 0.25,
        retry_max_delay: float = 8.0,
        middleware: tuple[Callable[..., Any], ...] = (),
        validate_responses: bool = False,
        before_request: Callable[[dict[str, Any]], None] | None = None,
        after_response: Callable[[dict[str, Any]], None] | None = None,
        on_error: Callable[[Exception, dict[str, Any]], None] | None = None,
    ) -> None:
        self.base_url = base_url.rstrip("/")
        self.api_key = api_key
        self.bearer_token = bearer_token
        self.token_provider = token_provider
        self.headers = dict(headers or {{}})
        self.timeout = timeout
        self.max_retries = max(0, max_retries)
        self.retry_initial_delay = max(0.0, retry_initial_delay)
        self.retry_max_delay = max(0.0, retry_max_delay)
        self.middleware = tuple(middleware)
        self.validate_responses = validate_responses
        self.before_request = before_request
        self.after_response = after_response
        self.on_error = on_error

    def for_call(self, *, headers: dict[str, str] | None = None, timeout: float | None = None) -> Any:
        """Create an independent scope sharing middleware, hooks, auth and async driver."""
        import math
        selected_timeout = self.timeout if timeout is None else timeout
        if not math.isfinite(selected_timeout) or selected_timeout <= 0:
            raise ValueError("call timeout must be finite and positive")
        selected_headers = dict(self.headers)
        for name, value in (headers or {{}}).items():
            for previous in list(selected_headers):
                if previous.lower() == name.lower():
                    del selected_headers[previous]
            selected_headers[name] = value
        options = dict(api_key=self.api_key, bearer_token=self.bearer_token, token_provider=self.token_provider,
                       headers=selected_headers, timeout=selected_timeout, max_retries=self.max_retries,
                       retry_initial_delay=self.retry_initial_delay, retry_max_delay=self.retry_max_delay,
                       middleware=self.middleware, validate_responses=self.validate_responses,
                       before_request=self.before_request, after_response=self.after_response, on_error=self.on_error)
        if hasattr(self, "_http_client"):
            options.update(http_client=self._http_client, async_middleware=self.async_middleware)
        return type(self)(self.base_url, **options)

    def _request(
        self,
        method: str,
        path: str,
        *,
        query: dict[str, Any] | None = None,
        headers: dict[str, str] | None = None,
        body: Any = None,
        body_kind: str = "json",
        error_types: dict[int, tuple[type[ApiError], type[Any] | None]] | None = None,
        retryable: bool = False,
        idempotency_header: str | None = None,
        pagination_url: str | None = None,
        response_operation: str | None = None,
    ) -> Any:
        url = f"{{self.base_url}}{{path}}"
        if query:
            query = {{name: ([str(item).lower() if isinstance(item, bool) else item for item in value] if isinstance(value, (list, tuple)) else str(value).lower() if isinstance(value, bool) else value) for name, value in query.items()}}
            encoded = urlencode({{key: value for key, value in query.items() if value is not None}}, doseq=True)
            if encoded:
                url = f"{{url}}?{{encoded}}"
        if pagination_url is not None:
            candidate = urlsplit(urljoin(url, pagination_url))
            expected = urlsplit(url)
            if candidate.scheme != expected.scheme or candidate.netloc != expected.netloc:
                raise ValueError("pagination URL must remain on the configured API origin")
            url = candidate.geturl()
        request_headers = {{"Accept": "application/json", **self.headers, **(headers or {{}})}}
        managed_auth = self.token_provider is not None and not self.bearer_token and not any(name.lower() == "authorization" for name in request_headers)
        auth_token = self.token_provider(None) if managed_auth else None
        if auth_token:
            request_headers["Authorization"] = f"Bearer {{auth_token}}"
        elif self.bearer_token and not any(name.lower() == "authorization" for name in request_headers):
            request_headers.setdefault("Authorization", f"Bearer {{self.bearer_token}}")
        elif self.api_key and not any(name.lower() == "authorization" for name in request_headers):
            request_headers.setdefault("Authorization", f"Bearer {{self.api_key}}")
        data = None
        if body is not None:
            if isinstance(body, MultipartBody):
                if body_kind != "multipart" and not body_kind.endswith("_or_multipart"):
                    raise TypeError("operation does not declare multipart/form-data")
                body_kind = "multipart"
            elif body_kind.endswith("_or_multipart"):
                body_kind = body_kind.removesuffix("_or_multipart")
            if body_kind == "form":
                value = to_wire(body)
                if not isinstance(value, dict):
                    raise TypeError("form request bodies must serialize to a dictionary")
                request_headers.setdefault("Content-Type", "application/x-www-form-urlencoded")
                data = urlencode(value, doseq=True).encode("utf-8")
            elif body_kind == "multipart":
                data, multipart_content_type = encode_multipart(body, to_wire)
                request_headers = {{key: value for key, value in request_headers.items() if key.lower() != "content-type"}}
                request_headers["Content-Type"] = multipart_content_type
            elif body_kind in ("json-seq", "ndjson", "application/json-seq", "application/x-ndjson", "application/ndjson", "application/jsonl"):
                value = to_wire(body)
                if not isinstance(value, list):
                    raise TypeError("Sequential JSON request bodies must serialize to a list")
                request_headers.setdefault("Content-Type", body_kind if body_kind.startswith("application/") else "application/json-seq" if body_kind == "json-seq" else "application/x-ndjson")
                data = "".join(("\x1e" if body_kind in ("json-seq", "application/json-seq") else "") + json.dumps(item, allow_nan=False) + "\n" for item in value).encode("utf-8")
            elif body_kind == "binary":
                if not isinstance(body, (bytes, bytearray, memoryview)):
                    raise TypeError("binary request bodies must be bytes-like")
                request_headers.setdefault("Content-Type", "application/octet-stream")
                data = bytes(body)
            else:
                request_headers.setdefault("Content-Type", "application/json")
                data = json.dumps(to_wire(body)).encode("utf-8")
        request_context = {{"method": method, "url": url, "query": query or {{}}, "headers": request_headers, "body": body}}
        can_retry = retryable and (method.upper() in {{"GET", "HEAD", "OPTIONS", "TRACE", "QUERY", "PUT", "DELETE"}} or (method.upper() in {{"POST", "PATCH"}} and any((name.lower() == "idempotency-key" or (idempotency_header is not None and name.lower() == idempotency_header.lower())) and value is not None and bool(str(value).strip()) for name, value in request_headers.items())))
        auth_refreshed = False
        for attempt in range(self.max_retries + (2 if managed_auth else 1)):
            if self.before_request is not None:
                self.before_request({{**request_context, "attempt": attempt}})
            request = Request(url, data=data, headers=request_headers, method=method)
            try:
                with self._send(request) as response:
                    status_code = response.status
                    response_headers = dict(response.headers.items())
                    if can_retry and status_code in {{408, 429, 500, 502, 503, 504}} and attempt < self.max_retries:
                        self._retry_delay(attempt, response_headers.get("Retry-After"), next((value for name, value in response_headers.items() if name.lower() == "retry-after-ms"), None))
                        continue
                    raw = response.read(10 * 1024 * 1024 + 1) if self.validate_responses else response.read()
                    if self.after_response is not None:
                        self.after_response({{"request": request_context, "status_code": status_code, "headers": response_headers, "body": raw}})
                    content_type = response.headers.get_content_type()
                    from .response_validation import decode_json, decode_sequence
                    decoded = decode_sequence(raw, content_type, self.validate_responses) if raw and content_type in ("application/json-seq", "application/x-ndjson", "application/ndjson", "application/jsonl") else decode_json(raw, self.validate_responses) if raw and (content_type == "application/json" or content_type.endswith("+json")) else raw or None
                    if self.validate_responses and response_operation is not None and method.upper() != "HEAD":
                        from .response_validation import PLANS, check_response
                        check_response(decoded, PLANS["operations"].get(response_operation, {{}}), PLANS["refs"], status_code, content_type)
                    return decoded
            except ResponseDecodeError as error:
                if self.on_error is not None:
                    self.on_error(error, request_context)
                raise
            except HTTPError as error:
                if error.code == 401 and managed_auth and can_retry and not auth_refreshed:
                    error.close()
                    auth_token = self.token_provider(auth_token)
                    request_headers["Authorization"] = f"Bearer {{auth_token}}"
                    auth_refreshed = True
                    continue
                if can_retry and error.code in {{408, 429, 500, 502, 503, 504}} and attempt < self.max_retries:
                    retry_after = error.headers.get("Retry-After")
                    error.close()
                    self._retry_delay(attempt, retry_after, error.headers.get("retry-after-ms"))
                    continue
                try:
                    raw = error.read()
                finally:
                    error.close()
                try:
                    response_body = json.loads(raw) if raw else None
                except json.JSONDecodeError:
                    response_body = raw.decode("utf-8", errors="replace")
                error_type, body_type = (error_types or {{}}).get(error.code, (ApiError, None))
                if body_type is not None and isinstance(response_body, dict):
                    response_body = body_type.from_dict(response_body)
                raised = error_type(error.code, dict(error.headers.items()), response_body)
                if self.on_error is not None:
                    self.on_error(raised, request_context)
                raise raised from error
            except URLError as error:
                if can_retry and attempt < self.max_retries:
                    self._retry_delay(attempt)
                    continue
                if self.on_error is not None:
                    self.on_error(error, request_context)
                raise
        raise RuntimeError("Poolster retry loop completed without a response")

    def _send(self, request: Request) -> Any:
        """Run native transport middleware in declaration order for each attempt."""
        def transport(request: Request) -> Any:
            return urlopen(request, timeout=self.timeout)
        handler = transport
        for middleware in reversed(self.middleware):
            following = handler
            def handler(request: Request, middleware: Any = middleware, following: Any = following) -> Any:
                return middleware(request, following)
        return handler(request)

    def _retry_delay(self, attempt: int, retry_after: str | None = None, retry_after_ms: str | None = None) -> None:
        import math
        server_delay = None
        for value, divisor in ((retry_after_ms, 1000.0), (retry_after, 1.0)):
            try:
                candidate = float(value) / divisor if value is not None else None
            except (ValueError, TypeError):
                continue
            if candidate is not None and math.isfinite(candidate) and candidate >= 0:
                server_delay = candidate
                break
        delay = server_delay if server_delay is not None else self.retry_initial_delay * (2 ** attempt)
        time.sleep(min(max(0.0, delay), max(0.0, self.retry_max_delay)))

    def _event_stream(
        self,
        method: str,
        path: str,
        *,
        query: dict[str, Any] | None = None,
        headers: dict[str, str] | None = None,
        body: Any = None,
        body_kind: str = "json",
        error_types: dict[int, tuple[type[ApiError], type[Any] | None]] | None = None,
        retryable: bool = False,
        idempotency_header: str | None = None,
    ) -> Iterator[Any]:
        """Open an SSE response and yield decoded ``data:`` events.

        Retries are limited to establishing the connection. Once an event has
        been yielded, reconnecting is application policy: Poolster never invents a
        last-event-id or resume token.
        """
        url = f"{{self.base_url}}{{path}}"
        if query:
            encoded_query = urlencode({{key: value for key, value in query.items() if value is not None}}, doseq=True)
            if encoded_query:
                url = f"{{url}}?{{encoded_query}}"
        request_headers = {{"Accept": "text/event-stream", **self.headers, **(headers or {{}})}}
        managed_auth = self.token_provider is not None and not self.bearer_token and not any(name.lower() == "authorization" for name in request_headers)
        auth_token = self.token_provider(None) if managed_auth else None
        if auth_token:
            request_headers["Authorization"] = f"Bearer {{auth_token}}"
        elif self.bearer_token and not any(name.lower() == "authorization" for name in request_headers):
            request_headers.setdefault("Authorization", f"Bearer {{self.bearer_token}}")
        elif self.api_key and not any(name.lower() == "authorization" for name in request_headers):
            request_headers.setdefault("Authorization", f"Bearer {{self.api_key}}")
        data = None
        if body is not None:
            if isinstance(body, MultipartBody):
                if body_kind != "multipart" and not body_kind.endswith("_or_multipart"):
                    raise TypeError("operation does not declare multipart/form-data")
                body_kind = "multipart"
            elif body_kind.endswith("_or_multipart"):
                body_kind = body_kind.removesuffix("_or_multipart")
            if body_kind == "form":
                value = to_wire(body)
                if not isinstance(value, dict):
                    raise TypeError("form request bodies must serialize to a dictionary")
                request_headers.setdefault("Content-Type", "application/x-www-form-urlencoded")
                data = urlencode(value, doseq=True).encode("utf-8")
            elif body_kind == "multipart":
                data, multipart_content_type = encode_multipart(body, to_wire)
                request_headers = {{key: value for key, value in request_headers.items() if key.lower() != "content-type"}}
                request_headers["Content-Type"] = multipart_content_type
            elif body_kind == "binary":
                if not isinstance(body, (bytes, bytearray, memoryview)):
                    raise TypeError("binary request bodies must be bytes-like")
                request_headers.setdefault("Content-Type", "application/octet-stream")
                data = bytes(body)
            else:
                request_headers.setdefault("Content-Type", "application/json")
                data = json.dumps(to_wire(body)).encode("utf-8")
        context = {{"method": method, "url": url, "query": query or {{}}, "headers": request_headers, "body": body}}
        can_retry = retryable and (method.upper() in {{"GET", "HEAD", "OPTIONS", "TRACE", "QUERY", "PUT", "DELETE"}} or (method.upper() in {{"POST", "PATCH"}} and any((name.lower() == "idempotency-key" or (idempotency_header is not None and name.lower() == idempotency_header.lower())) and value is not None and bool(str(value).strip()) for name, value in request_headers.items())))
        auth_refreshed = False
        for attempt in range(self.max_retries + (2 if managed_auth else 1)):
            if self.before_request is not None:
                self.before_request({{**context, "attempt": attempt}})
            request = Request(url, data=data, headers=request_headers, method=method)
            try:
                response = self._send(request)
                if self.after_response is not None:
                    self.after_response({{"request": context, "status_code": response.status, "headers": dict(response.headers.items()), "body": None}})
                def events() -> Iterator[Any]:
                    data_lines: list[str] = []
                    try:
                        for raw_line in response:
                            line = raw_line.decode("utf-8", errors="replace").rstrip("\r\n")
                            if line == "":
                                if data_lines:
                                    payload = "\n".join(data_lines)
                                    try:
                                        yield json.loads(payload)
                                    except json.JSONDecodeError:
                                        yield payload
                                    data_lines = []
                            elif line.startswith("data:"):
                                data_lines.append(line[5:].lstrip(" "))
                        if data_lines:
                            payload = "\n".join(data_lines)
                            try:
                                yield json.loads(payload)
                            except json.JSONDecodeError:
                                yield payload
                    finally:
                        response.close()
                return events()
            except HTTPError as error:
                if error.code == 401 and managed_auth and can_retry and not auth_refreshed:
                    error.close()
                    auth_token = self.token_provider(auth_token)
                    request_headers["Authorization"] = f"Bearer {{auth_token}}"
                    auth_refreshed = True
                    continue
                if can_retry and error.code in {{408, 429, 500, 502, 503, 504}} and attempt < self.max_retries:
                    retry_after = error.headers.get("Retry-After")
                    error.close()
                    self._retry_delay(attempt, retry_after, error.headers.get("retry-after-ms"))
                    continue
                try:
                    raw = error.read()
                finally:
                    error.close()
                try:
                    response_body = json.loads(raw) if raw else None
                except json.JSONDecodeError:
                    response_body = raw.decode("utf-8", errors="replace")
                error_type, body_type = (error_types or {{}}).get(error.code, (ApiError, None))
                if body_type is not None and isinstance(response_body, dict):
                    response_body = body_type.from_dict(response_body)
                raised = error_type(error.code, dict(error.headers.items()), response_body)
                if self.on_error is not None:
                    self.on_error(raised, context)
                raise raised from error
            except URLError as error:
                if can_retry and attempt < self.max_retries:
                    self._retry_delay(attempt)
                    continue
                if self.on_error is not None:
                    self.on_error(error, context)
                raise
        raise RuntimeError("Poolster stream retry loop completed without a response")

"#,
        api.name
    );
    output
}

fn bounded_source_ranges(sizes: &[usize], overhead: usize) -> Vec<std::ops::Range<usize>> {
    let units = sizes
        .iter()
        .map(|bytes| poolster_core::source_layout::SourceUnit {
            bytes: *bytes,
            resource: None,
        })
        .collect::<Vec<_>>();
    poolster_core::source_layout::SourceLayout::Chunked {
        max_file_bytes: 128 * 1024,
        max_declarations: Some(100),
    }
    .groups(&units, overhead)
    .expect("valid bounded source layout")
    .into_iter()
    .map(|group| group[0]..group[group.len() - 1] + 1)
    .collect()
}

fn python_operation_groups(api: &Api) -> Vec<std::ops::Range<usize>> {
    let overhead = render_operation_chunk(api, &[], 0).len();
    let sizes = api
        .operations
        .iter()
        .map(|operation| {
            render_operation_chunk(api, std::slice::from_ref(operation), 0)
                .len()
                .saturating_sub(overhead)
        })
        .collect::<Vec<_>>();
    bounded_source_ranges(&sizes, overhead + 64)
}

fn python_resource_groups(
    api: &Api,
    resource: &str,
    operations: &[&Operation],
) -> Vec<std::ops::Range<usize>> {
    let overhead = render_resource_chunk(api, resource, operations, &[], 0).len();
    let sizes = operations
        .iter()
        .map(|operation| {
            render_resource_chunk(
                api,
                resource,
                operations,
                std::slice::from_ref(operation),
                0,
            )
            .len()
            .saturating_sub(overhead)
        })
        .collect::<Vec<_>>();
    bounded_source_ranges(&sizes, overhead + 512)
}

fn render_operation_chunk(api: &Api, operations: &[Operation], index: usize) -> String {
    let mut output = format!(
        "{NOTICE}from __future__ import annotations\n\nfrom typing import Any, Iterator, cast\nfrom uuid import uuid4\nfrom urllib.parse import quote\n\nfrom .runtime import ApiError, _poolster_json_path, _poolster_with_body_value, to_wire\nfrom .multipart import MultipartBody\nfrom .models import *\n\n\nclass Operations{index:03}:\n"
    );
    for operation in operations {
        output.push_str(&render_operation(api, operation));
        if let Some(page) = render_page_paginator(api, operation) {
            output.push_str(&page);
        } else if let Some(pagination) = cursor_pagination(api, operation) {
            output.push_str(&render_cursor_paginator(api, operation, &pagination));
        } else if let Some(pagination) = offset_pagination(operation) {
            output.push_str(&render_offset_paginator(operation, &pagination));
        } else if let Some(pagination) = url_pagination(operation) {
            output.push_str(&render_url_paginator(operation, &pagination));
        }
    }
    output
}

fn render_client_facade(api: &Api, client_style: SdkClientStyle) -> String {
    let operation_imports = (0..python_operation_groups(api).len())
        .map(|index| format!("from .operations_{index:03} import Operations{index:03}"))
        .collect::<Vec<_>>();
    let resources = resource_operations(api);
    let mut output = format!(
        "{NOTICE}from __future__ import annotations\n\nfrom .runtime import BaseClient\n{}\n",
        operation_imports.join("\n")
    );
    if client_style == SdkClientStyle::Namespaced {
        for resource in resources.keys() {
            let class = format!("{}Resource", pascal_case(resource));
            let file = schema_file_name(resource);
            let _ = writeln!(output, "from .resources.{file} import {class}");
        }
    }
    let bases = operation_imports
        .iter()
        .enumerate()
        .map(|(index, _)| format!("Operations{index:03}"))
        .chain(std::iter::once("BaseClient".to_owned()))
        .collect::<Vec<_>>();
    output.push_str(&format!("\n\nclass Client({}):\n", bases.join(", ")));
    if client_style == SdkClientStyle::Namespaced {
        output.push_str("    def __init__(self, *args, **kwargs) -> None:\n        super().__init__(*args, **kwargs)\n");
        for (resource, operations) in &resources {
            let _ = writeln!(
                output,
                "        self.{} = {}Resource(self)",
                resource_attribute(resource, operations),
                pascal_case(resource)
            );
        }
    } else {
        output.push_str("    pass\n");
    }
    output
}

#[cfg(test)]
mod tests;

mod bundled_middleware;
mod multipart;
mod package;
pub use package::{
    OperationTests, PackageExt, Python, PythonModels, Roundtrips, Sdk, Settings, Webhooks,
    operation_tests, package, roundtrips, sdk, webhooks,
};

#[cfg(test)]
mod openapi32_native_tests;
