//! Native Python SDK output for Poolster.
//!
//! This crate deliberately consumes the normalized `poolster_core::Api`
//! model rather than OpenAPI directly. It therefore composes with the same
//! sidecar and profile pipeline as every other Poolster language target.

mod docs;
mod errors;
mod identifiers;
mod layout;
mod models;
mod operations;
mod pagination;
mod runtime;
mod types;
use docs::*;
use errors::*;
use layout::*;
use models::*;
use operations::*;
use pagination::*;
use runtime::render_runtime;
mod resources;
use resources::*;
use types::*;
mod symbols;
use identifiers::*;

use std::{collections::BTreeMap, fmt::Write};

use anyhow::{Result, bail};
use poolster_core::{
    AdditionalProperties, Api, GeneratedFile, GeneratedTree, Operation, RetryClass, Schema,
    SchemaKind, SchemaValue, SdkClientStyle, StreamingKind, analyze_operation,
};
use serde_json::Value;

mod response_validation;

#[cfg(test)]
mod extension_compat_tests;

const NOTICE: &str = "# Generated by Poolster. Do not edit.\n";

fn pagination_annotation(operation: &Operation) -> Option<&Value> {
    operation
        .annotations
        .get("x-poolster-pagination")
        .or_else(|| operation.annotations.get("x-kaji-pagination"))
        .or_else(|| operation.annotations.get("x-speakeasy-pagination"))
}

fn idempotency_annotation(operation: &Operation) -> Option<&Value> {
    operation
        .annotations
        .get("x-poolster-idempotency-resolved")
        .or_else(|| operation.annotations.get("x-kaji-idempotency-resolved"))
}

/// Generates an installable, typed Python SDK below `output_dir`.
///
/// The package uses only the Python standard library at runtime. `package_name`
/// controls both the distribution name in `pyproject.toml` and the import
/// package (with hyphens normalized to underscores). When omitted it is
/// derived from the API title.
#[cfg(test)]
fn render_test_sdk(
    api: &Api,
    output_dir: &str,
    package_name: Option<&str>,
) -> Result<GeneratedTree> {
    render_sdk(api, output_dir, package_name, SdkClientStyle::Flat)
}

/// Generates a Python SDK with either direct operations or resource namespaces.
fn render_sdk(
    api: &Api,
    output_dir: &str,
    package_name: Option<&str>,
    client_style: SdkClientStyle,
) -> Result<GeneratedTree> {
    let prepared = symbols::prepare(api);
    let api = prepared.as_ref();
    for operation in &api.operations {
        if pagination_annotation(operation)
            .and_then(|v| v.get("type"))
            .and_then(Value::as_str)
            == Some("page")
        {
            poolster_core::pagination::normalize_pagination(api, operation, None)?;
        }
    }
    let root = output_dir.trim_matches('/');
    if root.is_empty() {
        bail!("Python SDK output directory cannot be empty");
    }

    let distribution = package_name
        .map(str::to_owned)
        .unwrap_or_else(|| format!("{}-sdk", kebab_case(&api.name)));
    let module = python_module_name(&distribution);
    let mut tree = GeneratedTree::default();
    tree.insert(GeneratedFile::new(
        format!("{root}/pyproject.toml"),
        render_pyproject(&distribution, &api.version),
    )?)?;
    // Keep source files comfortably navigable for very large descriptions.
    // `models` remains a normal import package, so `from sdk.models import X`
    // stays exactly the same for callers.
    tree.insert(GeneratedFile::new(
        format!("{root}/src/{module}/models/__init__.py"),
        render_models_init(api),
    )?)?;
    tree.insert(GeneratedFile::new(
        format!("{root}/src/{module}/models/chunks/__init__.py"),
        format!("{NOTICE}# Bounded model re-export partitions.\n"),
    )?)?;
    for (index, schemas) in api.schemas.chunks(100).enumerate() {
        tree.insert(GeneratedFile::new(
            format!("{root}/src/{module}/models/chunks/exports_{index:03}.py"),
            render_model_exports(schemas),
        )?)?;
    }
    tree.insert(GeneratedFile::new(
        format!("{root}/src/{module}/models/_model_codec.py"),
        include_str!("../templates/model_codec.py"),
    )?)?;
    for schema in &api.schemas {
        tree.insert(GeneratedFile::new(
            format!(
                "{root}/src/{module}/models/{}.py",
                schema_file_name(&schema.name)
            ),
            render_model(schema),
        )?)?;
    }
    tree.insert(GeneratedFile::new(
        format!("{root}/src/{module}/runtime.py"),
        render_runtime(api),
    )?)?;
    tree.insert(GeneratedFile::new(
        format!("{root}/src/{module}/presence.py"),
        include_str!("../templates/presence.py"),
    )?)?;
    for (path, contents) in render_partitioned_errors(api) {
        tree.insert(GeneratedFile::new(
            format!("{root}/src/{module}/{path}"),
            contents,
        )?)?;
    }
    for (path, contents) in response_validation::render_partitioned(api) {
        tree.insert(GeneratedFile::new(
            format!("{root}/src/{module}/{path}"),
            contents,
        )?)?;
    }
    tree.insert(GeneratedFile::new(
        format!("{root}/src/{module}/multipart.py"),
        include_str!("../templates/multipart.py"),
    )?)?;
    if api
        .operations
        .iter()
        .any(|operation| operation_body_kind(operation).ends_with("multipart"))
    {
        tree.insert(GeneratedFile::new(
            format!("{root}/MULTIPART.md"),
            include_str!("../templates/multipart_readme.md"),
        )?)?;
    }
    tree.insert(GeneratedFile::new(
        format!("{root}/src/{module}/oauth.py"),
        include_str!("../templates/oauth.py"),
    )?)?;
    for (index, range) in python_operation_groups(api).into_iter().enumerate() {
        let operations = &api.operations[range];
        tree.insert(GeneratedFile::new(
            format!("{root}/src/{module}/operations_{index:03}.py"),
            render_operation_chunk(api, operations, index),
        )?)?;
    }
    if client_style == SdkClientStyle::Namespaced {
        let resource_names = resource_operations(api).keys().cloned().collect::<Vec<_>>();
        tree.insert(GeneratedFile::new(
            format!("{root}/src/{module}/resources/__init__.py"),
            render_resources_init(resource_names.len()),
        )?)?;
        tree.insert(GeneratedFile::new(
            format!("{root}/src/{module}/resources/chunks/__init__.py"),
            format!("{NOTICE}# Bounded resource re-export partitions.\n"),
        )?)?;
        for (index, resources) in resource_names.chunks(100).enumerate() {
            tree.insert(GeneratedFile::new(
                format!("{root}/src/{module}/resources/chunks/exports_{index:03}.py"),
                render_resource_exports(resources),
            )?)?;
        }
        for (resource, resource_operations) in resource_operations(api) {
            let file = schema_file_name(&resource);
            let groups = python_resource_groups(api, &resource, &resource_operations);
            let group_count = groups.len();
            for (index, range) in groups.into_iter().enumerate() {
                let operations = &resource_operations[range];
                tree.insert(GeneratedFile::new(
                    format!("{root}/src/{module}/resources/{file}_part_{index:03}.py"),
                    render_resource_chunk(api, &resource, &resource_operations, operations, index),
                )?)?;
            }
            tree.insert(GeneratedFile::new(
                format!("{root}/src/{module}/resources/{file}.py"),
                render_resource_facade(&resource, group_count),
            )?)?;
        }
    }
    tree.insert(GeneratedFile::new(
        format!("{root}/src/{module}/client.py"),
        render_client_facade(api, client_style),
    )?)?;
    tree.insert(GeneratedFile::new(
        format!("{root}/src/{module}/__init__.py"),
        render_init(api, client_style),
    )?)?;
    tree.insert(GeneratedFile::new(
        format!("{root}/README.md"),
        render_readme(api, &distribution, &module, client_style),
    )?)?;
    tree.insert(GeneratedFile::new(
        format!("{root}/api.md"),
        render_api_reference(api),
    )?)?;
    if client_style == SdkClientStyle::Namespaced {
        tree.insert(GeneratedFile::new(
            format!("{root}/STYLE_GUIDE.md"),
            render_style_guide(api, &module),
        )?)?;
    }
    Ok(tree)
}

/// Add native async operations while sharing the exact synchronous model package.
fn render_sdk_with_async(
    api: &Api,
    output_dir: &str,
    package_name: Option<&str>,
    style: SdkClientStyle,
    enabled: bool,
) -> Result<GeneratedTree> {
    let mut tree = render_sdk(api, output_dir, package_name, style)?;
    if !enabled {
        return Ok(tree);
    }
    let root = output_dir.trim_matches('/');
    let distribution = package_name
        .map(str::to_owned)
        .unwrap_or_else(|| format!("{}-sdk", kebab_case(&api.name)));
    let module = python_module_name(&distribution);
    let prefix = format!("{root}/src/{module}/");
    let mut files = Vec::new();
    for (path, contents) in tree.iter() {
        let path = path.to_string_lossy();
        let Some(relative) = path.strip_prefix(&prefix) else {
            continue;
        };
        if relative.starts_with("operations_") {
            files.push((
                format!("{prefix}async_{relative}"),
                async_operation_source(contents),
            ));
        } else if let Some(resource) = relative.strip_prefix("resources/") {
            files.push((
                format!("{prefix}async_resources/{resource}"),
                async_resource_source(contents),
            ));
        }
    }
    for (path, contents) in files {
        tree.insert(GeneratedFile::new(path, contents)?)?;
    }
    tree.insert(GeneratedFile::new(
        format!("{prefix}async_runtime.py"),
        include_str!("../templates/async_runtime.py"),
    )?)?;
    let facade = render_client_facade(api, style)
        .replace(
            "from .runtime import BaseClient",
            "from .async_runtime import AsyncBaseClient",
        )
        .replace("from .operations_", "from .async_operations_")
        .replace("from .resources.", "from .async_resources.")
        .replace("class Client(", "class AsyncClient(")
        .replace(", BaseClient)", ", AsyncBaseClient)")
        .replace(
            "class AsyncClient(BaseClient)",
            "class AsyncClient(AsyncBaseClient)",
        );
    tree.insert(GeneratedFile::new(
        format!("{prefix}async_client.py"),
        facade,
    )?)?;
    let init_path = format!("{prefix}__init__.py");
    let init = format!(
        "{}\nfrom .async_client import AsyncClient\n",
        tree.get(&init_path).unwrap()
    );
    tree.replace(GeneratedFile::new(init_path, init)?)?;
    let manifest_path = format!("{root}/pyproject.toml");
    let manifest = format!(
        "{}\n[project.optional-dependencies]\nasync = [\"httpx>=0.27,<1\"]\n",
        tree.get(&manifest_path).unwrap()
    );
    tree.replace(GeneratedFile::new(manifest_path, manifest)?)?;
    Ok(tree)
}

// These transformations apply only to Poolster's own generated operation grammar.
// Models, wire codecs, signatures and pagination declarations remain shared.
fn async_operation_source(source: &str) -> String {
    source
        .replace("Any, Iterator, cast", "Any, AsyncIterator, cast")
        .replace("Iterator[", "AsyncIterator[")
        .replace("    def ", "    async def ")
        .replace("result = self._request(", "result = await self._request(")
        .replace(
            "result = self._event_stream(",
            "result = await self._event_stream(",
        )
        .replace("response = self.", "response = await self.")
}
fn async_resource_source(source: &str) -> String {
    let source = source
        .replace("Any, Iterator", "Any, AsyncIterator")
        .replace("Iterator[", "AsyncIterator[");
    let mut output = String::new();
    for line in source.lines() {
        let line = if line.starts_with("    def ")
            && !line.contains("__init__")
            && !line.contains("_pages(")
        {
            line.replacen("    def ", "    async def ", 1)
        } else if line.contains("return self._client.") && !line.contains("_pages(") {
            line.replacen("return self._client.", "return await self._client.", 1)
        } else {
            line.to_owned()
        };
        output.push_str(&line);
        output.push('\n');
    }
    output
}

#[cfg(test)]
mod tests;

mod bundled_middleware;
mod multipart;
mod package;
pub use package::{
    OperationTests, PackageExt, Python, PythonModels, Roundtrips, Sdk, Settings, Webhooks,
    operation_tests, package, roundtrips, sdk, webhooks,
};

#[cfg(test)]
mod openapi32_native_tests;
