//! Generated bounded buffered-operation tests; never contact an API.
use super::{Python, PythonModels, Sdk};
use anyhow::{Result, bail, ensure};
use kaji_core::{
    Api, GeneratedFile, SchemaKind, SchemaValue,
    engine::{Handle, Meta, Plugin, PluginContext, Requirement},
};
use serde_json::{Value, json};

pub struct OperationTests {
    meta: Meta,
    models: Option<Handle<PythonModels>>,
}
pub fn operation_tests() -> OperationTests {
    OperationTests {
        meta: Meta::new(),
        models: None,
    }
}
impl OperationTests {
    pub fn using_models(mut self, handle: Handle<PythonModels>) -> Self {
        self.models = Some(handle);
        self
    }
    pub fn models_from(self, sdk: &Sdk) -> Self {
        self.using_models(sdk.models())
    }
}
impl Plugin<Python> for OperationTests {
    fn kind(&self) -> &'static str {
        "python-operation-tests"
    }
    fn meta(&self) -> &Meta {
        &self.meta
    }
    fn requires(&self) -> Vec<Requirement> {
        vec![Requirement::on(self.models)]
    }
    fn generate(&self, cx: &mut PluginContext<'_, Python>) -> Result<()> {
        let models = cx.inputs.get::<PythonModels>()?;
        ensure!(
            models.module.split('.').all(|part| part
                .chars()
                .next()
                .is_some_and(|c| c.is_ascii_alphabetic() || c == '_')
                && part.chars().all(|c| c.is_ascii_alphanumeric() || c == '_')),
            "operation test module must be a safe Python import"
        );
        let mut api = cx.api.clone();
        for schema in &mut api.schemas {
            sanitize(&mut schema.value)
        }
        let mut cases = Vec::new();
        let mut diagnostics = Vec::new();
        for operation in &api.operations {
            if cases.len() >= 256 {
                diagnostics.push(json!({"operation":operation.id,"status":"skipped","reason":"operation fixture limit (256)"}));
                continue;
            }
            match case(&api, operation, models) {
                Ok(case) => cases.push(case),
                Err(error) => diagnostics.push(
                    json!({"operation":operation.id,"status":"skipped","reason":error.to_string()}),
                ),
            }
        }
        cx.files.emit(GeneratedFile::new(
            "tests/operation-fixtures.json",
            serde_json::to_string_pretty(&json!({"cases":cases}))?,
        )?)?;
        cx.files.emit(GeneratedFile::new(".kaji/operation-test-diagnostics.json",serde_json::to_string_pretty(&json!({"scope":"buffered JSON success; fake urllib driver; not live API acceptance","covered_operations":cases.len(),"diagnostics":diagnostics}))?)?)?;
        cx.files.emit(GeneratedFile::new(
            "tests/__init__.py",
            "# Generated by Kaji: discoverable operation smoke tests.\n",
        )?)?;
        let script = SCRIPT.replace("__MODULE__", &models.module);
        cx.files
            .emit(GeneratedFile::new("tests/test_operations.py", script)?)
    }
}
fn sanitize(schema: &mut SchemaValue) {
    schema.default = None;
    schema.extensions.clear();
    schema.description = None;
    schema.title = None;
    match &mut schema.kind {
        SchemaKind::Object {
            fields,
            additional_properties,
        } => {
            for field in fields {
                sanitize(&mut field.value)
            }
            if let kaji_core::AdditionalProperties::Schema { value } = additional_properties {
                sanitize(value)
            }
        }
        SchemaKind::Array { items } => sanitize(items),
        SchemaKind::OneOf { variants }
        | SchemaKind::AnyOf { variants }
        | SchemaKind::AllOf { variants } => {
            for value in variants {
                sanitize(value)
            }
        }
        _ => {}
    }
}
fn supported(api: &Api, schema: &SchemaValue, seen: &mut Vec<String>) -> Result<()> {
    ensure!(
        schema.constraints.is_empty()
            && schema.enum_values.is_empty()
            && schema.const_value.is_none()
            && schema.format.is_none(),
        "schema constraints/enums/formats need dedicated fixtures"
    );
    ensure!(
        !schema.write_only,
        "writeOnly schema needs explicit response fixture projection"
    );
    match &schema.kind {
        SchemaKind::Reference { reference } => {
            ensure!(
                reference.starts_with("#/components/schemas/"),
                "external/noncomponent reference unsupported"
            );
            let name = reference.rsplit('/').next().unwrap();
            ensure!(
                !seen.iter().any(|n| n == name) && seen.len() < 12,
                "recursive/deep reference unsupported"
            );
            seen.push(name.into());
            supported(
                api,
                &api.schemas
                    .iter()
                    .find(|s| s.name == name)
                    .ok_or_else(|| anyhow::anyhow!("missing referenced schema"))?
                    .value,
                seen,
            )?;
            seen.pop();
        }
        SchemaKind::Object {
            fields,
            additional_properties,
        } => {
            for field in fields {
                supported(api, &field.value, seen)?
            }
            if let kaji_core::AdditionalProperties::Schema { value } = additional_properties {
                supported(api, value, seen)?
            }
        }
        SchemaKind::Array { items } => supported(api, items, seen)?,
        SchemaKind::Boolean
        | SchemaKind::String
        | SchemaKind::Integer
        | SchemaKind::Number
        | SchemaKind::Null => {}
        _ => bail!("unknown/compositional schemas need dedicated fixtures"),
    }
    Ok(())
}
fn sample(api: &Api, schema: &SchemaValue) -> Result<Value> {
    supported(api, schema, &mut vec![])?;
    let mut clean = schema.clone();
    sanitize(&mut clean);
    let report = kaji_core::samples::schema_samples(
        api,
        &clean,
        kaji_core::samples::SampleOptions {
            max_samples: 16,
            max_depth: 12,
            max_array_items: 2,
        },
    );
    ensure!(
        report.diagnostics.is_empty(),
        "bounded fixture could not completely represent schema: {}",
        report.diagnostics.join("; ")
    );
    report
        .samples
        .into_iter()
        .find(|s| s.name == "full")
        .or_else(|| {
            kaji_core::samples::schema_samples(api, &clean, Default::default())
                .samples
                .into_iter()
                .next()
        })
        .map(|s| s.value)
        .ok_or_else(|| anyhow::anyhow!("no bounded sample"))
}
fn case(api: &Api, operation: &kaji_core::Operation, models: &PythonModels) -> Result<Value> {
    ensure!(
        operation.method.as_str() != "HEAD",
        "HEAD excluded from buffered JSON smoke scope"
    );
    let responses = operation
        .responses
        .iter()
        .filter(|r| r.status.starts_with('2'))
        .collect::<Vec<_>>();
    ensure!(
        responses.len() == 1,
        "exactly one declared success response required"
    );
    let response = responses[0];
    let status = response.status.parse::<u16>()?;
    ensure!(
        status != 204 && response.media_types.len() == 1,
        "one buffered JSON representation required"
    );
    let media = &response.media_types[0];
    ensure!(
        media.content_type == "application/json" || media.content_type.ends_with("+json"),
        "stream/binary/text representations unsupported"
    );
    let response_schema = media
        .schema
        .as_ref()
        .ok_or_else(|| anyhow::anyhow!("response schema missing"))?;
    let result = sample(api, response_schema)?;
    let mut kwargs = serde_json::Map::new();
    let mut parameters = Vec::new();
    for parameter in &operation.parameters {
        ensure!(
            matches!(parameter.location.as_str(), "path" | "query" | "header"),
            "cookie/unknown parameter mapping unsupported"
        );
        ensure!(
            !parameter.annotations.contains_key("style")
                && !parameter.annotations.contains_key("explode")
                && !parameter.annotations.contains_key("allowReserved"),
            "parameter serialization overrides need dedicated fixtures"
        );
        let schema = parameter
            .schema
            .as_ref()
            .ok_or_else(|| anyhow::anyhow!("parameter schema missing"))?;
        ensure!(
            matches!(
                schema.kind,
                SchemaKind::String | SchemaKind::Boolean | SchemaKind::Integer | SchemaKind::Number
            ),
            "parameter must be scalar"
        );
        let value = sample(api, schema)?;
        let name = crate::python_parameter_identifier(operation, parameter);
        ensure!(
            !matches!(
                name.as_str(),
                "_kaji_path" | "_kaji_query" | "_kaji_headers" | "result" | "self"
            ),
            "parameter collides with generated operation locals; requires renderer-specific coverage"
        );
        ensure!(
            kwargs.insert(name.clone(), value.clone()).is_none(),
            "parameter name collision"
        );
        parameters.push(json!({"name":parameter.name,"location":parameter.location,"value":value}));
    }
    let mut body = None;
    if let Some(request) = &operation.request_body {
        ensure!(
            request.media_types.len() == 1
                && request.media_types[0].content_type == "application/json",
            "request needs single JSON body"
        );
        let schema = request.media_types[0]
            .schema
            .as_ref()
            .ok_or_else(|| anyhow::anyhow!("request schema missing"))?;
        let value = sample(api, schema)?;
        ensure!(
            kwargs.insert("body".into(), value.clone()).is_none(),
            "body parameter collision"
        );
        body = Some(value);
    }
    Ok(
        json!({"operation":operation.id,"method":crate::symbols::operation_symbols(api)[&operation.id],"http_method":operation.method.as_str(),"path":operation.path,"parameters":parameters,"kwargs":kwargs,"body":body,"status":status,"content_type":media.content_type,"response_model": match &response_schema.kind { SchemaKind::Reference {reference} => models.object_models.get(&reference.rsplit('/').next().unwrap_or(reference).replace("~1", "/").replace("~0", "~")), _=>None },"response":result}),
    )
}
const SCRIPT: &str = r#"# Generated by Kaji. Do not edit.
import io
import json
from email.message import Message
from pathlib import Path
import unittest
from unittest.mock import patch
from urllib.parse import parse_qs, quote, urlsplit
from __MODULE__ import Client, ResponseDecodeError, models

class Response(io.BytesIO):
    def __init__(self, body, status, content_type):
        super().__init__(body)
        self.status = status
        self.headers = Message()
        self.headers['Content-Type'] = content_type
    def __enter__(self): return self
    def __exit__(self, *args): self.close()

class OperationSmokeTests(unittest.TestCase):
    def test_generated_operations(self):
        cases = json.loads(Path(__file__).with_name('operation-fixtures.json').read_text())['cases']
        if not cases:
            self.skipTest('No supported operations; review .kaji/operation-test-diagnostics.json')
        for case in cases:
            with self.subTest(operation=case['operation']):
                calls = []
                path = case['path']
                for parameter in case['parameters']:
                    if parameter['location'] == 'path':
                        path = path.replace('{' + parameter['name'] + '}', quote(str(parameter['value']), safe=''))
                def transport(request, **options):
                    calls.append(request)
                    self.assertEqual(request.get_method(), case['http_method'])
                    parsed = urlsplit(request.full_url)
                    self.assertEqual(parsed.netloc, 'example.invalid')
                    self.assertEqual(parsed.path, path)
                    for parameter in case['parameters']:
                        if parameter['location'] == 'query':
                            self.assertEqual(parse_qs(parsed.query)[parameter['name']], [str(parameter['value'])])
                        elif parameter['location'] == 'header':
                            self.assertEqual(dict((key.lower(), value) for key,value in request.header_items())[parameter['name'].lower()], str(parameter['value']))
                    if case['body'] is not None:
                        self.assertEqual(json.loads(request.data), case['body'])
                    return Response(json.dumps(case['response']).encode(), case['status'], case['content_type'])
                client = Client('https://example.invalid', max_retries=0, validate_responses=True)
                with patch('__MODULE__.runtime.urlopen', transport):
                    result = getattr(client, case['method'])(**case['kwargs'])
                if case.get('response_model'):
                    self.assertIsInstance(result, getattr(models, case['response_model']))
                self.assertEqual(models._to_wire(result), case['response'])
                self.assertEqual(len(calls), 1)
                with patch('__MODULE__.runtime.urlopen', lambda request, **options: Response(b'{invalid', case['status'], case['content_type'])):
                    with self.assertRaises(ResponseDecodeError):
                        getattr(client, case['method'])(**case['kwargs'])

if __name__ == '__main__': unittest.main()
"#;

#[cfg(test)]
mod tests {
    use super::*;
    use kaji_core::{
        AdditionalProperties, Field, HttpMethod, Operation, OperationParameter,
        OperationRequestBody, OperationResponse, Schema, engine::Packages,
    };
    fn fixture() -> Api {
        let string = || SchemaValue::new(SchemaKind::String);
        let object = SchemaValue::new(SchemaKind::Object {
            fields: vec![Field {
                name: "name".into(),
                value: string(),
                required: true,
                annotations: Default::default(),
            }],
            additional_properties: AdditionalProperties::Forbidden,
        });
        let mut api = Api {
            name: "Smoke".into(),
            schemas: vec![Schema::new("Contact", object.clone())],
            ..Default::default()
        };
        let mut read = Operation {
            id: "getContact".into(),
            method: HttpMethod::Get,
            path: "/contacts/{path}".into(),
            responses: vec![OperationResponse::json(
                "200",
                SchemaValue::reference("#/components/schemas/Contact"),
            )],
            ..Default::default()
        };
        for (name, location) in [("path", "path"), ("query", "query"), ("headers", "header")] {
            read.parameters.push(OperationParameter {
                name: name.into(),
                location: location.into(),
                required: true,
                schema: Some(string()),
                description: None,
                annotations: Default::default(),
            })
        }
        api.operations.push(read);
        api.operations.push(Operation {
            id: "createContact".into(),
            method: HttpMethod::Post,
            path: "/contacts".into(),
            request_body: Some(OperationRequestBody::json(object, true)),
            responses: vec![OperationResponse::json(
                "201",
                SchemaValue::reference("#/components/schemas/Contact"),
            )],
            ..Default::default()
        });
        api
    }
    #[test]
    fn explicit_contract_and_unsupported_diagnostics_are_emitted() {
        let mut api = fixture();
        api.operations[0].responses[0].media_types[0].content_type = "text/event-stream".into();
        let sdk = crate::sdk();
        let tests = operation_tests().using_models(sdk.models());
        let tree = Packages::new()
            .package(crate::package("sdk").with(tests).with(sdk))
            .generate(&api, None)
            .unwrap();
        let fixture: Value =
            serde_json::from_str(tree.get("sdk/tests/operation-fixtures.json").unwrap()).unwrap();
        assert_eq!(fixture["cases"].as_array().unwrap().len(), 1);
        assert!(
            tree.get("sdk/.kaji/operation-test-diagnostics.json")
                .unwrap()
                .contains("getContact")
        );
    }
    #[test]
    #[ignore = "requires Python 3.10+; set KAJI_TEST_PYTHON"]
    fn generated_smoke_tests_execute_flat_and_namespaced() {
        for flat in [false, true] {
            let root = tempfile::tempdir().unwrap();
            let sdk = if flat {
                crate::sdk().flat()
            } else {
                crate::sdk().namespaced()
            };
            let tests = operation_tests().models_from(&sdk);
            Packages::new()
                .package(crate::package("sdk").with(sdk).with(tests))
                .generate(&fixture(), None)
                .unwrap()
                .write_to(root.path())
                .unwrap();
            let output = std::process::Command::new(
                std::env::var("KAJI_TEST_PYTHON").unwrap_or_else(|_| "python3".into()),
            )
            .args(["-m", "unittest", "discover", "-v"])
            .current_dir(root.path().join("sdk"))
            .env("PYTHONPATH", root.path().join("sdk/src"))
            .output()
            .unwrap();
            assert!(
                output.status.success(),
                "{}{}",
                String::from_utf8_lossy(&output.stdout),
                String::from_utf8_lossy(&output.stderr)
            );
        }
    }
}
