//! Runnable, language-neutral mock-server package output.
//!
//! The fixture generator lives in `poolster-core`: this module is the
//! first-party release profile that makes those fixtures immediately useful to
//! every generated SDK. Keeping the launcher here means community fixture
//! backends can remain target-neutral while Poolster owns the supported UX.

use anyhow::Result;
use poolster_core::engine::{Language, Meta, Package, Plugin, PluginContext};
use poolster_core::{Api, GeneratedFile, GeneratedTree};

pub struct HttpMock;
impl Language for HttpMock {
    const NAME: &'static str = "httpmock";
    type Settings = ();
    type Workspace = ();
}
pub fn package(directory: impl Into<String>) -> Package<HttpMock> {
    Package::new(directory)
}
pub struct Server {
    meta: Meta,
    http: poolster_core::engine::HttpInput,
    options: MockServerOptions,
}
pub fn server() -> Server {
    Server {
        meta: Meta::new(),
        http: Default::default(),
        options: MockServerOptions::default(),
    }
}
impl Server {
    /// Select an input or transformed HTTP contract.
    pub fn input(
        mut self,
        input: poolster_core::engine::Handle<poolster_core::AdaptedApi>,
    ) -> Self {
        self.http = self.http.input(input);
        self
    }
    pub fn input_models(
        mut self,
        models: poolster_core::engine::Handle<poolster_core::blocks::Blocks<poolster_core::Schema>>,
    ) -> Self {
        self.http = self.http.input_models(models);
        self
    }
    pub fn input_endpoints(
        mut self,
        endpoints: poolster_core::engine::Handle<
            poolster_core::blocks::Blocks<poolster_core::Operation>,
        >,
    ) -> Self {
        self.http = self.http.input_endpoints(endpoints);
        self
    }
    pub fn image(mut self, image: impl Into<String>) -> Self {
        self.options.image = image.into();
        self
    }
    pub fn port(mut self, port: u16) -> Self {
        self.options.port = port;
        self
    }
}
impl Plugin<HttpMock> for Server {
    fn kind(&self) -> &'static str {
        "httpmock-server"
    }
    fn meta(&self) -> &Meta {
        &self.meta
    }
    fn requires(&self) -> Vec<poolster_core::engine::Requirement> {
        self.http.requirements()
    }
    fn supports_native_input(&self) -> bool {
        self.http.is_explicit()
    }
    fn generate(&self, cx: &mut PluginContext<'_, HttpMock>) -> Result<()> {
        self.http.run(cx, |cx| {
            cx.files.append_from(
                generate(cx.api, "__mock", &self.options)?,
                std::path::Path::new("__mock"),
            )
        })
    }
}

/// Configuration for Poolster's standalone mock-server target.
///
/// `image` defaults to the official httpmock standalone image. Pin the image
/// in a release profile when a build must be fully reproducible.
#[derive(Clone, Debug, PartialEq, Eq)]
struct MockServerOptions {
    pub image: String,
    pub port: u16,
}

impl Default for MockServerOptions {
    fn default() -> Self {
        Self {
            image: "httpmock/httpmock".into(),
            port: 5000,
        }
    }
}

fn generate(api: &Api, output_dir: &str, options: &MockServerOptions) -> Result<GeneratedTree> {
    let mut tree = GeneratedTree::default();
    let root = output_dir.trim_matches('/');

    // Fixture generation intentionally remains in the target-neutral codegen
    // crate. This profile only establishes the runnable package convention.
    let fixtures = poolster_core::httpmock::generate_httpmock_fixtures(
        api,
        &poolster_core::httpmock::HttpmockFixtureConfig {
            output_dir: format!("{root}/fixtures"),
            include_readme: true,
        },
    )?;
    for fixture in fixtures {
        tree.insert(fixture)?;
    }

    tree.insert(GeneratedFile::new(
        format!("{root}/Dockerfile"),
        dockerfile(options),
    )?)?;
    tree.insert(GeneratedFile::new(
        format!("{root}/compose.yaml"),
        compose(options),
    )?)?;
    tree.insert(GeneratedFile::new(format!("{root}/run.sh"), run_script())?)?;
    tree.insert(GeneratedFile::new(
        format!("{root}/.env.example"),
        format!("POOLSTER_MOCK_PORT={}\n", options.port),
    )?)?;
    tree.insert(GeneratedFile::new(
        format!("{root}/README.md"),
        readme(api, options),
    )?)?;
    Ok(tree)
}

fn dockerfile(options: &MockServerOptions) -> String {
    format!(
        "# Generated by Poolster. Edit fixture YAML, not this image contract.\nFROM {}\n\nCOPY fixtures /poolster/fixtures\nENV HTTPMOCK_EXPOSE=1\nENV HTTPMOCK_MOCK_FILES_DIR=/poolster/fixtures\nEXPOSE {}\n",
        options.image, options.port
    )
}

fn compose(options: &MockServerOptions) -> String {
    format!(
        "# Generated by Poolster. `docker compose up --build` starts the contract mock.\nservices:\n  poolster-mock:\n    build:\n      context: .\n    ports:\n      - \"${{POOLSTER_MOCK_PORT:-{}}}:{}\"\n    environment:\n      HTTPMOCK_EXPOSE: \"1\"\n      HTTPMOCK_MOCK_FILES_DIR: /poolster/fixtures\n",
        options.port, options.port
    )
}

fn run_script() -> String {
    "#!/bin/sh\n# Generated by Poolster. `sh ./run.sh` starts the mock at POOLSTER_MOCK_PORT (default 5000).\nset -eu\nexec docker compose -f \"$(dirname \"$0\")/compose.yaml\" up --build \"$@\"\n".into()
}

fn readme(api: &Api, options: &MockServerOptions) -> String {
    format!(
        "# {} mock server\n\nThis is a language-neutral HTTP mock generated from the same OpenAPI contract as the SDKs. Every generated SDK can use it by setting its base URL to `http://localhost:{}`.\n\n## Run\n\n```sh\ncp .env.example .env # optional: choose a different host port\ndocker compose up --build\n# or: sh ./run.sh\n```\n\nThe server reads `fixtures/*.yaml` on startup through [httpmock](https://httpmock.rs/). Those fixtures match HTTP method, path, and any OpenAPI or `x-poolster-mock` scenario conditions. A missing match returns `404`, which makes unmodelled calls visible in tests.\n\n## Use from an SDK\n\nPass `http://localhost:${{POOLSTER_MOCK_PORT:-{}}}` as the SDK base URL. Keep test-only scenario selectors (for example `x-test-scenario`) in the request that invokes the SDK; the generated fixture documents the selector.\n\n## Customize safely\n\n- Regenerate this directory when the OpenAPI contract changes.\n- Put product-specific scenarios in `x-poolster-mock` in the OpenAPI document so they travel with the contract.\n- The generated fixture files are intentionally plain YAML. You may edit them for a local experiment, but commit source-contract scenarios for durable behavior.\n\nSee [`fixtures/README.md`](fixtures/README.md) for the generated route inventory.\n",
        api.name, options.port, options.port
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use poolster_core::{HttpMethod, Operation};
    use serde_json::json;

    #[test]
    fn mock_server_target_emits_a_runnable_package_without_sdk_runtime() {
        let api = Api {
            name: "Pet API".into(),
            version: "1.0.0".into(),
            operations: vec![Operation {
                id: "listPets".into(),
                method: HttpMethod::Get,
                path: "/pets".into(),
                ..Operation::default()
            }],
            ..Api::default()
        };
        let tree = generate(&api, "mocks", &MockServerOptions::default()).unwrap();
        assert!(
            tree.get("mocks/Dockerfile")
                .unwrap()
                .contains("httpmock/httpmock")
        );
        assert!(
            tree.get("mocks/compose.yaml")
                .unwrap()
                .contains("POOLSTER_MOCK_PORT")
        );
        assert!(tree.get("mocks/run.sh").unwrap().contains("docker compose"));
        assert!(
            tree.iter()
                .any(|(path, _)| path.starts_with("mocks/fixtures")
                    && path.extension().is_some_and(|ext| ext == "yaml"))
        );
    }

    #[test]
    fn mock_server_profile_preserves_contract_scenarios_in_its_fixture() {
        let api = Api {
            name: "Contact API".into(),
            version: "1.0.0".into(),
            operations: vec![Operation {
                id: "listContacts".into(),
                method: HttpMethod::Get,
                path: "/contacts".into(),
                annotations: std::collections::BTreeMap::from([(
                    "x-poolster-mock".into(),
                    json!({
                        "scenarios": [{
                            "name": "rate-limited",
                            "when": { "headers": { "x-test-scenario": "rate-limited" } },
                            "response": {
                                "status": 429,
                                "headers": { "retry-after": "1" },
                                "body": { "message": "Slow down" }
                            }
                        }]
                    }),
                )]),
                ..Operation::default()
            }],
            ..Api::default()
        };
        let tree = generate(&api, "mocks", &MockServerOptions::default()).unwrap();
        let fixture = tree
            .iter()
            .find_map(|(path, contents)| {
                (path.starts_with("mocks/fixtures")
                    && path
                        .extension()
                        .is_some_and(|extension| extension == "yaml"))
                .then_some(contents)
            })
            .unwrap();
        assert!(fixture.contains("# Scenario: rate-limited"), "{fixture}");
        assert!(fixture.contains("x-test-scenario"));
        assert!(fixture.contains("status: 429"));
    }
}
