//! HTTP-specific backend implementation.
mod assembly;
pub(crate) use assembly::*;
mod cursor;
pub(crate) use cursor::*;
mod docs;
pub(crate) use docs::*;
mod errors;
pub(crate) use errors::*;
mod facade;
pub(crate) use facade::*;
mod layout;
pub(crate) use layout::*;
mod models;
pub(crate) use models::*;
mod names;
pub(crate) use names::*;
mod operations;
pub(crate) use operations::*;
mod request;
pub(crate) use request::*;
mod request_body;
pub(crate) use request_body::*;
mod runtime;
pub(crate) use runtime::*;
mod types;
pub(crate) use types::*;
